
// Generated by Cadence Genus(TM) Synthesis Solution 25.12-s067_1
// Generated on: Aug 22 2026 16:04:22 -03 (Aug 22 2026 19:04:22 UTC)

// Verification Directory fv/aFifo 

module GrayCounter_COUNTER_WIDTH5_28(GrayCount_out, Enable_in,
     Clear_in, clk);
  input Enable_in, Clear_in, clk;
  output [4:0] GrayCount_out;
  wire Enable_in, Clear_in, clk;
  wire [4:0] GrayCount_out;
  wire [4:0] BinaryCount;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13, n_14, n_15, n_16;
  wire n_17, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_32;
  DFFHQX1 \BinaryCount_reg[3] (.CK (clk), .D (n_28), .Q
       (BinaryCount[3]));
  DFFHQX1 \BinaryCount_reg[4] (.CK (clk), .D (n_27), .Q
       (BinaryCount[4]));
  DFFHQX1 \BinaryCount_reg[2] (.CK (clk), .D (n_26), .Q
       (BinaryCount[2]));
  OAI22X1 g919__2398(.A0 (n_16), .A1 (n_23), .B0 (n_3), .B1 (n_25), .Y
       (n_28));
  OA22X1 g920__5107(.A0 (n_15), .A1 (n_24), .B0 (BinaryCount[4]), .B1
       (n_22), .Y (n_27));
  AOI21X1 g921__6260(.A0 (n_2), .A1 (n_20), .B0 (n_25), .Y (n_26));
  DFFHQX1 \BinaryCount_reg[1] (.CK (clk), .D (n_21), .Q
       (GrayCount_out[0]));
  INVX1 g923(.A (n_24), .Y (n_25));
  NOR2X1 g924__4319(.A (Clear_in), .B (n_22), .Y (n_24));
  DFFHQX1 \GrayCount_out_reg[1] (.CK (clk), .D (n_17), .Q
       (GrayCount_out[1]));
  DFFHQX1 \GrayCount_out_reg[2] (.CK (clk), .D (n_19), .Q
       (GrayCount_out[2]));
  INVX1 g927(.A (n_22), .Y (n_23));
  AOI211XL g928__8428(.A0 (n_0), .A1 (n_7), .B0 (Clear_in), .C0 (n_13),
       .Y (n_21));
  DFFHQX1 \GrayCount_out_reg[3] (.CK (clk), .D (n_32), .Q
       (GrayCount_out[3]));
  NOR2X1 g930__5526(.A (n_2), .B (n_20), .Y (n_22));
  INVX1 g931(.A (n_13), .Y (n_20));
  DFFHQX1 \GrayCount_out_reg[4] (.CK (clk), .D (n_14), .Q
       (GrayCount_out[4]));
  SDFFQX1 \BinaryCount_reg[0] (.CK (clk), .D (n_4), .SI (n_6), .SE
       (BinaryCount[0]), .Q (BinaryCount[0]));
  OAI2BB1X1 g934__6783(.A0N (GrayCount_out[2]), .A1N (n_5), .B0 (n_16),
       .Y (n_19));
  OAI22X1 g936__1617(.A0 (n_9), .A1 (n_6), .B0 (n_1), .B1 (n_4), .Y
       (n_17));
  OR2X1 g937__2802(.A (n_10), .B (n_6), .Y (n_16));
  OAI2BB1X1 g938__1705(.A0N (GrayCount_out[4]), .A1N (n_5), .B0 (n_11),
       .Y (n_14));
  NOR2X1 g939__5122(.A (n_8), .B (n_6), .Y (n_15));
  NAND2BX1 g941__7098(.AN (n_6), .B (BinaryCount[4]), .Y (n_11));
  NOR2X1 g942__6131(.A (n_0), .B (n_7), .Y (n_13));
  AOI22X1 g943__1881(.A0 (BinaryCount[2]), .A1 (n_3), .B0
       (BinaryCount[3]), .B1 (n_2), .Y (n_10));
  AOI22X1 g944__5115(.A0 (GrayCount_out[0]), .A1 (n_2), .B0
       (BinaryCount[2]), .B1 (n_0), .Y (n_9));
  MX2XL g945__7482(.A (n_3), .B (BinaryCount[3]), .S0 (BinaryCount[4]),
       .Y (n_8));
  NAND2X1 g946__4733(.A (BinaryCount[0]), .B (Enable_in), .Y (n_7));
  INVX1 g947(.A (n_5), .Y (n_4));
  NAND2BX1 g948__6161(.AN (Clear_in), .B (Enable_in), .Y (n_6));
  NOR2X1 g949__9315(.A (Clear_in), .B (Enable_in), .Y (n_5));
  INVX1 g950(.A (BinaryCount[3]), .Y (n_3));
  INVX1 g951(.A (BinaryCount[2]), .Y (n_2));
  INVX1 g952(.A (GrayCount_out[1]), .Y (n_1));
  INVX1 g953(.A (GrayCount_out[0]), .Y (n_0));
  AO21XL g2(.A0 (GrayCount_out[3]), .A1 (n_5), .B0 (n_15), .Y (n_32));
endmodule

module GrayCounter_COUNTER_WIDTH5(GrayCount_out, Enable_in, Clear_in,
     clk);
  input Enable_in, Clear_in, clk;
  output [4:0] GrayCount_out;
  wire Enable_in, Clear_in, clk;
  wire [4:0] GrayCount_out;
  wire [4:0] BinaryCount;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13, n_14, n_15, n_16;
  wire n_17, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_32;
  DFFHQX1 \BinaryCount_reg[3] (.CK (clk), .D (n_28), .Q
       (BinaryCount[3]));
  DFFHQX1 \BinaryCount_reg[4] (.CK (clk), .D (n_27), .Q
       (BinaryCount[4]));
  DFFHQX1 \BinaryCount_reg[2] (.CK (clk), .D (n_26), .Q
       (BinaryCount[2]));
  OAI22X1 g919__9945(.A0 (n_16), .A1 (n_23), .B0 (n_3), .B1 (n_25), .Y
       (n_28));
  OA22X1 g920__2883(.A0 (n_15), .A1 (n_24), .B0 (BinaryCount[4]), .B1
       (n_22), .Y (n_27));
  AOI21X1 g921__2346(.A0 (n_2), .A1 (n_20), .B0 (n_25), .Y (n_26));
  DFFHQX1 \BinaryCount_reg[1] (.CK (clk), .D (n_21), .Q
       (GrayCount_out[0]));
  INVX1 g923(.A (n_24), .Y (n_25));
  NOR2X1 g924__1666(.A (Clear_in), .B (n_22), .Y (n_24));
  DFFHQX1 \GrayCount_out_reg[1] (.CK (clk), .D (n_17), .Q
       (GrayCount_out[1]));
  DFFHQX1 \GrayCount_out_reg[2] (.CK (clk), .D (n_19), .Q
       (GrayCount_out[2]));
  INVX1 g927(.A (n_22), .Y (n_23));
  AOI211XL g928__7410(.A0 (n_0), .A1 (n_7), .B0 (Clear_in), .C0 (n_13),
       .Y (n_21));
  DFFHQX1 \GrayCount_out_reg[3] (.CK (clk), .D (n_32), .Q
       (GrayCount_out[3]));
  NOR2X1 g930__6417(.A (n_2), .B (n_20), .Y (n_22));
  INVX1 g931(.A (n_13), .Y (n_20));
  DFFHQX1 \GrayCount_out_reg[4] (.CK (clk), .D (n_14), .Q
       (GrayCount_out[4]));
  SDFFQX1 \BinaryCount_reg[0] (.CK (clk), .D (n_4), .SI (n_6), .SE
       (BinaryCount[0]), .Q (BinaryCount[0]));
  OAI2BB1X1 g934__5477(.A0N (GrayCount_out[2]), .A1N (n_5), .B0 (n_16),
       .Y (n_19));
  OAI22X1 g936__5107(.A0 (n_9), .A1 (n_6), .B0 (n_1), .B1 (n_4), .Y
       (n_17));
  OR2X1 g937__6260(.A (n_10), .B (n_6), .Y (n_16));
  OAI2BB1X1 g938__4319(.A0N (GrayCount_out[4]), .A1N (n_5), .B0 (n_11),
       .Y (n_14));
  NOR2X1 g939__8428(.A (n_8), .B (n_6), .Y (n_15));
  NAND2BX1 g941__6783(.AN (n_6), .B (BinaryCount[4]), .Y (n_11));
  NOR2X1 g942__3680(.A (n_0), .B (n_7), .Y (n_13));
  AOI22X1 g943__1617(.A0 (BinaryCount[2]), .A1 (n_3), .B0
       (BinaryCount[3]), .B1 (n_2), .Y (n_10));
  AOI22X1 g944__2802(.A0 (GrayCount_out[0]), .A1 (n_2), .B0
       (BinaryCount[2]), .B1 (n_0), .Y (n_9));
  MX2XL g945__1705(.A (n_3), .B (BinaryCount[3]), .S0 (BinaryCount[4]),
       .Y (n_8));
  NAND2X1 g946__5122(.A (BinaryCount[0]), .B (Enable_in), .Y (n_7));
  INVX1 g947(.A (n_5), .Y (n_4));
  NAND2BX1 g948__8246(.AN (Clear_in), .B (Enable_in), .Y (n_6));
  NOR2X1 g949__7098(.A (Clear_in), .B (Enable_in), .Y (n_5));
  INVX1 g950(.A (BinaryCount[3]), .Y (n_3));
  INVX1 g951(.A (BinaryCount[2]), .Y (n_2));
  INVX1 g952(.A (GrayCount_out[1]), .Y (n_1));
  INVX1 g953(.A (GrayCount_out[0]), .Y (n_0));
  AO21XL g2(.A0 (GrayCount_out[3]), .A1 (n_5), .B0 (n_15), .Y (n_32));
endmodule

module aFifo(Data_out, Empty_out, ReadEn_in, RClk, Data_in, Full_out,
     WriteEn_in, WClk, Clear_in);
  input ReadEn_in, RClk, WriteEn_in, WClk, Clear_in;
  input [7:0] Data_in;
  output [7:0] Data_out;
  output Empty_out, Full_out;
  wire ReadEn_in, RClk, WriteEn_in, WClk, Clear_in;
  wire [7:0] Data_in;
  wire [7:0] Data_out;
  wire Empty_out, Full_out;
  wire [4:0] pNextWordToRead;
  wire [4:0] pNextWordToWrite;
  wire [4:0] Next_Write_addr_2;
  wire [4:0] Next_Read_addr_2;
  wire [4:0] Next_Read_addr_1;
  wire [4:0] Next_Write_addr_1;
  wire [7:0] \Mem[0] ;
  wire [7:0] \Mem[1] ;
  wire [7:0] \Mem[2] ;
  wire [7:0] \Mem[3] ;
  wire [7:0] \Mem[4] ;
  wire [7:0] \Mem[5] ;
  wire [7:0] \Mem[6] ;
  wire [7:0] \Mem[7] ;
  wire [7:0] \Mem[8] ;
  wire [7:0] \Mem[9] ;
  wire [7:0] \Mem[10] ;
  wire [7:0] \Mem[11] ;
  wire [7:0] \Mem[12] ;
  wire [7:0] \Mem[13] ;
  wire [7:0] \Mem[14] ;
  wire [7:0] \Mem[15] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_196;
  GrayCounter_COUNTER_WIDTH5_28 GrayCounter_pRd(.GrayCount_out
       (pNextWordToRead), .Enable_in (n_180), .Clear_in (Clear_in),
       .clk (RClk));
  GrayCounter_COUNTER_WIDTH5 GrayCounter_pWr(.GrayCount_out
       (pNextWordToWrite), .Enable_in (n_179), .Clear_in (Clear_in),
       .clk (WClk));
  INVX1 g3223(.A (n_182), .Y (n_180));
  INVX1 g3222(.A (n_181), .Y (n_179));
  DFFHQX1 \Next_Write_addr_2_reg[1] (.CK (RClk), .D (n_173), .Q
       (Next_Write_addr_2[1]));
  DFFHQX1 \Next_Write_addr_2_reg[2] (.CK (RClk), .D (n_170), .Q
       (Next_Write_addr_2[2]));
  DFFHQX1 \Next_Write_addr_2_reg[4] (.CK (RClk), .D (n_169), .Q
       (Next_Write_addr_2[4]));
  DFFQXL \Next_Read_addr_2_reg[4] (.CK (WClk), .D (n_171), .Q
       (Next_Read_addr_2[4]));
  DFFHQX1 \Next_Read_addr_2_reg[3] (.CK (WClk), .D (n_174), .Q
       (Next_Read_addr_2[3]));
  DFFQXL \Next_Read_addr_2_reg[2] (.CK (WClk), .D (n_178), .Q
       (Next_Read_addr_2[2]));
  DFFHQX1 \Next_Write_addr_2_reg[0] (.CK (RClk), .D (n_172), .Q
       (Next_Write_addr_2[0]));
  DFFHQX1 \Next_Write_addr_2_reg[3] (.CK (RClk), .D (n_175), .Q
       (Next_Write_addr_2[3]));
  DFFQXL \Next_Read_addr_2_reg[1] (.CK (WClk), .D (n_177), .Q
       (Next_Read_addr_2[1]));
  DFFHQX1 \Next_Read_addr_2_reg[0] (.CK (WClk), .D (n_176), .Q
       (Next_Read_addr_2[0]));
  NOR2BX1 g3414__6131(.AN (Next_Read_addr_1[2]), .B (Clear_in), .Y
       (n_178));
  NOR2BX1 g3415__1881(.AN (Next_Read_addr_1[1]), .B (Clear_in), .Y
       (n_177));
  NOR2BX1 g3416__5115(.AN (Next_Read_addr_1[0]), .B (Clear_in), .Y
       (n_176));
  NOR2BX1 g3417__7482(.AN (Next_Write_addr_1[3]), .B (Clear_in), .Y
       (n_175));
  NOR2BX1 g3418__4733(.AN (Next_Read_addr_1[3]), .B (Clear_in), .Y
       (n_174));
  NOR2BX1 g3419__6161(.AN (Next_Write_addr_1[1]), .B (Clear_in), .Y
       (n_173));
  NOR2BX1 g3420__9315(.AN (Next_Write_addr_1[0]), .B (Clear_in), .Y
       (n_172));
  NOR2BX1 g3421__9945(.AN (Next_Read_addr_1[4]), .B (Clear_in), .Y
       (n_171));
  NOR2BX1 g3422__2883(.AN (Next_Write_addr_1[2]), .B (Clear_in), .Y
       (n_170));
  NOR2BX1 g3423__2346(.AN (Next_Write_addr_1[4]), .B (Clear_in), .Y
       (n_169));
  DFFQXL \Next_Read_addr_1_reg[2] (.CK (WClk), .D (n_166), .Q
       (Next_Read_addr_1[2]));
  DFFQXL \Next_Read_addr_1_reg[1] (.CK (WClk), .D (n_167), .Q
       (Next_Read_addr_1[1]));
  DFFQXL \Next_Read_addr_1_reg[0] (.CK (WClk), .D (n_168), .Q
       (Next_Read_addr_1[0]));
  DFFQXL \Next_Read_addr_1_reg[3] (.CK (WClk), .D (n_165), .Q
       (Next_Read_addr_1[3]));
  DFFQXL \Next_Read_addr_1_reg[4] (.CK (WClk), .D (n_164), .Q
       (Next_Read_addr_1[4]));
  DFFQXL \Next_Write_addr_1_reg[2] (.CK (RClk), .D (n_161), .Q
       (Next_Write_addr_1[2]));
  DFFQXL \Next_Write_addr_1_reg[1] (.CK (RClk), .D (n_162), .Q
       (Next_Write_addr_1[1]));
  DFFQXL \Next_Write_addr_1_reg[0] (.CK (RClk), .D (n_163), .Q
       (Next_Write_addr_1[0]));
  DFFQXL \Next_Write_addr_1_reg[3] (.CK (RClk), .D (n_159), .Q
       (Next_Write_addr_1[3]));
  DFFQXL \Next_Write_addr_1_reg[4] (.CK (RClk), .D (n_160), .Q
       (Next_Write_addr_1[4]));
  NOR2BX1 g3434__1666(.AN (pNextWordToRead[0]), .B (Clear_in), .Y
       (n_168));
  NOR2BX1 g3435__7410(.AN (pNextWordToRead[1]), .B (Clear_in), .Y
       (n_167));
  NOR2BX1 g3436__6417(.AN (pNextWordToRead[2]), .B (Clear_in), .Y
       (n_166));
  NOR2BX1 g3437__5477(.AN (pNextWordToRead[3]), .B (Clear_in), .Y
       (n_165));
  NOR2BX1 g3438__2398(.AN (pNextWordToRead[4]), .B (Clear_in), .Y
       (n_164));
  NAND2BX1 g3439__5107(.AN (Empty_out), .B (ReadEn_in), .Y (n_182));
  NOR2BX1 g3440__6260(.AN (pNextWordToWrite[0]), .B (Clear_in), .Y
       (n_163));
  NOR2BX1 g3441__4319(.AN (pNextWordToWrite[1]), .B (Clear_in), .Y
       (n_162));
  NOR2BX1 g3442__8428(.AN (pNextWordToWrite[2]), .B (Clear_in), .Y
       (n_161));
  NOR2BX1 g3443__5526(.AN (pNextWordToWrite[4]), .B (Clear_in), .Y
       (n_160));
  NOR2BX1 g3444__6783(.AN (pNextWordToWrite[3]), .B (Clear_in), .Y
       (n_159));
  NAND2BX1 g3445__3680(.AN (Full_out), .B (WriteEn_in), .Y (n_181));
  DFFQX2 \Data_out_reg[0] (.CK (RClk), .D (n_152), .Q (Data_out[0]));
  DFFQX2 \Data_out_reg[1] (.CK (RClk), .D (n_151), .Q (Data_out[1]));
  DFFQX2 \Data_out_reg[2] (.CK (RClk), .D (n_157), .Q (Data_out[2]));
  DFFQX2 \Data_out_reg[3] (.CK (RClk), .D (n_153), .Q (Data_out[3]));
  DFFQX2 \Data_out_reg[4] (.CK (RClk), .D (n_156), .Q (Data_out[4]));
  DFFQX2 \Data_out_reg[5] (.CK (RClk), .D (n_158), .Q (Data_out[5]));
  DFFQX2 \Data_out_reg[6] (.CK (RClk), .D (n_155), .Q (Data_out[6]));
  DFFQX2 \Data_out_reg[7] (.CK (RClk), .D (n_154), .Q (Data_out[7]));
  DFFQX2 Empty_out_reg(.CK (RClk), .D (n_134), .Q (Empty_out));
  DFFQX2 Full_out_reg(.CK (WClk), .D (n_131), .Q (Full_out));
  SDFFQX1 \Mem_reg[0][0] (.CK (WClk), .D (Data_in[0]), .SI (\Mem[0]
       [0]), .SE (n_55), .Q (\Mem[0] [0]));
  SDFFQX1 \Mem_reg[0][1] (.CK (WClk), .D (Data_in[1]), .SI (\Mem[0]
       [1]), .SE (n_55), .Q (\Mem[0] [1]));
  SDFFQX1 \Mem_reg[0][2] (.CK (WClk), .D (Data_in[2]), .SI (\Mem[0]
       [2]), .SE (n_55), .Q (\Mem[0] [2]));
  SDFFQX1 \Mem_reg[0][3] (.CK (WClk), .D (Data_in[3]), .SI (\Mem[0]
       [3]), .SE (n_55), .Q (\Mem[0] [3]));
  SDFFQX1 \Mem_reg[0][4] (.CK (WClk), .D (Data_in[4]), .SI (\Mem[0]
       [4]), .SE (n_55), .Q (\Mem[0] [4]));
  SDFFQX1 \Mem_reg[0][5] (.CK (WClk), .D (Data_in[5]), .SI (\Mem[0]
       [5]), .SE (n_55), .Q (\Mem[0] [5]));
  SDFFQX1 \Mem_reg[0][6] (.CK (WClk), .D (Data_in[6]), .SI (\Mem[0]
       [6]), .SE (n_55), .Q (\Mem[0] [6]));
  SDFFQX1 \Mem_reg[0][7] (.CK (WClk), .D (Data_in[7]), .SI (\Mem[0]
       [7]), .SE (n_55), .Q (\Mem[0] [7]));
  SDFFQX1 \Mem_reg[1][0] (.CK (WClk), .D (Data_in[0]), .SI (\Mem[1]
       [0]), .SE (n_65), .Q (\Mem[1] [0]));
  SDFFQX1 \Mem_reg[1][1] (.CK (WClk), .D (Data_in[1]), .SI (\Mem[1]
       [1]), .SE (n_65), .Q (\Mem[1] [1]));
  SDFFQX1 \Mem_reg[1][2] (.CK (WClk), .D (Data_in[2]), .SI (\Mem[1]
       [2]), .SE (n_65), .Q (\Mem[1] [2]));
  SDFFQX1 \Mem_reg[1][3] (.CK (WClk), .D (Data_in[3]), .SI (\Mem[1]
       [3]), .SE (n_65), .Q (\Mem[1] [3]));
  SDFFQX1 \Mem_reg[1][4] (.CK (WClk), .D (Data_in[4]), .SI (\Mem[1]
       [4]), .SE (n_65), .Q (\Mem[1] [4]));
  SDFFQX1 \Mem_reg[1][5] (.CK (WClk), .D (Data_in[5]), .SI (\Mem[1]
       [5]), .SE (n_65), .Q (\Mem[1] [5]));
  SDFFQX1 \Mem_reg[1][6] (.CK (WClk), .D (Data_in[6]), .SI (\Mem[1]
       [6]), .SE (n_65), .Q (\Mem[1] [6]));
  SDFFQX1 \Mem_reg[1][7] (.CK (WClk), .D (Data_in[7]), .SI (\Mem[1]
       [7]), .SE (n_65), .Q (\Mem[1] [7]));
  SDFFQX1 \Mem_reg[2][0] (.CK (WClk), .D (Data_in[0]), .SI (\Mem[2]
       [0]), .SE (n_54), .Q (\Mem[2] [0]));
  SDFFQX1 \Mem_reg[2][1] (.CK (WClk), .D (Data_in[1]), .SI (\Mem[2]
       [1]), .SE (n_54), .Q (\Mem[2] [1]));
  SDFFQX1 \Mem_reg[2][2] (.CK (WClk), .D (Data_in[2]), .SI (\Mem[2]
       [2]), .SE (n_54), .Q (\Mem[2] [2]));
  SDFFQX1 \Mem_reg[2][3] (.CK (WClk), .D (Data_in[3]), .SI (\Mem[2]
       [3]), .SE (n_54), .Q (\Mem[2] [3]));
  SDFFQX1 \Mem_reg[2][4] (.CK (WClk), .D (Data_in[4]), .SI (\Mem[2]
       [4]), .SE (n_54), .Q (\Mem[2] [4]));
  SDFFQX1 \Mem_reg[2][5] (.CK (WClk), .D (Data_in[5]), .SI (\Mem[2]
       [5]), .SE (n_54), .Q (\Mem[2] [5]));
  SDFFQX1 \Mem_reg[2][6] (.CK (WClk), .D (Data_in[6]), .SI (\Mem[2]
       [6]), .SE (n_54), .Q (\Mem[2] [6]));
  SDFFQX1 \Mem_reg[2][7] (.CK (WClk), .D (Data_in[7]), .SI (\Mem[2]
       [7]), .SE (n_54), .Q (\Mem[2] [7]));
  SDFFQX1 \Mem_reg[3][0] (.CK (WClk), .D (\Mem[3] [0]), .SI
       (Data_in[0]), .SE (n_59), .Q (\Mem[3] [0]));
  SDFFQX1 \Mem_reg[3][1] (.CK (WClk), .D (\Mem[3] [1]), .SI
       (Data_in[1]), .SE (n_59), .Q (\Mem[3] [1]));
  SDFFQX1 \Mem_reg[3][2] (.CK (WClk), .D (\Mem[3] [2]), .SI
       (Data_in[2]), .SE (n_59), .Q (\Mem[3] [2]));
  SDFFQX1 \Mem_reg[3][3] (.CK (WClk), .D (\Mem[3] [3]), .SI
       (Data_in[3]), .SE (n_59), .Q (\Mem[3] [3]));
  SDFFQX1 \Mem_reg[3][4] (.CK (WClk), .D (\Mem[3] [4]), .SI
       (Data_in[4]), .SE (n_59), .Q (\Mem[3] [4]));
  SDFFQX1 \Mem_reg[3][5] (.CK (WClk), .D (\Mem[3] [5]), .SI
       (Data_in[5]), .SE (n_59), .Q (\Mem[3] [5]));
  SDFFQX1 \Mem_reg[3][6] (.CK (WClk), .D (\Mem[3] [6]), .SI
       (Data_in[6]), .SE (n_59), .Q (\Mem[3] [6]));
  SDFFQX1 \Mem_reg[3][7] (.CK (WClk), .D (\Mem[3] [7]), .SI
       (Data_in[7]), .SE (n_59), .Q (\Mem[3] [7]));
  SDFFQX1 \Mem_reg[4][0] (.CK (WClk), .D (Data_in[0]), .SI (\Mem[4]
       [0]), .SE (n_61), .Q (\Mem[4] [0]));
  SDFFQX1 \Mem_reg[4][1] (.CK (WClk), .D (Data_in[1]), .SI (\Mem[4]
       [1]), .SE (n_61), .Q (\Mem[4] [1]));
  SDFFQX1 \Mem_reg[4][2] (.CK (WClk), .D (Data_in[2]), .SI (\Mem[4]
       [2]), .SE (n_61), .Q (\Mem[4] [2]));
  SDFFQX1 \Mem_reg[4][3] (.CK (WClk), .D (Data_in[3]), .SI (\Mem[4]
       [3]), .SE (n_61), .Q (\Mem[4] [3]));
  SDFFQX1 \Mem_reg[4][4] (.CK (WClk), .D (Data_in[4]), .SI (\Mem[4]
       [4]), .SE (n_61), .Q (\Mem[4] [4]));
  SDFFQX1 \Mem_reg[4][5] (.CK (WClk), .D (Data_in[5]), .SI (\Mem[4]
       [5]), .SE (n_61), .Q (\Mem[4] [5]));
  SDFFQX1 \Mem_reg[4][6] (.CK (WClk), .D (Data_in[6]), .SI (\Mem[4]
       [6]), .SE (n_61), .Q (\Mem[4] [6]));
  SDFFQX1 \Mem_reg[4][7] (.CK (WClk), .D (Data_in[7]), .SI (\Mem[4]
       [7]), .SE (n_61), .Q (\Mem[4] [7]));
  SDFFQX1 \Mem_reg[5][0] (.CK (WClk), .D (Data_in[0]), .SI (\Mem[5]
       [0]), .SE (n_64), .Q (\Mem[5] [0]));
  SDFFQX1 \Mem_reg[5][1] (.CK (WClk), .D (Data_in[1]), .SI (\Mem[5]
       [1]), .SE (n_64), .Q (\Mem[5] [1]));
  SDFFQX1 \Mem_reg[5][2] (.CK (WClk), .D (Data_in[2]), .SI (\Mem[5]
       [2]), .SE (n_64), .Q (\Mem[5] [2]));
  SDFFQX1 \Mem_reg[5][3] (.CK (WClk), .D (Data_in[3]), .SI (\Mem[5]
       [3]), .SE (n_64), .Q (\Mem[5] [3]));
  SDFFQX1 \Mem_reg[5][4] (.CK (WClk), .D (Data_in[4]), .SI (\Mem[5]
       [4]), .SE (n_64), .Q (\Mem[5] [4]));
  SDFFQX1 \Mem_reg[5][5] (.CK (WClk), .D (Data_in[5]), .SI (\Mem[5]
       [5]), .SE (n_64), .Q (\Mem[5] [5]));
  SDFFQX1 \Mem_reg[5][6] (.CK (WClk), .D (Data_in[6]), .SI (\Mem[5]
       [6]), .SE (n_64), .Q (\Mem[5] [6]));
  SDFFQX1 \Mem_reg[5][7] (.CK (WClk), .D (Data_in[7]), .SI (\Mem[5]
       [7]), .SE (n_64), .Q (\Mem[5] [7]));
  SDFFQX1 \Mem_reg[6][0] (.CK (WClk), .D (Data_in[0]), .SI (\Mem[6]
       [0]), .SE (n_60), .Q (\Mem[6] [0]));
  SDFFQX1 \Mem_reg[6][1] (.CK (WClk), .D (Data_in[1]), .SI (\Mem[6]
       [1]), .SE (n_60), .Q (\Mem[6] [1]));
  SDFFQX1 \Mem_reg[6][2] (.CK (WClk), .D (Data_in[2]), .SI (\Mem[6]
       [2]), .SE (n_60), .Q (\Mem[6] [2]));
  SDFFQX1 \Mem_reg[6][3] (.CK (WClk), .D (Data_in[3]), .SI (\Mem[6]
       [3]), .SE (n_60), .Q (\Mem[6] [3]));
  SDFFQX1 \Mem_reg[6][4] (.CK (WClk), .D (Data_in[4]), .SI (\Mem[6]
       [4]), .SE (n_60), .Q (\Mem[6] [4]));
  SDFFQX1 \Mem_reg[6][5] (.CK (WClk), .D (Data_in[5]), .SI (\Mem[6]
       [5]), .SE (n_60), .Q (\Mem[6] [5]));
  SDFFQX1 \Mem_reg[6][6] (.CK (WClk), .D (Data_in[6]), .SI (\Mem[6]
       [6]), .SE (n_60), .Q (\Mem[6] [6]));
  SDFFQX1 \Mem_reg[6][7] (.CK (WClk), .D (Data_in[7]), .SI (\Mem[6]
       [7]), .SE (n_60), .Q (\Mem[6] [7]));
  SDFFQX1 \Mem_reg[7][0] (.CK (WClk), .D (Data_in[0]), .SI (\Mem[7]
       [0]), .SE (n_57), .Q (\Mem[7] [0]));
  SDFFQX1 \Mem_reg[7][1] (.CK (WClk), .D (Data_in[1]), .SI (\Mem[7]
       [1]), .SE (n_57), .Q (\Mem[7] [1]));
  SDFFQX1 \Mem_reg[7][2] (.CK (WClk), .D (Data_in[2]), .SI (\Mem[7]
       [2]), .SE (n_57), .Q (\Mem[7] [2]));
  SDFFQX1 \Mem_reg[7][3] (.CK (WClk), .D (Data_in[3]), .SI (\Mem[7]
       [3]), .SE (n_57), .Q (\Mem[7] [3]));
  SDFFQX1 \Mem_reg[7][4] (.CK (WClk), .D (Data_in[4]), .SI (\Mem[7]
       [4]), .SE (n_57), .Q (\Mem[7] [4]));
  SDFFQX1 \Mem_reg[7][5] (.CK (WClk), .D (Data_in[5]), .SI (\Mem[7]
       [5]), .SE (n_57), .Q (\Mem[7] [5]));
  SDFFQX1 \Mem_reg[7][6] (.CK (WClk), .D (Data_in[6]), .SI (\Mem[7]
       [6]), .SE (n_57), .Q (\Mem[7] [6]));
  SDFFQX1 \Mem_reg[7][7] (.CK (WClk), .D (Data_in[7]), .SI (\Mem[7]
       [7]), .SE (n_57), .Q (\Mem[7] [7]));
  SDFFQX1 \Mem_reg[8][0] (.CK (WClk), .D (Data_in[0]), .SI (\Mem[8]
       [0]), .SE (n_53), .Q (\Mem[8] [0]));
  SDFFQX1 \Mem_reg[8][1] (.CK (WClk), .D (Data_in[1]), .SI (\Mem[8]
       [1]), .SE (n_53), .Q (\Mem[8] [1]));
  SDFFQX1 \Mem_reg[8][2] (.CK (WClk), .D (Data_in[2]), .SI (\Mem[8]
       [2]), .SE (n_53), .Q (\Mem[8] [2]));
  SDFFQX1 \Mem_reg[8][3] (.CK (WClk), .D (Data_in[3]), .SI (\Mem[8]
       [3]), .SE (n_53), .Q (\Mem[8] [3]));
  SDFFQX1 \Mem_reg[8][4] (.CK (WClk), .D (Data_in[4]), .SI (\Mem[8]
       [4]), .SE (n_53), .Q (\Mem[8] [4]));
  SDFFQX1 \Mem_reg[8][5] (.CK (WClk), .D (Data_in[5]), .SI (\Mem[8]
       [5]), .SE (n_53), .Q (\Mem[8] [5]));
  SDFFQX1 \Mem_reg[8][6] (.CK (WClk), .D (Data_in[6]), .SI (\Mem[8]
       [6]), .SE (n_53), .Q (\Mem[8] [6]));
  SDFFQX1 \Mem_reg[8][7] (.CK (WClk), .D (Data_in[7]), .SI (\Mem[8]
       [7]), .SE (n_53), .Q (\Mem[8] [7]));
  SDFFQX1 \Mem_reg[9][0] (.CK (WClk), .D (\Mem[9] [0]), .SI
       (Data_in[0]), .SE (n_58), .Q (\Mem[9] [0]));
  SDFFQX1 \Mem_reg[9][1] (.CK (WClk), .D (\Mem[9] [1]), .SI
       (Data_in[1]), .SE (n_58), .Q (\Mem[9] [1]));
  SDFFQX1 \Mem_reg[9][2] (.CK (WClk), .D (\Mem[9] [2]), .SI
       (Data_in[2]), .SE (n_58), .Q (\Mem[9] [2]));
  SDFFQX1 \Mem_reg[9][3] (.CK (WClk), .D (\Mem[9] [3]), .SI
       (Data_in[3]), .SE (n_58), .Q (\Mem[9] [3]));
  SDFFQX1 \Mem_reg[9][4] (.CK (WClk), .D (\Mem[9] [4]), .SI
       (Data_in[4]), .SE (n_58), .Q (\Mem[9] [4]));
  SDFFQX1 \Mem_reg[9][5] (.CK (WClk), .D (\Mem[9] [5]), .SI
       (Data_in[5]), .SE (n_58), .Q (\Mem[9] [5]));
  SDFFQX1 \Mem_reg[9][6] (.CK (WClk), .D (\Mem[9] [6]), .SI
       (Data_in[6]), .SE (n_58), .Q (\Mem[9] [6]));
  SDFFQX1 \Mem_reg[9][7] (.CK (WClk), .D (\Mem[9] [7]), .SI
       (Data_in[7]), .SE (n_58), .Q (\Mem[9] [7]));
  SDFFQX1 \Mem_reg[10][0] (.CK (WClk), .D (\Mem[10] [0]), .SI
       (Data_in[0]), .SE (n_62), .Q (\Mem[10] [0]));
  SDFFQX1 \Mem_reg[10][1] (.CK (WClk), .D (\Mem[10] [1]), .SI
       (Data_in[1]), .SE (n_62), .Q (\Mem[10] [1]));
  SDFFQX1 \Mem_reg[10][2] (.CK (WClk), .D (\Mem[10] [2]), .SI
       (Data_in[2]), .SE (n_62), .Q (\Mem[10] [2]));
  SDFFQX1 \Mem_reg[10][3] (.CK (WClk), .D (\Mem[10] [3]), .SI
       (Data_in[3]), .SE (n_62), .Q (\Mem[10] [3]));
  SDFFQX1 \Mem_reg[10][4] (.CK (WClk), .D (\Mem[10] [4]), .SI
       (Data_in[4]), .SE (n_62), .Q (\Mem[10] [4]));
  SDFFQX1 \Mem_reg[10][5] (.CK (WClk), .D (\Mem[10] [5]), .SI
       (Data_in[5]), .SE (n_62), .Q (\Mem[10] [5]));
  SDFFQX1 \Mem_reg[10][6] (.CK (WClk), .D (\Mem[10] [6]), .SI
       (Data_in[6]), .SE (n_62), .Q (\Mem[10] [6]));
  SDFFQX1 \Mem_reg[10][7] (.CK (WClk), .D (\Mem[10] [7]), .SI
       (Data_in[7]), .SE (n_62), .Q (\Mem[10] [7]));
  SDFFQX1 \Mem_reg[11][0] (.CK (WClk), .D (\Mem[11] [0]), .SI
       (Data_in[0]), .SE (n_2), .Q (\Mem[11] [0]));
  SDFFQX1 \Mem_reg[11][1] (.CK (WClk), .D (\Mem[11] [1]), .SI
       (Data_in[1]), .SE (n_2), .Q (\Mem[11] [1]));
  SDFFQX1 \Mem_reg[11][2] (.CK (WClk), .D (\Mem[11] [2]), .SI
       (Data_in[2]), .SE (n_2), .Q (\Mem[11] [2]));
  SDFFQX1 \Mem_reg[11][3] (.CK (WClk), .D (\Mem[11] [3]), .SI
       (Data_in[3]), .SE (n_2), .Q (\Mem[11] [3]));
  SDFFQX1 \Mem_reg[11][4] (.CK (WClk), .D (\Mem[11] [4]), .SI
       (Data_in[4]), .SE (n_2), .Q (\Mem[11] [4]));
  SDFFQX1 \Mem_reg[11][5] (.CK (WClk), .D (\Mem[11] [5]), .SI
       (Data_in[5]), .SE (n_2), .Q (\Mem[11] [5]));
  SDFFQX1 \Mem_reg[11][6] (.CK (WClk), .D (\Mem[11] [6]), .SI
       (Data_in[6]), .SE (n_2), .Q (\Mem[11] [6]));
  SDFFQX1 \Mem_reg[11][7] (.CK (WClk), .D (\Mem[11] [7]), .SI
       (Data_in[7]), .SE (n_2), .Q (\Mem[11] [7]));
  SDFFQX1 \Mem_reg[12][0] (.CK (WClk), .D (Data_in[0]), .SI
       (\Mem[12] [0]), .SE (n_66), .Q (\Mem[12] [0]));
  SDFFQX1 \Mem_reg[12][1] (.CK (WClk), .D (Data_in[1]), .SI
       (\Mem[12] [1]), .SE (n_66), .Q (\Mem[12] [1]));
  SDFFQX1 \Mem_reg[12][2] (.CK (WClk), .D (Data_in[2]), .SI
       (\Mem[12] [2]), .SE (n_66), .Q (\Mem[12] [2]));
  SDFFQX1 \Mem_reg[12][3] (.CK (WClk), .D (Data_in[3]), .SI
       (\Mem[12] [3]), .SE (n_66), .Q (\Mem[12] [3]));
  SDFFQX1 \Mem_reg[12][4] (.CK (WClk), .D (Data_in[4]), .SI
       (\Mem[12] [4]), .SE (n_66), .Q (\Mem[12] [4]));
  SDFFQX1 \Mem_reg[12][5] (.CK (WClk), .D (Data_in[5]), .SI
       (\Mem[12] [5]), .SE (n_66), .Q (\Mem[12] [5]));
  SDFFQX1 \Mem_reg[12][6] (.CK (WClk), .D (Data_in[6]), .SI
       (\Mem[12] [6]), .SE (n_66), .Q (\Mem[12] [6]));
  SDFFQX1 \Mem_reg[12][7] (.CK (WClk), .D (Data_in[7]), .SI
       (\Mem[12] [7]), .SE (n_66), .Q (\Mem[12] [7]));
  SDFFQX1 \Mem_reg[13][0] (.CK (WClk), .D (Data_in[0]), .SI
       (\Mem[13] [0]), .SE (n_56), .Q (\Mem[13] [0]));
  SDFFQX1 \Mem_reg[13][1] (.CK (WClk), .D (Data_in[1]), .SI
       (\Mem[13] [1]), .SE (n_56), .Q (\Mem[13] [1]));
  SDFFQX1 \Mem_reg[13][2] (.CK (WClk), .D (Data_in[2]), .SI
       (\Mem[13] [2]), .SE (n_56), .Q (\Mem[13] [2]));
  SDFFQX1 \Mem_reg[13][3] (.CK (WClk), .D (Data_in[3]), .SI
       (\Mem[13] [3]), .SE (n_56), .Q (\Mem[13] [3]));
  SDFFQX1 \Mem_reg[13][4] (.CK (WClk), .D (Data_in[4]), .SI
       (\Mem[13] [4]), .SE (n_56), .Q (\Mem[13] [4]));
  SDFFQX1 \Mem_reg[13][5] (.CK (WClk), .D (Data_in[5]), .SI
       (\Mem[13] [5]), .SE (n_56), .Q (\Mem[13] [5]));
  SDFFQX1 \Mem_reg[13][6] (.CK (WClk), .D (Data_in[6]), .SI
       (\Mem[13] [6]), .SE (n_56), .Q (\Mem[13] [6]));
  SDFFQX1 \Mem_reg[13][7] (.CK (WClk), .D (Data_in[7]), .SI
       (\Mem[13] [7]), .SE (n_56), .Q (\Mem[13] [7]));
  SDFFQX1 \Mem_reg[14][0] (.CK (WClk), .D (Data_in[0]), .SI
       (\Mem[14] [0]), .SE (n_63), .Q (\Mem[14] [0]));
  SDFFQX1 \Mem_reg[14][1] (.CK (WClk), .D (Data_in[1]), .SI
       (\Mem[14] [1]), .SE (n_63), .Q (\Mem[14] [1]));
  SDFFQX1 \Mem_reg[14][2] (.CK (WClk), .D (Data_in[2]), .SI
       (\Mem[14] [2]), .SE (n_63), .Q (\Mem[14] [2]));
  SDFFQX1 \Mem_reg[14][3] (.CK (WClk), .D (Data_in[3]), .SI
       (\Mem[14] [3]), .SE (n_63), .Q (\Mem[14] [3]));
  SDFFQX1 \Mem_reg[14][4] (.CK (WClk), .D (Data_in[4]), .SI
       (\Mem[14] [4]), .SE (n_63), .Q (\Mem[14] [4]));
  SDFFQX1 \Mem_reg[14][5] (.CK (WClk), .D (Data_in[5]), .SI
       (\Mem[14] [5]), .SE (n_63), .Q (\Mem[14] [5]));
  SDFFQX1 \Mem_reg[14][6] (.CK (WClk), .D (Data_in[6]), .SI
       (\Mem[14] [6]), .SE (n_63), .Q (\Mem[14] [6]));
  SDFFQX1 \Mem_reg[14][7] (.CK (WClk), .D (Data_in[7]), .SI
       (\Mem[14] [7]), .SE (n_63), .Q (\Mem[14] [7]));
  SDFFQX1 \Mem_reg[15][0] (.CK (WClk), .D (\Mem[15] [0]), .SI
       (Data_in[0]), .SE (n_3), .Q (\Mem[15] [0]));
  SDFFQX1 \Mem_reg[15][1] (.CK (WClk), .D (\Mem[15] [1]), .SI
       (Data_in[1]), .SE (n_3), .Q (\Mem[15] [1]));
  SDFFQX1 \Mem_reg[15][2] (.CK (WClk), .D (\Mem[15] [2]), .SI
       (Data_in[2]), .SE (n_3), .Q (\Mem[15] [2]));
  SDFFQX1 \Mem_reg[15][3] (.CK (WClk), .D (\Mem[15] [3]), .SI
       (Data_in[3]), .SE (n_3), .Q (\Mem[15] [3]));
  SDFFQX1 \Mem_reg[15][4] (.CK (WClk), .D (\Mem[15] [4]), .SI
       (Data_in[4]), .SE (n_3), .Q (\Mem[15] [4]));
  SDFFQX1 \Mem_reg[15][5] (.CK (WClk), .D (\Mem[15] [5]), .SI
       (Data_in[5]), .SE (n_3), .Q (\Mem[15] [5]));
  SDFFQX1 \Mem_reg[15][6] (.CK (WClk), .D (\Mem[15] [6]), .SI
       (Data_in[6]), .SE (n_3), .Q (\Mem[15] [6]));
  SDFFQX1 \Mem_reg[15][7] (.CK (WClk), .D (\Mem[15] [7]), .SI
       (Data_in[7]), .SE (n_3), .Q (\Mem[15] [7]));
  OR2XL g6403__1617(.A (n_141), .B (n_147), .Y (n_158));
  OR2XL g6404__2802(.A (n_139), .B (n_145), .Y (n_157));
  OR2XL g6405__1705(.A (n_138), .B (n_149), .Y (n_156));
  OR2XL g6406__5122(.A (n_142), .B (n_144), .Y (n_155));
  OR2XL g6407__8246(.A (n_137), .B (n_146), .Y (n_154));
  OR2XL g6408__7098(.A (n_136), .B (n_143), .Y (n_153));
  OR2XL g6409__6131(.A (n_140), .B (n_150), .Y (n_152));
  OR2XL g6410__1881(.A (n_135), .B (n_148), .Y (n_151));
  NAND4XL g6411__5115(.A (n_71), .B (n_80), .C (n_98), .D (n_124), .Y
       (n_150));
  NAND4XL g6412__7482(.A (n_109), .B (n_110), .C (n_111), .D (n_130),
       .Y (n_149));
  NAND4XL g6413__4733(.A (n_104), .B (n_108), .C (n_113), .D (n_129),
       .Y (n_148));
  NAND4XL g6414__6161(.A (n_81), .B (n_99), .C (n_100), .D (n_126), .Y
       (n_147));
  NAND4XL g6415__9315(.A (n_73), .B (n_70), .C (n_117), .D (n_125), .Y
       (n_146));
  NAND4XL g6416__9945(.A (n_68), .B (n_95), .C (n_85), .D (n_128), .Y
       (n_145));
  NAND4XL g6417__2883(.A (n_82), .B (n_83), .C (n_84), .D (n_127), .Y
       (n_144));
  NAND4XL g6418__2346(.A (n_123), .B (n_67), .C (n_107), .D (n_133), .Y
       (n_143));
  NAND4XL g6488__1666(.A (n_86), .B (n_88), .C (n_89), .D (n_90), .Y
       (n_142));
  NAND4XL g6489__7410(.A (n_101), .B (n_102), .C (n_103), .D (n_105),
       .Y (n_141));
  NAND4XL g6490__6417(.A (n_112), .B (n_120), .C (n_87), .D (n_91), .Y
       (n_140));
  NAND4XL g6491__5477(.A (n_106), .B (n_92), .C (n_94), .D (n_97), .Y
       (n_139));
  NAND4XL g6492__2398(.A (n_114), .B (n_115), .C (n_118), .D (n_119),
       .Y (n_138));
  NAND4XL g6493__5107(.A (n_76), .B (n_77), .C (n_79), .D (n_72), .Y
       (n_137));
  NAND4XL g6494__6260(.A (n_93), .B (n_78), .C (n_74), .D (n_75), .Y
       (n_136));
  NAND4XL g6495__4319(.A (n_116), .B (n_121), .C (n_122), .D (n_69), .Y
       (n_135));
  INVX1 g6557(.A (n_132), .Y (n_134));
  AOI222X1 g6558__8428(.A0 (Data_out[3]), .A1 (n_182), .B0 (\Mem[0]
       [3]), .B1 (n_43), .C0 (\Mem[8] [3]), .C1 (n_0), .Y (n_133));
  AOI31X1 g6559__5526(.A0 (n_22), .A1 (n_20), .A2 (n_50), .B0
       (Clear_in), .Y (n_132));
  NOR2X1 g6560__6783(.A (n_51), .B (n_96), .Y (n_131));
  AOI222X1 g6561__3680(.A0 (Data_out[4]), .A1 (n_182), .B0 (\Mem[0]
       [4]), .B1 (n_43), .C0 (\Mem[8] [4]), .C1 (n_0), .Y (n_130));
  AOI222X1 g6562__1617(.A0 (Data_out[1]), .A1 (n_182), .B0 (\Mem[0]
       [1]), .B1 (n_43), .C0 (\Mem[8] [1]), .C1 (n_0), .Y (n_129));
  AOI222X1 g6563__2802(.A0 (Data_out[2]), .A1 (n_182), .B0 (\Mem[0]
       [2]), .B1 (n_43), .C0 (\Mem[8] [2]), .C1 (n_0), .Y (n_128));
  AOI222X1 g6564__1705(.A0 (Data_out[6]), .A1 (n_182), .B0 (\Mem[0]
       [6]), .B1 (n_43), .C0 (\Mem[8] [6]), .C1 (n_0), .Y (n_127));
  AOI222X1 g6565__5122(.A0 (Data_out[5]), .A1 (n_182), .B0 (\Mem[0]
       [5]), .B1 (n_43), .C0 (\Mem[8] [5]), .C1 (n_0), .Y (n_126));
  AOI222X1 g6566__8246(.A0 (Data_out[7]), .A1 (n_182), .B0 (\Mem[0]
       [7]), .B1 (n_43), .C0 (\Mem[8] [7]), .C1 (n_0), .Y (n_125));
  AOI222X1 g6567__7098(.A0 (Data_out[0]), .A1 (n_182), .B0 (\Mem[0]
       [0]), .B1 (n_43), .C0 (\Mem[8] [0]), .C1 (n_0), .Y (n_124));
  AOI22XL g6568__6131(.A0 (\Mem[7] [3]), .A1 (n_45), .B0 (\Mem[15]
       [3]), .B1 (n_38), .Y (n_123));
  AOI22XL g6569__1881(.A0 (\Mem[4] [1]), .A1 (n_42), .B0 (\Mem[12]
       [1]), .B1 (n_34), .Y (n_122));
  AOI22XL g6570__5115(.A0 (\Mem[2] [1]), .A1 (n_47), .B0 (\Mem[10]
       [1]), .B1 (n_32), .Y (n_121));
  AOI22XL g6571__7482(.A0 (\Mem[2] [0]), .A1 (n_47), .B0 (\Mem[10]
       [0]), .B1 (n_32), .Y (n_120));
  AOI22X1 g6572__4733(.A0 (\Mem[3] [4]), .A1 (n_35), .B0 (\Mem[11]
       [4]), .B1 (n_46), .Y (n_119));
  AOI22XL g6573__6161(.A0 (\Mem[4] [4]), .A1 (n_42), .B0 (\Mem[12]
       [4]), .B1 (n_34), .Y (n_118));
  AOI22XL g6574__9315(.A0 (\Mem[6] [7]), .A1 (n_33), .B0 (\Mem[14]
       [7]), .B1 (n_44), .Y (n_117));
  AOI22XL g6575__9945(.A0 (\Mem[1] [1]), .A1 (n_41), .B0 (\Mem[9] [1]),
       .B1 (n_40), .Y (n_116));
  AOI22XL g6576__2883(.A0 (\Mem[2] [4]), .A1 (n_47), .B0 (\Mem[10]
       [4]), .B1 (n_32), .Y (n_115));
  AOI22XL g6577__2346(.A0 (\Mem[1] [4]), .A1 (n_41), .B0 (\Mem[9] [4]),
       .B1 (n_40), .Y (n_114));
  AOI22XL g6578__1666(.A0 (\Mem[6] [1]), .A1 (n_33), .B0 (\Mem[14]
       [1]), .B1 (n_44), .Y (n_113));
  AOI22XL g6579__7410(.A0 (\Mem[1] [0]), .A1 (n_41), .B0 (\Mem[9] [0]),
       .B1 (n_40), .Y (n_112));
  AOI22XL g6580__6417(.A0 (\Mem[6] [4]), .A1 (n_33), .B0 (\Mem[14]
       [4]), .B1 (n_44), .Y (n_111));
  AOI22XL g6581__5477(.A0 (\Mem[5] [4]), .A1 (n_36), .B0 (\Mem[13]
       [4]), .B1 (n_37), .Y (n_110));
  AOI22XL g6582__2398(.A0 (\Mem[7] [4]), .A1 (n_45), .B0 (\Mem[15]
       [4]), .B1 (n_38), .Y (n_109));
  AOI22XL g6583__5107(.A0 (\Mem[5] [1]), .A1 (n_36), .B0 (\Mem[13]
       [1]), .B1 (n_37), .Y (n_108));
  AOI22XL g6584__6260(.A0 (\Mem[6] [3]), .A1 (n_33), .B0 (\Mem[14]
       [3]), .B1 (n_44), .Y (n_107));
  AOI22XL g6585__4319(.A0 (\Mem[1] [2]), .A1 (n_41), .B0 (\Mem[9] [2]),
       .B1 (n_40), .Y (n_106));
  AOI22X1 g6586__8428(.A0 (\Mem[3] [5]), .A1 (n_35), .B0 (\Mem[11]
       [5]), .B1 (n_46), .Y (n_105));
  AOI22XL g6587__5526(.A0 (\Mem[7] [1]), .A1 (n_45), .B0 (\Mem[15]
       [1]), .B1 (n_38), .Y (n_104));
  AOI22XL g6588__6783(.A0 (\Mem[4] [5]), .A1 (n_42), .B0 (\Mem[12]
       [5]), .B1 (n_34), .Y (n_103));
  AOI22XL g6589__3680(.A0 (\Mem[2] [5]), .A1 (n_47), .B0 (\Mem[10]
       [5]), .B1 (n_32), .Y (n_102));
  AOI22XL g6590__1617(.A0 (\Mem[1] [5]), .A1 (n_41), .B0 (\Mem[9] [5]),
       .B1 (n_40), .Y (n_101));
  AOI22XL g6591__2802(.A0 (\Mem[6] [5]), .A1 (n_33), .B0 (\Mem[14]
       [5]), .B1 (n_44), .Y (n_100));
  AOI22XL g6592__1705(.A0 (\Mem[5] [5]), .A1 (n_36), .B0 (\Mem[13]
       [5]), .B1 (n_37), .Y (n_99));
  AOI22XL g6593__5122(.A0 (\Mem[6] [0]), .A1 (n_33), .B0 (\Mem[14]
       [0]), .B1 (n_44), .Y (n_98));
  AOI22X1 g6594__8246(.A0 (\Mem[3] [2]), .A1 (n_35), .B0 (\Mem[11]
       [2]), .B1 (n_46), .Y (n_97));
  OAI221X1 g6595__7098(.A0 (Next_Read_addr_2[1]), .A1 (n_7), .B0
       (Next_Read_addr_2[0]), .B1 (n_8), .C0 (n_52), .Y (n_96));
  AOI22XL g6596__6131(.A0 (\Mem[5] [2]), .A1 (n_36), .B0 (\Mem[13]
       [2]), .B1 (n_37), .Y (n_95));
  AOI22XL g6597__1881(.A0 (\Mem[4] [2]), .A1 (n_42), .B0 (\Mem[12]
       [2]), .B1 (n_34), .Y (n_94));
  AOI22XL g6598__5115(.A0 (\Mem[1] [3]), .A1 (n_41), .B0 (\Mem[9] [3]),
       .B1 (n_40), .Y (n_93));
  AOI22XL g6599__7482(.A0 (\Mem[2] [2]), .A1 (n_47), .B0 (\Mem[10]
       [2]), .B1 (n_32), .Y (n_92));
  AOI22X1 g6600__4733(.A0 (\Mem[3] [0]), .A1 (n_35), .B0 (\Mem[11]
       [0]), .B1 (n_46), .Y (n_91));
  AOI22X1 g6601__6161(.A0 (\Mem[3] [6]), .A1 (n_35), .B0 (\Mem[11]
       [6]), .B1 (n_46), .Y (n_90));
  AOI22XL g6602__9315(.A0 (\Mem[4] [6]), .A1 (n_42), .B0 (\Mem[12]
       [6]), .B1 (n_34), .Y (n_89));
  AOI22XL g6603__9945(.A0 (\Mem[2] [6]), .A1 (n_47), .B0 (\Mem[10]
       [6]), .B1 (n_32), .Y (n_88));
  AOI22XL g6604__2883(.A0 (\Mem[4] [0]), .A1 (n_42), .B0 (\Mem[12]
       [0]), .B1 (n_34), .Y (n_87));
  AOI22XL g6605__2346(.A0 (\Mem[1] [6]), .A1 (n_41), .B0 (\Mem[9] [6]),
       .B1 (n_40), .Y (n_86));
  AOI22XL g6606__1666(.A0 (\Mem[6] [2]), .A1 (n_33), .B0 (\Mem[14]
       [2]), .B1 (n_44), .Y (n_85));
  AOI22XL g6607__7410(.A0 (\Mem[6] [6]), .A1 (n_33), .B0 (\Mem[14]
       [6]), .B1 (n_44), .Y (n_84));
  AOI22XL g6608__6417(.A0 (\Mem[5] [6]), .A1 (n_36), .B0 (\Mem[13]
       [6]), .B1 (n_37), .Y (n_83));
  AOI22XL g6609__5477(.A0 (\Mem[7] [6]), .A1 (n_45), .B0 (\Mem[15]
       [6]), .B1 (n_38), .Y (n_82));
  AOI22XL g6610__2398(.A0 (\Mem[7] [5]), .A1 (n_45), .B0 (\Mem[15]
       [5]), .B1 (n_38), .Y (n_81));
  AOI22XL g6611__5107(.A0 (\Mem[5] [0]), .A1 (n_36), .B0 (\Mem[13]
       [0]), .B1 (n_37), .Y (n_80));
  AOI22XL g6612__6260(.A0 (\Mem[4] [7]), .A1 (n_42), .B0 (\Mem[12]
       [7]), .B1 (n_34), .Y (n_79));
  AOI22XL g6613__4319(.A0 (\Mem[2] [3]), .A1 (n_47), .B0 (\Mem[10]
       [3]), .B1 (n_32), .Y (n_78));
  AOI22XL g6614__8428(.A0 (\Mem[2] [7]), .A1 (n_47), .B0 (\Mem[10]
       [7]), .B1 (n_32), .Y (n_77));
  AOI22XL g6615__5526(.A0 (\Mem[1] [7]), .A1 (n_41), .B0 (\Mem[9] [7]),
       .B1 (n_40), .Y (n_76));
  AOI22X1 g6616__6783(.A0 (\Mem[3] [3]), .A1 (n_35), .B0 (\Mem[11]
       [3]), .B1 (n_46), .Y (n_75));
  AOI22XL g6617__3680(.A0 (\Mem[4] [3]), .A1 (n_42), .B0 (\Mem[12]
       [3]), .B1 (n_34), .Y (n_74));
  AOI22XL g6618__1617(.A0 (\Mem[7] [7]), .A1 (n_45), .B0 (\Mem[15]
       [7]), .B1 (n_38), .Y (n_73));
  AOI22X1 g6619__2802(.A0 (\Mem[3] [7]), .A1 (n_35), .B0 (\Mem[11]
       [7]), .B1 (n_46), .Y (n_72));
  AOI22XL g6620__1705(.A0 (\Mem[7] [0]), .A1 (n_45), .B0 (\Mem[15]
       [0]), .B1 (n_38), .Y (n_71));
  AOI22XL g6621__5122(.A0 (\Mem[5] [7]), .A1 (n_36), .B0 (\Mem[13]
       [7]), .B1 (n_37), .Y (n_70));
  AOI22X1 g6622__8246(.A0 (\Mem[3] [1]), .A1 (n_35), .B0 (\Mem[11]
       [1]), .B1 (n_46), .Y (n_69));
  AOI22XL g6623__7098(.A0 (\Mem[7] [2]), .A1 (n_45), .B0 (\Mem[15]
       [2]), .B1 (n_38), .Y (n_68));
  AOI22XL g6624__6131(.A0 (\Mem[5] [3]), .A1 (n_36), .B0 (\Mem[13]
       [3]), .B1 (n_37), .Y (n_67));
  NAND2X1 g6625__1881(.A (n_11), .B (n_49), .Y (n_66));
  NAND2X1 g6626__5115(.A (n_16), .B (n_1), .Y (n_65));
  NAND2X1 g6628__7482(.A (n_16), .B (n_48), .Y (n_64));
  NAND2BX1 g6629__4733(.AN (n_12), .B (n_49), .Y (n_63));
  NOR2X1 g6630__6161(.A (n_12), .B (n_39), .Y (n_62));
  NAND2X1 g6631__9315(.A (n_16), .B (n_49), .Y (n_61));
  NAND2X1 g6632__9945(.A (n_10), .B (n_49), .Y (n_60));
  AOI211XL g6634__2883(.A0 (Next_Read_addr_2[1]), .A1 (n_7), .B0
       (Clear_in), .C0 (n_21), .Y (n_52));
  OAI221X1 g6635__2346(.A0 (Next_Read_addr_2[3]), .A1
       (pNextWordToWrite[3]), .B0 (n_4), .B1 (pNextWordToWrite[2]), .C0
       (n_30), .Y (n_51));
  AOI221X1 g6636__1666(.A0 (n_9), .A1 (pNextWordToRead[2]), .B0
       (Next_Write_addr_2[0]), .B1 (n_5), .C0 (n_31), .Y (n_50));
  AND2X1 g6637__7410(.A (n_1), .B (n_10), .Y (n_59));
  AND2X1 g6638__6417(.A (n_1), .B (n_11), .Y (n_58));
  NAND2X1 g6639__5477(.A (n_10), .B (n_48), .Y (n_57));
  NAND2X1 g6640__2398(.A (n_11), .B (n_48), .Y (n_56));
  NAND2BX1 g6641__5107(.AN (n_39), .B (n_16), .Y (n_55));
  NAND2BX1 g6642__6260(.AN (n_39), .B (n_10), .Y (n_54));
  NAND2BX1 g6643__4319(.AN (n_39), .B (n_11), .Y (n_53));
  NOR2X1 g6645__8428(.A (pNextWordToWrite[0]), .B (n_28), .Y (n_49));
  NOR2X1 g6646__5526(.A (n_8), .B (n_28), .Y (n_48));
  NOR2BX1 g6647__6783(.AN (n_17), .B (n_25), .Y (n_47));
  NOR2X1 g6648__3680(.A (n_18), .B (n_25), .Y (n_46));
  NOR2X1 g6649__1617(.A (n_15), .B (n_27), .Y (n_45));
  NOR2X1 g6650__2802(.A (n_13), .B (n_27), .Y (n_44));
  AND2X1 g6651__1705(.A (n_26), .B (n_17), .Y (n_43));
  NOR2BX1 g6652__5122(.AN (n_17), .B (n_24), .Y (n_42));
  AND2X1 g6653__8246(.A (n_26), .B (n_14), .Y (n_41));
  NOR2BX1 g6655__7098(.AN (n_26), .B (n_18), .Y (n_40));
  OAI221X1 g6657__6131(.A0 (Next_Write_addr_2[0]), .A1 (n_5), .B0
       (n_9), .B1 (pNextWordToRead[2]), .C0 (n_23), .Y (n_31));
  AOI222X1 g6658__1881(.A0 (n_4), .A1 (pNextWordToWrite[2]), .B0
       (Next_Read_addr_2[3]), .B1 (pNextWordToWrite[3]), .C0
       (Next_Read_addr_2[0]), .C1 (n_8), .Y (n_30));
  NAND2X1 g6659__5115(.A (n_8), .B (n_29), .Y (n_39));
  NOR2X1 g6661__7482(.A (n_18), .B (n_27), .Y (n_38));
  NOR2X1 g6662__4733(.A (n_18), .B (n_24), .Y (n_37));
  NOR2X1 g6663__6161(.A (n_15), .B (n_24), .Y (n_36));
  NOR2X1 g6664__9315(.A (n_15), .B (n_25), .Y (n_35));
  NOR2X1 g6665__9945(.A (n_13), .B (n_24), .Y (n_34));
  NOR2BX1 g6666__2883(.AN (n_17), .B (n_27), .Y (n_33));
  NOR2X1 g6667__2346(.A (n_13), .B (n_25), .Y (n_32));
  NOR2BX1 g6669__1666(.AN (n_19), .B (pNextWordToWrite[2]), .Y (n_29));
  NAND2X1 g6670__7410(.A (pNextWordToWrite[2]), .B (n_19), .Y (n_28));
  NAND3BXL g6671__6417(.AN (n_196), .B (pNextWordToRead[1]), .C
       (pNextWordToRead[2]), .Y (n_27));
  NOR3X1 g6672__5477(.A (pNextWordToRead[1]), .B (pNextWordToRead[2]),
       .C (n_182), .Y (n_26));
  OR3X1 g6673__2398(.A (pNextWordToRead[2]), .B (n_6), .C (n_196), .Y
       (n_25));
  XNOR2X1 g6674__5107(.A (Next_Write_addr_2[3]), .B
       (pNextWordToRead[3]), .Y (n_23));
  XNOR2X1 g6675__6260(.A (Next_Write_addr_2[4]), .B
       (pNextWordToRead[4]), .Y (n_22));
  XNOR2X1 g6676__4319(.A (Next_Read_addr_2[4]), .B
       (pNextWordToWrite[4]), .Y (n_21));
  MXI2XL g6677__8428(.A (pNextWordToRead[1]), .B (n_6), .S0
       (Next_Write_addr_2[1]), .Y (n_20));
  NAND3BXL g6678__5526(.AN (n_182), .B (pNextWordToRead[2]), .C (n_6),
       .Y (n_24));
  NOR2X1 g6679__6783(.A (pNextWordToWrite[4]), .B (n_181), .Y (n_19));
  NAND2X1 g6680__3680(.A (pNextWordToRead[0]), .B (pNextWordToRead[3]),
       .Y (n_18));
  NOR2X1 g6681__1617(.A (pNextWordToRead[0]), .B (pNextWordToRead[3]),
       .Y (n_17));
  NOR2X1 g6682__2802(.A (pNextWordToWrite[1]), .B
       (pNextWordToWrite[3]), .Y (n_16));
  INVX1 g6683(.A (n_14), .Y (n_15));
  NOR2X1 g6685__1705(.A (pNextWordToRead[3]), .B (n_5), .Y (n_14));
  NAND2X1 g6686__5122(.A (pNextWordToRead[3]), .B (n_5), .Y (n_13));
  NAND2X1 g6687__8246(.A (pNextWordToWrite[1]), .B
       (pNextWordToWrite[3]), .Y (n_12));
  NOR2BX1 g6688__7098(.AN (pNextWordToWrite[3]), .B
       (pNextWordToWrite[1]), .Y (n_11));
  NOR2X1 g6689__6131(.A (pNextWordToWrite[3]), .B (n_7), .Y (n_10));
  INVX1 g6690(.A (Next_Write_addr_2[2]), .Y (n_9));
  INVX1 g6691(.A (pNextWordToWrite[0]), .Y (n_8));
  INVX1 g6692(.A (pNextWordToWrite[1]), .Y (n_7));
  INVX1 g6693(.A (pNextWordToRead[1]), .Y (n_6));
  INVX1 g6694(.A (pNextWordToRead[0]), .Y (n_5));
  INVX1 g6695(.A (Next_Read_addr_2[2]), .Y (n_4));
  NOR2BX1 g2__1881(.AN (n_48), .B (n_12), .Y (n_3));
  NOR2BX1 g6696__5115(.AN (n_1), .B (n_12), .Y (n_2));
  NOR2BX1 g6697__7482(.AN (n_29), .B (n_8), .Y (n_1));
  NOR2BX1 g6698__4733(.AN (n_26), .B (n_13), .Y (n_0));
  BUFX2 drc_bufs6704(.A (n_182), .Y (n_196));
endmodule

