
// Generated by Cadence Genus(TM) Synthesis Solution 25.12-s067_1
// Generated on: Aug  7 2026 21:41:36 -03 (Aug  8 2026 00:41:36 UTC)

// Verification Directory fv/x3_curto 

module x3_curto(XPower, X, clk);
  input [7:0] X;
  input clk;
  output [7:0] XPower;
  wire [7:0] X;
  wire clk;
  wire [7:0] XPower;
  wire [7:0] XPower2;
  wire [7:0] X1;
  wire [7:0] X2;
  wire UNCONNECTED, mul_20_24_n_0, mul_20_24_n_1, mul_20_24_n_2,
       mul_20_24_n_3, mul_20_24_n_4, mul_20_24_n_5, mul_20_24_n_6;
  wire mul_20_24_n_10, mul_20_24_n_12, mul_20_24_n_13, mul_20_24_n_14,
       mul_20_24_n_15, mul_20_24_n_16, mul_20_24_n_17, mul_20_24_n_18;
  wire mul_20_24_n_19, mul_20_24_n_20, mul_20_24_n_21, mul_20_24_n_23,
       mul_20_24_n_24, mul_20_24_n_25, mul_20_24_n_26, mul_20_24_n_27;
  wire mul_20_24_n_28, mul_20_24_n_29, mul_20_24_n_31, mul_20_24_n_32,
       mul_20_24_n_33, mul_20_24_n_34, mul_20_24_n_36, mul_20_24_n_37;
  wire mul_20_24_n_38, mul_20_24_n_40, mul_20_24_n_41, mul_20_24_n_42,
       mul_20_24_n_43, mul_20_24_n_44, mul_20_24_n_45, mul_20_24_n_46;
  wire mul_20_24_n_48, mul_20_24_n_49, mul_20_24_n_50, mul_20_24_n_51,
       mul_20_24_n_52, mul_20_24_n_53, mul_20_24_n_55, mul_20_24_n_56;
  wire mul_20_24_n_57, mul_20_24_n_58, mul_20_24_n_59, mul_20_24_n_60,
       mul_20_24_n_61, mul_20_24_n_62, mul_20_24_n_64, mul_20_24_n_66;
  wire mul_20_24_n_68, mul_20_24_n_69, mul_20_24_n_70, mul_20_24_n_71,
       mul_20_24_n_75, mul_20_24_n_76, mul_20_24_n_77, mul_20_24_n_78;
  wire mul_20_24_n_79, mul_20_24_n_80, mul_20_24_n_81, mul_20_24_n_82,
       mul_20_24_n_84, mul_20_24_n_86, mul_20_24_n_90, mul_20_24_n_91;
  wire mul_20_24_n_92, mul_20_24_n_93, mul_20_24_n_94, mul_20_24_n_95,
       mul_20_24_n_96, mul_20_24_n_97, mul_20_24_n_99, mul_20_24_n_100;
  wire mul_20_24_n_102, mul_20_24_n_103, mul_20_24_n_105,
       mul_20_24_n_108, mul_20_24_n_109, mul_20_24_n_111, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_136, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_148;
  wire n_149, n_151, n_156, n_157, n_162, n_164, n_166, n_167;
  DFFQXL \XPower2_reg[7] (.CK (clk), .D (n_47), .Q (XPower2[7]));
  DFFHQX1 \XPower2_reg[6] (.CK (clk), .D (n_48), .Q (XPower2[6]));
  NAND2X1 g1793__2398(.A (n_38), .B (n_46), .Y (n_48));
  XNOR2X1 g1794__5107(.A (n_36), .B (n_45), .Y (n_47));
  DFFHQX1 \XPower2_reg[5] (.CK (clk), .D (n_44), .Q (XPower2[5]));
  NOR2X1 g1796__6260(.A (n_43), .B (n_42), .Y (n_46));
  DFFHQX1 \XPower2_reg[4] (.CK (clk), .D (n_39), .Q (XPower2[4]));
  NOR2XL g1798__4319(.A (n_31), .B (n_37), .Y (n_45));
  NOR2X1 g1799__8428(.A (n_21), .B (n_40), .Y (n_44));
  NOR2X1 g1800__5526(.A (n_29), .B (n_41), .Y (n_43));
  OAI2BB1X1 g1801__6783(.A0N (n_8), .A1N (n_35), .B0 (n_28), .Y (n_42));
  DFFQX1 \XPower2_reg[3] (.CK (clk), .D (n_32), .Q (XPower2[3]));
  OR2XL g1803__3680(.A (n_35), .B (n_16), .Y (n_41));
  XOR2XL g1804__1617(.A (n_11), .B (n_23), .Y (n_40));
  OAI21X1 g1805__2802(.A0 (X1[0]), .A1 (n_3), .B0 (n_24), .Y (n_39));
  NOR2XL g1806__1705(.A (n_34), .B (n_30), .Y (n_38));
  NOR3X1 g1807__5122(.A (n_2), .B (n_25), .C (n_33), .Y (n_37));
  XNOR2X1 g1808__8246(.A (n_4), .B (n_27), .Y (n_36));
  AND2XL g1809__7098(.A (n_8), .B (n_29), .Y (n_34));
  NOR2BX1 g1810__6131(.AN (X1[5]), .B (n_26), .Y (n_33));
  NOR3XL g1811__1881(.A (X1[1]), .B (X1[4]), .C (n_1), .Y (n_35));
  NOR2XL g1812__5115(.A (n_0), .B (n_15), .Y (n_32));
  AOI21XL g1813__7482(.A0 (n_10), .A1 (n_19), .B0 (n_9), .Y (n_31));
  NOR3XL g1814__4733(.A (n_2), .B (X1[0]), .C (n_22), .Y (n_30));
  OR2XL g1815__6161(.A (X1[0]), .B (n_19), .Y (n_28));
  NOR2X1 g1816__9315(.A (n_1), .B (n_22), .Y (n_27));
  AOI2BB1X1 g1817__9945(.A0N (X1[2]), .A1N (n_5), .B0 (X1[3]), .Y
       (n_29));
  NOR2BX1 g1818__2883(.AN (n_10), .B (n_17), .Y (n_26));
  NOR3BX1 g1819__2346(.AN (n_10), .B (X1[5]), .C (n_18), .Y (n_25));
  NAND2X1 g1820__1666(.A (n_14), .B (n_20), .Y (n_24));
  OAI21X1 g1821__7410(.A0 (n_2), .A1 (n_13), .B0 (n_14), .Y (n_23));
  NOR2XL g1822__6417(.A (X1[0]), .B (n_14), .Y (n_21));
  NOR2X1 g1823__5477(.A (n_0), .B (n_13), .Y (n_20));
  DFFQX2 \XPower2_reg[2] (.CK (clk), .D (n_7), .Q (XPower2[2]));
  NAND2BX1 g1825__2398(.AN (n_12), .B (n_10), .Y (n_22));
  NOR2X1 g1826__5107(.A (n_1), .B (n_11), .Y (n_18));
  NOR2XL g1827__6260(.A (n_12), .B (n_0), .Y (n_17));
  NAND2XL g1828__4319(.A (X1[0]), .B (n_9), .Y (n_16));
  XNOR2X1 g1829__8428(.A (X1[1]), .B (X1[2]), .Y (n_15));
  NAND2X1 g1830__5526(.A (n_1), .B (n_6), .Y (n_19));
  DFFQXL \X2_reg[7] (.CK (clk), .D (X1[7]), .Q (X2[7]));
  DFFHQX1 \X2_reg[2] (.CK (clk), .D (X1[2]), .Q (X2[2]));
  DFFQX1 \X2_reg[4] (.CK (clk), .D (X1[4]), .Q (X2[4]));
  DFFQXL \X2_reg[6] (.CK (clk), .D (X1[6]), .Q (X2[6]));
  DFFQX1 \X2_reg[3] (.CK (clk), .D (X1[3]), .Q (X2[3]));
  DFFQXL \X2_reg[5] (.CK (clk), .D (X1[5]), .Q (X2[5]));
  DFFHQX4 \X2_reg[0] (.CK (clk), .D (X1[0]), .Q (X2[0]));
  NAND2X1 g1839__6783(.A (X1[3]), .B (X1[2]), .Y (n_14));
  INVXL g1840(.A (n_9), .Y (n_8));
  NOR2XL g1841__3680(.A (X1[0]), .B (n_2), .Y (n_7));
  NOR2BX1 g1842__1617(.AN (X1[3]), .B (X1[1]), .Y (n_6));
  NAND2XL g1843__2802(.A (X1[1]), .B (X1[4]), .Y (n_5));
  NOR2X1 g1844__1705(.A (X1[3]), .B (X1[2]), .Y (n_13));
  NAND2XL g1845__5122(.A (X1[6]), .B (X1[0]), .Y (n_4));
  NOR2X1 g1846__8246(.A (X1[3]), .B (X1[4]), .Y (n_12));
  NAND2X1 g1847__7098(.A (X1[2]), .B (n_2), .Y (n_3));
  NAND2X1 g1848__6131(.A (X1[0]), .B (X1[4]), .Y (n_11));
  NAND2X1 g1849__1881(.A (X1[3]), .B (X1[4]), .Y (n_10));
  NAND2X1 g1850__5115(.A (X1[5]), .B (X1[0]), .Y (n_9));
  INVX1 g1851(.A (X1[1]), .Y (n_2));
  INVX1 g1852(.A (X1[2]), .Y (n_1));
  DFFQXL \XPower_reg[5] (.CK (clk), .D (n_60), .Q (XPower[5]));
  DFFQXL \XPower_reg[1] (.CK (clk), .D (n_64), .Q (XPower[1]));
  DFFQXL \XPower_reg[6] (.CK (clk), .D (n_59), .Q (XPower[6]));
  DFFQXL \X1_reg[6] (.CK (clk), .D (X[6]), .Q (X1[6]));
  DFFQX2 \X1_reg[3] (.CK (clk), .D (X[3]), .Q (X1[3]));
  DFFHQX1 \X1_reg[1] (.CK (clk), .D (X[1]), .Q (X1[1]));
  INVX1 g1861(.A (X1[0]), .Y (n_0));
  DFFQXL \XPower_reg[2] (.CK (clk), .D (n_63), .Q (XPower[2]));
  DFFQXL \X1_reg[7] (.CK (clk), .D (X[7]), .Q (X1[7]));
  DFFQXL \XPower_reg[4] (.CK (clk), .D (n_61), .Q (XPower[4]));
  DFFHQX1 \XPower_reg[3] (.CK (clk), .D (n_62), .Q (XPower[3]));
  DFFQXL \XPower_reg[0] (.CK (clk), .D (n_148), .Q (XPower[0]));
  DFFHQX1 \X1_reg[5] (.CK (clk), .D (X[5]), .Q (X1[5]));
  DFFHQX1 \X1_reg[4] (.CK (clk), .D (X[4]), .Q (X1[4]));
  MXI2XL mul_20_24_g1520__7482(.A (n_136), .B (n_141), .S0
       (mul_20_24_n_111), .Y (n_58));
  OAI21X2 mul_20_24_g1521__4733(.A0 (mul_20_24_n_102), .A1
       (mul_20_24_n_105), .B0 (mul_20_24_n_103), .Y (mul_20_24_n_111));
  MXI2XL mul_20_24_g1522__6161(.A (mul_20_24_n_109), .B
       (mul_20_24_n_105), .S0 (mul_20_24_n_108), .Y (n_59));
  INVXL mul_20_24_g1523(.A (mul_20_24_n_105), .Y (mul_20_24_n_109));
  NAND2BX1 mul_20_24_g1524__9315(.AN (mul_20_24_n_102), .B
       (mul_20_24_n_103), .Y (mul_20_24_n_108));
  AOI21X2 mul_20_24_g1527__2883(.A0 (mul_20_24_n_99), .A1 (n_145), .B0
       (mul_20_24_n_95), .Y (mul_20_24_n_105));
  MXI2XL mul_20_24_g1528__2346(.A (mul_20_24_n_100), .B
       (mul_20_24_n_99), .S0 (mul_20_24_n_97), .Y (n_60));
  NAND2X1 mul_20_24_g1529__1666(.A (n_164), .B (mul_20_24_n_91), .Y
       (mul_20_24_n_103));
  NOR2X1 mul_20_24_g1530__7410(.A (n_164), .B (mul_20_24_n_91), .Y
       (mul_20_24_n_102));
  INVXL mul_20_24_g1532(.A (mul_20_24_n_99), .Y (mul_20_24_n_100));
  ADDFHXL mul_20_24_g1533__6417(.A (mul_20_24_n_2), .B
       (mul_20_24_n_86), .CI (n_167), .CO (mul_20_24_n_99), .S (n_61));
  NOR2BX1 mul_20_24_g1534__5477(.AN (mul_20_24_n_94), .B
       (mul_20_24_n_93), .Y (mul_20_24_n_97));
  MXI2X1 mul_20_24_g1535__2398(.A (n_140), .B (n_139), .S0
       (mul_20_24_n_90), .Y (mul_20_24_n_96));
  INVX1 mul_20_24_g1536(.A (mul_20_24_n_94), .Y (mul_20_24_n_95));
  NAND2X1 mul_20_24_g1537__5107(.A (mul_20_24_n_75), .B
       (mul_20_24_n_84), .Y (mul_20_24_n_94));
  INVXL mul_20_24_g1538(.A (n_146), .Y (mul_20_24_n_93));
  OAI21X1 mul_20_24_g1540__6260(.A0 (mul_20_24_n_81), .A1
       (mul_20_24_n_6), .B0 (mul_20_24_n_80), .Y (mul_20_24_n_92));
  XOR2XL mul_20_24_g1541__4319(.A (mul_20_24_n_6), .B (mul_20_24_n_82),
       .Y (mul_20_24_n_91));
  XOR2XL mul_20_24_g1543__8428(.A (mul_20_24_n_5), .B (n_142), .Y
       (mul_20_24_n_90));
  ADDFHXL mul_20_24_g1546__6783(.A (mul_20_24_n_19), .B
       (mul_20_24_n_49), .CI (mul_20_24_n_59), .CO (mul_20_24_n_86), .S
       (n_62));
  XNOR2X1 mul_20_24_g1548__1617(.A (mul_20_24_n_76), .B
       (mul_20_24_n_79), .Y (mul_20_24_n_84));
  MXI2X1 mul_20_24_g1551__1705(.A (mul_20_24_n_78), .B
       (mul_20_24_n_10), .S0 (mul_20_24_n_69), .Y (mul_20_24_n_82));
  NOR2X1 mul_20_24_g1552__5122(.A (mul_20_24_n_10), .B
       (mul_20_24_n_77), .Y (mul_20_24_n_81));
  NAND2X1 mul_20_24_g1553__8246(.A (mul_20_24_n_10), .B
       (mul_20_24_n_77), .Y (mul_20_24_n_80));
  INVX1 mul_20_24_g1556(.A (mul_20_24_n_10), .Y (mul_20_24_n_78));
  ADDFHXL mul_20_24_g1557__7098(.A (mul_20_24_n_28), .B
       (mul_20_24_n_14), .CI (mul_20_24_n_29), .CO (mul_20_24_n_10), .S
       (mul_20_24_n_79));
  INVX1 mul_20_24_g1558(.A (mul_20_24_n_69), .Y (mul_20_24_n_77));
  XOR2XL mul_20_24_g1559__6131(.A (mul_20_24_n_51), .B
       (mul_20_24_n_61), .Y (mul_20_24_n_76));
  OAI22X1 mul_20_24_g1560__1881(.A0 (mul_20_24_n_46), .A1 (n_166), .B0
       (mul_20_24_n_21), .B1 (mul_20_24_n_24), .Y (mul_20_24_n_75));
  NAND2BXL mul_20_24_g1564__6161(.AN (mul_20_24_n_51), .B
       (mul_20_24_n_61), .Y (mul_20_24_n_71));
  OAI21X1 mul_20_24_g1567__9315(.A0 (mul_20_24_n_1), .A1
       (mul_20_24_n_4), .B0 (mul_20_24_n_66), .Y (mul_20_24_n_70));
  MXI2X1 mul_20_24_g1568__9945(.A (n_156), .B (n_157), .S0
       (mul_20_24_n_58), .Y (mul_20_24_n_69));
  OAI21X1 mul_20_24_g1569__2883(.A0 (mul_20_24_n_37), .A1
       (mul_20_24_n_55), .B0 (mul_20_24_n_57), .Y (mul_20_24_n_68));
  NAND2BXL mul_20_24_g1572__2346(.AN (mul_20_24_n_23), .B
       (mul_20_24_n_50), .Y (mul_20_24_n_66));
  NOR2XL mul_20_24_g1573__1666(.A (mul_20_24_n_49), .B
       (mul_20_24_n_48), .Y (n_63));
  INVXL mul_20_24_g1577(.A (mul_20_24_n_61), .Y (mul_20_24_n_62));
  XNOR2XL mul_20_24_g1578__6417(.A (mul_20_24_n_17), .B
       (mul_20_24_n_31), .Y (mul_20_24_n_60));
  XOR2XL mul_20_24_g1579__5477(.A (mul_20_24_n_21), .B
       (mul_20_24_n_24), .Y (mul_20_24_n_64));
  MXI2X1 mul_20_24_g1580__2398(.A (mul_20_24_n_42), .B
       (mul_20_24_n_41), .S0 (mul_20_24_n_25), .Y (mul_20_24_n_59));
  NOR2BX1 mul_20_24_g1581__5107(.AN (mul_20_24_n_53), .B
       (mul_20_24_n_56), .Y (mul_20_24_n_58));
  MXI2X1 mul_20_24_g1583__4319(.A (mul_20_24_n_43), .B
       (mul_20_24_n_44), .S0 (mul_20_24_n_20), .Y (mul_20_24_n_61));
  NAND2X1 mul_20_24_g1584__8428(.A (mul_20_24_n_0), .B
       (mul_20_24_n_34), .Y (mul_20_24_n_57));
  NOR2XL mul_20_24_g1585__5526(.A (mul_20_24_n_37), .B
       (mul_20_24_n_34), .Y (mul_20_24_n_56));
  NOR2X1 mul_20_24_g1586__6783(.A (mul_20_24_n_0), .B (mul_20_24_n_34),
       .Y (mul_20_24_n_55));
  NAND2XL mul_20_24_g1588__1617(.A (mul_20_24_n_37), .B
       (mul_20_24_n_34), .Y (mul_20_24_n_53));
  OAI21XL mul_20_24_g1592__2802(.A0 (X2[2]), .A1 (XPower2[2]), .B0
       (n_148), .Y (mul_20_24_n_48));
  AND2XL mul_20_24_g1594__5122(.A (mul_20_24_n_21), .B
       (mul_20_24_n_24), .Y (mul_20_24_n_46));
  NOR2X1 mul_20_24_g1595__8246(.A (mul_20_24_n_32), .B
       (mul_20_24_n_36), .Y (mul_20_24_n_52));
  NOR2XL mul_20_24_g1596__7098(.A (mul_20_24_n_38), .B
       (mul_20_24_n_40), .Y (mul_20_24_n_51));
  NOR2X1 mul_20_24_g1597__6131(.A (mul_20_24_n_33), .B
       (mul_20_24_n_36), .Y (mul_20_24_n_50));
  NOR2X1 mul_20_24_g1598__1881(.A (n_149), .B (mul_20_24_n_21), .Y
       (mul_20_24_n_49));
  INVX1 mul_20_24_g1600(.A (mul_20_24_n_43), .Y (mul_20_24_n_44));
  INVX1 mul_20_24_g1601(.A (mul_20_24_n_42), .Y (mul_20_24_n_41));
  INVXL mul_20_24_g1603(.A (mul_20_24_n_36), .Y (n_64));
  NAND2X1 mul_20_24_g1604__5115(.A (XPower2[4]), .B (XPower2[5]), .Y
       (mul_20_24_n_33));
  NAND2X1 mul_20_24_g1605__7482(.A (XPower2[6]), .B (XPower2[5]), .Y
       (mul_20_24_n_32));
  NAND2X1 mul_20_24_g1606__4733(.A (X2[2]), .B (XPower2[5]), .Y
       (mul_20_24_n_31));
  NAND2XL mul_20_24_g1608__9315(.A (X2[3]), .B (XPower2[4]), .Y
       (mul_20_24_n_45));
  NAND2X1 mul_20_24_g1609__9945(.A (XPower2[4]), .B (X2[1]), .Y
       (mul_20_24_n_43));
  NAND2X1 mul_20_24_g1610__2883(.A (XPower2[2]), .B (X2[1]), .Y
       (mul_20_24_n_42));
  NOR2BX1 mul_20_24_g1611__2346(.AN (X2[2]), .B (mul_20_24_n_13), .Y
       (mul_20_24_n_29));
  NAND2X1 mul_20_24_g1612__1666(.A (XPower2[4]), .B (X2[0]), .Y
       (mul_20_24_n_40));
  NAND2X1 mul_20_24_g1613__7410(.A (X2[1]), .B (XPower2[3]), .Y
       (mul_20_24_n_38));
  NAND2X1 mul_20_24_g1614__6417(.A (X2[4]), .B (XPower2[2]), .Y
       (mul_20_24_n_37));
  NAND2X2 mul_20_24_g1615__5477(.A (X2[1]), .B (X2[0]), .Y
       (mul_20_24_n_36));
  NOR2X2 mul_20_24_g1616__2398(.A (mul_20_24_n_12), .B (n_151), .Y
       (mul_20_24_n_34));
  CLKAND2X2 mul_20_24_g1617__5107(.A (X2[3]), .B (XPower2[2]), .Y
       (mul_20_24_n_28));
  NAND2X1 mul_20_24_g1623__6260(.A (XPower2[5]), .B (X2[1]), .Y
       (mul_20_24_n_27));
  NAND2X1 mul_20_24_g1624__4319(.A (XPower2[5]), .B (X2[0]), .Y
       (mul_20_24_n_20));
  NAND2X1 mul_20_24_g1625__8428(.A (X2[5]), .B (XPower2[2]), .Y
       (mul_20_24_n_26));
  NOR2BX1 mul_20_24_g1626__5526(.AN (X2[3]), .B (n_149), .Y
       (mul_20_24_n_19));
  NAND2X1 mul_20_24_g1627__6783(.A (XPower2[6]), .B (X2[1]), .Y
       (mul_20_24_n_18));
  NAND2X1 mul_20_24_g1628__3680(.A (X2[4]), .B (XPower2[3]), .Y
       (mul_20_24_n_17));
  NAND2X1 mul_20_24_g1629__1617(.A (X2[7]), .B (X2[0]), .Y
       (mul_20_24_n_16));
  NAND2X1 mul_20_24_g1630__2802(.A (XPower2[6]), .B (X2[0]), .Y
       (mul_20_24_n_15));
  NOR2X1 mul_20_24_g1631__1705(.A (mul_20_24_n_13), .B (n_151), .Y
       (mul_20_24_n_25));
  NAND2X1 mul_20_24_g1632__5122(.A (X2[4]), .B (X2[0]), .Y
       (mul_20_24_n_24));
  NAND2X1 mul_20_24_g1633__8246(.A (X2[2]), .B (XPower2[4]), .Y
       (mul_20_24_n_23));
  CLKAND2X2 mul_20_24_g1634__7098(.A (X2[5]), .B (X2[0]), .Y
       (mul_20_24_n_14));
  NAND2X2 mul_20_24_g1636__6131(.A (X2[2]), .B (XPower2[2]), .Y
       (mul_20_24_n_21));
  INVX2 mul_20_24_g1638(.A (XPower2[3]), .Y (mul_20_24_n_13));
  INVX1 mul_20_24_g1639(.A (X2[6]), .Y (mul_20_24_n_12));
  XNOR3X1 mul_20_24_g1643__4733(.A (mul_20_24_n_23), .B
       (mul_20_24_n_50), .C (mul_20_24_n_4), .Y (mul_20_24_n_6));
  XNOR2X1 mul_20_24_g1644__6161(.A (mul_20_24_n_45), .B
       (mul_20_24_n_60), .Y (mul_20_24_n_5));
  XNOR2X1 mul_20_24_g1645__9315(.A (mul_20_24_n_27), .B
       (mul_20_24_n_15), .Y (mul_20_24_n_4));
  XNOR2X1 mul_20_24_g1646__9945(.A (mul_20_24_n_26), .B
       (mul_20_24_n_16), .Y (mul_20_24_n_3));
  NOR2BX1 mul_20_24_g1647__2883(.AN (mul_20_24_n_25), .B
       (mul_20_24_n_42), .Y (mul_20_24_n_2));
  NOR2BX1 mul_20_24_g1648__2346(.AN (mul_20_24_n_23), .B
       (mul_20_24_n_50), .Y (mul_20_24_n_1));
  NOR2BX1 mul_20_24_g1649__1666(.AN (X2[3]), .B (mul_20_24_n_13), .Y
       (mul_20_24_n_0));
  DFFQX2 \X2_reg[1] (.CK (clk), .D (X1[1]), .Q (X2[1]));
  DFFXL \XPower_reg[7] (.CK (clk), .D (n_58), .Q (XPower[7]), .QN
       (UNCONNECTED));
  DFFQX2 \X1_reg[2] (.CK (clk), .D (X[2]), .Q (X1[2]));
  DFFQX2 \X1_reg[0] (.CK (clk), .D (X[0]), .Q (X1[0]));
  XOR2XL g2(.A (mul_20_24_n_92), .B (mul_20_24_n_96), .Y (n_136));
  XNOR2XL g1886(.A (mul_20_24_n_70), .B (n_143), .Y (n_139));
  XOR2XL mul_20_24_g1545__1887(.A (mul_20_24_n_70), .B (n_144), .Y
       (n_140));
  XNOR2XL g1888(.A (mul_20_24_n_92), .B (mul_20_24_n_96), .Y (n_141));
  XOR3XL g1889(.A (mul_20_24_n_18), .B (n_162), .C (mul_20_24_n_68), .Y
       (n_142));
  XOR2XL mul_20_24_g1642__1890(.A (mul_20_24_n_52), .B (mul_20_24_n_3),
       .Y (n_143));
  XOR2XL mul_20_24_g1642__7482_0(.A (mul_20_24_n_52), .B
       (mul_20_24_n_3), .Y (n_144));
  OR2X1 mul_20_24_g2__1891(.A (mul_20_24_n_75), .B (mul_20_24_n_84), .Y
       (n_145));
  OR2XL mul_20_24_g2__1881_1(.A (mul_20_24_n_75), .B (mul_20_24_n_84),
       .Y (n_146));
  INVX1 fopt(.A (n_149), .Y (n_148));
  BUFX3 fopt1(.A (n_151), .Y (n_149));
  INVX3 fopt3(.A (X2[0]), .Y (n_151));
  INVX1 fopt1892(.A (n_157), .Y (n_156));
  BUFX2 fopt1893(.A (mul_20_24_n_0), .Y (n_157));
  NAND2BX1 g1909(.AN (n_151), .B (XPower2[7]), .Y (n_162));
  AO22XL g1911(.A0 (mul_20_24_n_51), .A1 (mul_20_24_n_62), .B0
       (mul_20_24_n_71), .B1 (mul_20_24_n_79), .Y (n_164));
  XNOR2X1 g1913(.A (mul_20_24_n_38), .B (mul_20_24_n_40), .Y (n_166));
  XNOR2X1 g1914(.A (mul_20_24_n_64), .B (n_166), .Y (n_167));
endmodule

