# ####################################################################

#  Created by Genus(TM) Synthesis Solution 25.12-s067_1 on Sat Jul 25 15:45:42 -03 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design mac_param

create_clock -name "clk" -period 0.64 -waveform {0.0 0.32} [get_ports clk]
set_load -pin_load 1.0 [get_ports busy]
set_load -pin_load 1.0 [get_ports done]
set_load -pin_load 1.0 [get_ports {result[73]}]
set_load -pin_load 1.0 [get_ports {result[72]}]
set_load -pin_load 1.0 [get_ports {result[71]}]
set_load -pin_load 1.0 [get_ports {result[70]}]
set_load -pin_load 1.0 [get_ports {result[69]}]
set_load -pin_load 1.0 [get_ports {result[68]}]
set_load -pin_load 1.0 [get_ports {result[67]}]
set_load -pin_load 1.0 [get_ports {result[66]}]
set_load -pin_load 1.0 [get_ports {result[65]}]
set_load -pin_load 1.0 [get_ports {result[64]}]
set_load -pin_load 1.0 [get_ports {result[63]}]
set_load -pin_load 1.0 [get_ports {result[62]}]
set_load -pin_load 1.0 [get_ports {result[61]}]
set_load -pin_load 1.0 [get_ports {result[60]}]
set_load -pin_load 1.0 [get_ports {result[59]}]
set_load -pin_load 1.0 [get_ports {result[58]}]
set_load -pin_load 1.0 [get_ports {result[57]}]
set_load -pin_load 1.0 [get_ports {result[56]}]
set_load -pin_load 1.0 [get_ports {result[55]}]
set_load -pin_load 1.0 [get_ports {result[54]}]
set_load -pin_load 1.0 [get_ports {result[53]}]
set_load -pin_load 1.0 [get_ports {result[52]}]
set_load -pin_load 1.0 [get_ports {result[51]}]
set_load -pin_load 1.0 [get_ports {result[50]}]
set_load -pin_load 1.0 [get_ports {result[49]}]
set_load -pin_load 1.0 [get_ports {result[48]}]
set_load -pin_load 1.0 [get_ports {result[47]}]
set_load -pin_load 1.0 [get_ports {result[46]}]
set_load -pin_load 1.0 [get_ports {result[45]}]
set_load -pin_load 1.0 [get_ports {result[44]}]
set_load -pin_load 1.0 [get_ports {result[43]}]
set_load -pin_load 1.0 [get_ports {result[42]}]
set_load -pin_load 1.0 [get_ports {result[41]}]
set_load -pin_load 1.0 [get_ports {result[40]}]
set_load -pin_load 1.0 [get_ports {result[39]}]
set_load -pin_load 1.0 [get_ports {result[38]}]
set_load -pin_load 1.0 [get_ports {result[37]}]
set_load -pin_load 1.0 [get_ports {result[36]}]
set_load -pin_load 1.0 [get_ports {result[35]}]
set_load -pin_load 1.0 [get_ports {result[34]}]
set_load -pin_load 1.0 [get_ports {result[33]}]
set_load -pin_load 1.0 [get_ports {result[32]}]
set_load -pin_load 1.0 [get_ports {result[31]}]
set_load -pin_load 1.0 [get_ports {result[30]}]
set_load -pin_load 1.0 [get_ports {result[29]}]
set_load -pin_load 1.0 [get_ports {result[28]}]
set_load -pin_load 1.0 [get_ports {result[27]}]
set_load -pin_load 1.0 [get_ports {result[26]}]
set_load -pin_load 1.0 [get_ports {result[25]}]
set_load -pin_load 1.0 [get_ports {result[24]}]
set_load -pin_load 1.0 [get_ports {result[23]}]
set_load -pin_load 1.0 [get_ports {result[22]}]
set_load -pin_load 1.0 [get_ports {result[21]}]
set_load -pin_load 1.0 [get_ports {result[20]}]
set_load -pin_load 1.0 [get_ports {result[19]}]
set_load -pin_load 1.0 [get_ports {result[18]}]
set_load -pin_load 1.0 [get_ports {result[17]}]
set_load -pin_load 1.0 [get_ports {result[16]}]
set_load -pin_load 1.0 [get_ports {result[15]}]
set_load -pin_load 1.0 [get_ports {result[14]}]
set_load -pin_load 1.0 [get_ports {result[13]}]
set_load -pin_load 1.0 [get_ports {result[12]}]
set_load -pin_load 1.0 [get_ports {result[11]}]
set_load -pin_load 1.0 [get_ports {result[10]}]
set_load -pin_load 1.0 [get_ports {result[9]}]
set_load -pin_load 1.0 [get_ports {result[8]}]
set_load -pin_load 1.0 [get_ports {result[7]}]
set_load -pin_load 1.0 [get_ports {result[6]}]
set_load -pin_load 1.0 [get_ports {result[5]}]
set_load -pin_load 1.0 [get_ports {result[4]}]
set_load -pin_load 1.0 [get_ports {result[3]}]
set_load -pin_load 1.0 [get_ports {result[2]}]
set_load -pin_load 1.0 [get_ports {result[1]}]
set_load -pin_load 1.0 [get_ports {result[0]}]
set_clock_gating_check -setup 0.0 
set_wire_load_mode "enclosed"
