
// Generated by Cadence Genus(TM) Synthesis Solution 25.12-s067_1
// Generated on: Jul 25 2026 12:02:37 -03 (Jul 25 2026 15:02:37 UTC)

// Verification Directory fv/x3_curto 

module x3_curto(XPower, X, clk);
  input [7:0] X;
  input clk;
  output [7:0] XPower;
  wire [7:0] X;
  wire clk;
  wire [7:0] XPower;
  wire [7:0] XPower2;
  wire [7:0] X1;
  wire [7:0] X2;
  wire mul_20_24_n_0, mul_20_24_n_1, mul_20_24_n_2, mul_20_24_n_3,
       mul_20_24_n_4, mul_20_24_n_5, mul_20_24_n_6, mul_20_24_n_7;
  wire mul_20_24_n_8, mul_20_24_n_9, mul_20_24_n_10, mul_20_24_n_11,
       mul_20_24_n_12, mul_20_24_n_13, mul_20_24_n_14, mul_20_24_n_15;
  wire mul_20_24_n_16, mul_20_24_n_17, mul_20_24_n_18, mul_20_24_n_19,
       mul_20_24_n_20, mul_20_24_n_22, mul_20_24_n_23, mul_20_24_n_24;
  wire mul_20_24_n_25, mul_20_24_n_26, mul_20_24_n_27, mul_20_24_n_28,
       mul_20_24_n_29, mul_20_24_n_30, mul_20_24_n_31, mul_20_24_n_32;
  wire mul_20_24_n_33, mul_20_24_n_34, mul_20_24_n_35, mul_20_24_n_36,
       mul_20_24_n_37, mul_20_24_n_38, mul_20_24_n_39, mul_20_24_n_41;
  wire mul_20_24_n_42, mul_20_24_n_43, mul_20_24_n_44, mul_20_24_n_45,
       mul_20_24_n_46, mul_20_24_n_47, mul_20_24_n_48, mul_20_24_n_49;
  wire mul_20_24_n_50, mul_20_24_n_51, mul_20_24_n_52, mul_20_24_n_53,
       mul_20_24_n_55, mul_20_24_n_56, mul_20_24_n_57, mul_20_24_n_58;
  wire mul_20_24_n_59, mul_20_24_n_60, mul_20_24_n_61, mul_20_24_n_63,
       mul_20_24_n_64, mul_20_24_n_66, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51;
  DFFQXL \XPower2_reg[7] (.CK (clk), .D (n_35), .Q (XPower2[7]));
  XNOR2X1 g1021__2398(.A (n_32), .B (n_34), .Y (n_35));
  XNOR2X1 g1022__5107(.A (n_26), .B (n_33), .Y (n_34));
  DFFQXL \XPower2_reg[6] (.CK (clk), .D (n_31), .Q (XPower2[6]));
  OAI21XL g1024__6260(.A0 (n_6), .A1 (n_9), .B0 (n_30), .Y (n_33));
  XNOR2X1 g1025__4319(.A (n_3), .B (n_28), .Y (n_32));
  DFFQXL \XPower2_reg[5] (.CK (clk), .D (n_29), .Q (XPower2[5]));
  OA21X1 g1027__8428(.A0 (n_25), .A1 (n_27), .B0 (n_30), .Y (n_31));
  NAND2XL g1028__5526(.A (n_25), .B (n_27), .Y (n_30));
  OAI22XL g1029__6783(.A0 (n_20), .A1 (n_24), .B0 (n_0), .B1 (n_17), .Y
       (n_29));
  AOI211XL g1030__3680(.A0 (X1[4]), .A1 (n_12), .B0 (n_16), .C0 (n_22),
       .Y (n_28));
  SDFFQX1 \XPower2_reg[4] (.CK (clk), .D (n_14), .SI (n_11), .SE (n_0),
       .Q (XPower2[4]));
  AND2XL g1032__1617(.A (n_23), .B (n_24), .Y (n_27));
  DFFHQX1 \XPower2_reg[3] (.CK (clk), .D (n_21), .Q (XPower2[3]));
  NAND2BXL g1034__2802(.AN (n_15), .B (X1[5]), .Y (n_26));
  OAI211X1 g1035__1705(.A0 (X1[1]), .A1 (n_8), .B0 (n_5), .C0 (n_15),
       .Y (n_23));
  AOI21XL g1036__5122(.A0 (n_10), .A1 (n_18), .B0 (n_22), .Y (n_25));
  OAI2BB1X1 g1037__8246(.A0N (X1[1]), .A1N (n_19), .B0 (n_6), .Y
       (n_24));
  NOR2X1 g1038__7098(.A (n_10), .B (n_18), .Y (n_22));
  NOR2X1 g1039__6131(.A (n_0), .B (n_13), .Y (n_21));
  AOI21XL g1040__1881(.A0 (X1[1]), .A1 (n_14), .B0 (n_7), .Y (n_20));
  AND2XL g1041__5115(.A (n_7), .B (n_14), .Y (n_19));
  XNOR2X1 g1042__7482(.A (n_2), .B (n_9), .Y (n_18));
  INVXL g1043(.A (n_16), .Y (n_17));
  DFFHQX1 \XPower2_reg[2] (.CK (clk), .D (n_4), .Q (XPower2[2]));
  NOR2XL g1045__4733(.A (X1[4]), .B (n_6), .Y (n_16));
  AOI21XL g1046__6161(.A0 (X1[1]), .A1 (n_1), .B0 (n_11), .Y (n_13));
  NAND2XL g1047__9315(.A (X1[1]), .B (n_8), .Y (n_15));
  NAND2BX1 g1048__9945(.AN (n_12), .B (n_10), .Y (n_14));
  DFFQXL \X2_reg[6] (.CK (clk), .D (X1[6]), .Q (X2[6]));
  DFFHQX1 \X2_reg[3] (.CK (clk), .D (X1[3]), .Q (X2[3]));
  DFFHQX1 \X2_reg[2] (.CK (clk), .D (X1[2]), .Q (X2[2]));
  DFFQXL \X2_reg[4] (.CK (clk), .D (X1[4]), .Q (X2[4]));
  DFFQXL \X2_reg[5] (.CK (clk), .D (X1[5]), .Q (X2[5]));
  DFFQXL \X2_reg[7] (.CK (clk), .D (X1[7]), .Q (X2[7]));
  DFFHQX1 \X2_reg[1] (.CK (clk), .D (X1[1]), .Q (X2[1]));
  DFFHQX1 \X2_reg[0] (.CK (clk), .D (X1[0]), .Q (X2[0]));
  INVX1 g1057(.A (n_8), .Y (n_7));
  INVX1 g1058(.A (n_6), .Y (n_5));
  NOR2BX1 g1059__2883(.AN (X1[1]), .B (X1[0]), .Y (n_4));
  NAND2XL g1060__2346(.A (X1[6]), .B (X1[0]), .Y (n_3));
  NAND2XL g1061__1666(.A (X1[5]), .B (X1[0]), .Y (n_2));
  NOR2XL g1062__7410(.A (X1[3]), .B (n_1), .Y (n_12));
  NOR2X1 g1063__6417(.A (X1[1]), .B (n_1), .Y (n_11));
  NAND2X1 g1064__5477(.A (X1[3]), .B (n_1), .Y (n_10));
  NAND2XL g1065__2398(.A (X1[1]), .B (X1[4]), .Y (n_9));
  NAND2X1 g1066__5107(.A (X1[4]), .B (X1[0]), .Y (n_8));
  NAND2X1 g1067__6260(.A (X1[3]), .B (X1[2]), .Y (n_6));
  DFFQXL \XPower_reg[6] (.CK (clk), .D (n_46), .Q (XPower[6]));
  DFFQXL \XPower_reg[2] (.CK (clk), .D (n_50), .Q (XPower[2]));
  DFFQXL \XPower_reg[5] (.CK (clk), .D (n_47), .Q (XPower[5]));
  DFFQXL \X1_reg[6] (.CK (clk), .D (X[6]), .Q (X1[6]));
  DFFQXL \X1_reg[5] (.CK (clk), .D (X[5]), .Q (X1[5]));
  DFFQXL \X1_reg[3] (.CK (clk), .D (X[3]), .Q (X1[3]));
  DFFHQX1 \X1_reg[4] (.CK (clk), .D (X[4]), .Q (X1[4]));
  DFFHQX1 \X1_reg[1] (.CK (clk), .D (X[1]), .Q (X1[1]));
  INVX1 g1076(.A (X1[2]), .Y (n_1));
  INVX1 g1077(.A (X1[0]), .Y (n_0));
  DFFQXL \XPower_reg[3] (.CK (clk), .D (n_49), .Q (XPower[3]));
  DFFQXL \XPower_reg[4] (.CK (clk), .D (n_48), .Q (XPower[4]));
  DFFQXL \XPower_reg[1] (.CK (clk), .D (n_51), .Q (XPower[1]));
  DFFQXL \X1_reg[7] (.CK (clk), .D (X[7]), .Q (X1[7]));
  DFFQXL \XPower_reg[0] (.CK (clk), .D (X2[0]), .Q (XPower[0]));
  DFFQXL \XPower_reg[7] (.CK (clk), .D (n_45), .Q (XPower[7]));
  DFFQXL \X1_reg[2] (.CK (clk), .D (X[2]), .Q (X1[2]));
  DFFHQX1 \X1_reg[0] (.CK (clk), .D (X[0]), .Q (X1[0]));
  XNOR2X1 mul_20_24_g480__4319(.A (mul_20_24_n_63), .B
       (mul_20_24_n_66), .Y (n_45));
  ADDFX1 mul_20_24_g481__8428(.A (mul_20_24_n_55), .B (mul_20_24_n_64),
       .CI (mul_20_24_n_59), .CO (mul_20_24_n_66), .S (n_46));
  ADDFX1 mul_20_24_g482__5526(.A (mul_20_24_n_47), .B (mul_20_24_n_61),
       .CI (mul_20_24_n_56), .CO (mul_20_24_n_64), .S (n_47));
  XNOR2X1 mul_20_24_g483__6783(.A (mul_20_24_n_58), .B
       (mul_20_24_n_60), .Y (mul_20_24_n_63));
  ADDFX1 mul_20_24_g484__3680(.A (mul_20_24_n_30), .B (mul_20_24_n_53),
       .CI (mul_20_24_n_48), .CO (mul_20_24_n_61), .S (n_48));
  XNOR2X1 mul_20_24_g485__1617(.A (mul_20_24_n_57), .B
       (mul_20_24_n_52), .Y (mul_20_24_n_60));
  ADDFX1 mul_20_24_g486__2802(.A (mul_20_24_n_45), .B (mul_20_24_n_44),
       .CI (mul_20_24_n_51), .CO (mul_20_24_n_58), .S (mul_20_24_n_59));
  XNOR2X1 mul_20_24_g487__1705(.A (mul_20_24_n_42), .B
       (mul_20_24_n_50), .Y (mul_20_24_n_57));
  ADDFX1 mul_20_24_g488__5122(.A (mul_20_24_n_29), .B (mul_20_24_n_33),
       .CI (mul_20_24_n_46), .CO (mul_20_24_n_55), .S (mul_20_24_n_56));
  ADDFX1 mul_20_24_g489__8246(.A (mul_20_24_n_3), .B (mul_20_24_n_28),
       .CI (mul_20_24_n_34), .CO (mul_20_24_n_53), .S (n_49));
  XNOR2X1 mul_20_24_g490__7098(.A (mul_20_24_n_41), .B
       (mul_20_24_n_49), .Y (mul_20_24_n_52));
  ADDFX1 mul_20_24_g491__6131(.A (mul_20_24_n_4), .B (mul_20_24_n_31),
       .CI (mul_20_24_n_35), .CO (mul_20_24_n_50), .S (mul_20_24_n_51));
  XNOR2X1 mul_20_24_g492__1881(.A (mul_20_24_n_37), .B
       (mul_20_24_n_43), .Y (mul_20_24_n_49));
  ADDFX1 mul_20_24_g493__5115(.A (mul_20_24_n_14), .B (mul_20_24_n_15),
       .CI (mul_20_24_n_36), .CO (mul_20_24_n_47), .S (mul_20_24_n_48));
  ADDFX1 mul_20_24_g494__7482(.A (mul_20_24_n_1), .B (mul_20_24_n_0),
       .CI (mul_20_24_n_17), .CO (mul_20_24_n_45), .S (mul_20_24_n_46));
  ADDFX1 mul_20_24_g495__4733(.A (mul_20_24_n_2), .B (mul_20_24_n_16),
       .CI (mul_20_24_n_18), .CO (mul_20_24_n_43), .S (mul_20_24_n_44));
  XNOR2X1 mul_20_24_g496__6161(.A (mul_20_24_n_32), .B
       (mul_20_24_n_39), .Y (mul_20_24_n_42));
  XNOR2X1 mul_20_24_g497__9315(.A (mul_20_24_n_7), .B (mul_20_24_n_38),
       .Y (mul_20_24_n_41));
  AOI21XL mul_20_24_g498__9945(.A0 (mul_20_24_n_27), .A1
       (mul_20_24_n_26), .B0 (mul_20_24_n_28), .Y (n_50));
  XNOR2X1 mul_20_24_g499__2883(.A (mul_20_24_n_20), .B (mul_20_24_n_8),
       .Y (mul_20_24_n_39));
  XNOR2X1 mul_20_24_g500__2346(.A (mul_20_24_n_19), .B (mul_20_24_n_9),
       .Y (mul_20_24_n_38));
  XNOR2X1 mul_20_24_g501__1666(.A (mul_20_24_n_6), .B (mul_20_24_n_5),
       .Y (mul_20_24_n_37));
  XOR2XL mul_20_24_g502__7410(.A (mul_20_24_n_22), .B (mul_20_24_n_11),
       .Y (mul_20_24_n_36));
  XOR2XL mul_20_24_g503__6417(.A (mul_20_24_n_25), .B (mul_20_24_n_24),
       .Y (mul_20_24_n_35));
  XOR2XL mul_20_24_g504__5477(.A (mul_20_24_n_10), .B (mul_20_24_n_12),
       .Y (mul_20_24_n_34));
  XOR2XL mul_20_24_g505__2398(.A (mul_20_24_n_13), .B (mul_20_24_n_23),
       .Y (mul_20_24_n_33));
  NOR2XL mul_20_24_g506__5107(.A (mul_20_24_n_25), .B (mul_20_24_n_24),
       .Y (mul_20_24_n_32));
  NOR2X1 mul_20_24_g507__6260(.A (mul_20_24_n_13), .B (mul_20_24_n_23),
       .Y (mul_20_24_n_31));
  NOR2X1 mul_20_24_g508__4319(.A (mul_20_24_n_10), .B (mul_20_24_n_12),
       .Y (mul_20_24_n_30));
  NOR2X1 mul_20_24_g509__8428(.A (mul_20_24_n_22), .B (mul_20_24_n_11),
       .Y (mul_20_24_n_29));
  NOR2X1 mul_20_24_g510__5526(.A (mul_20_24_n_27), .B (mul_20_24_n_26),
       .Y (mul_20_24_n_28));
  AND2XL mul_20_24_g511__6783(.A (X2[1]), .B (X2[0]), .Y (n_51));
  NAND2XL mul_20_24_g512__3680(.A (X2[5]), .B (XPower2[2]), .Y
       (mul_20_24_n_20));
  NAND2XL mul_20_24_g513__1617(.A (X2[2]), .B (XPower2[5]), .Y
       (mul_20_24_n_19));
  NAND2XL mul_20_24_g514__2802(.A (X2[2]), .B (X2[0]), .Y
       (mul_20_24_n_27));
  NAND2XL mul_20_24_g515__1705(.A (XPower2[2]), .B (X2[0]), .Y
       (mul_20_24_n_26));
  NAND2X1 mul_20_24_g516__5122(.A (XPower2[5]), .B (X2[1]), .Y
       (mul_20_24_n_25));
  AND2XL mul_20_24_g517__8246(.A (X2[6]), .B (X2[0]), .Y
       (mul_20_24_n_18));
  NAND2XL mul_20_24_g518__7098(.A (XPower2[6]), .B (X2[0]), .Y
       (mul_20_24_n_24));
  NAND2XL mul_20_24_g519__6131(.A (XPower2[5]), .B (X2[0]), .Y
       (mul_20_24_n_23));
  AND2XL mul_20_24_g520__1881(.A (X2[5]), .B (X2[0]), .Y
       (mul_20_24_n_17));
  NAND2XL mul_20_24_g521__5115(.A (X2[1]), .B (XPower2[3]), .Y
       (mul_20_24_n_22));
  AND2X1 mul_20_24_g522__7482(.A (XPower2[3]), .B (X2[3]), .Y
       (mul_20_24_n_16));
  AND2XL mul_20_24_g523__4733(.A (X2[4]), .B (X2[0]), .Y
       (mul_20_24_n_15));
  AND2XL mul_20_24_g524__6161(.A (X2[2]), .B (XPower2[2]), .Y
       (mul_20_24_n_14));
  NAND2XL mul_20_24_g525__9315(.A (X2[4]), .B (XPower2[3]), .Y
       (mul_20_24_n_9));
  NAND2XL mul_20_24_g526__9945(.A (X2[7]), .B (X2[0]), .Y
       (mul_20_24_n_8));
  NAND2XL mul_20_24_g527__2883(.A (X2[3]), .B (XPower2[4]), .Y
       (mul_20_24_n_7));
  NAND2XL mul_20_24_g528__2346(.A (XPower2[6]), .B (X2[1]), .Y
       (mul_20_24_n_6));
  NAND2XL mul_20_24_g529__1666(.A (XPower2[7]), .B (X2[0]), .Y
       (mul_20_24_n_5));
  NAND2X1 mul_20_24_g530__7410(.A (XPower2[4]), .B (X2[1]), .Y
       (mul_20_24_n_13));
  NAND2X1 mul_20_24_g531__6417(.A (XPower2[3]), .B (X2[0]), .Y
       (mul_20_24_n_12));
  NAND2XL mul_20_24_g532__5477(.A (XPower2[4]), .B (X2[0]), .Y
       (mul_20_24_n_11));
  NAND2X1 mul_20_24_g533__2398(.A (X2[1]), .B (XPower2[2]), .Y
       (mul_20_24_n_10));
  AND2X1 mul_20_24_g534__5107(.A (X2[2]), .B (XPower2[4]), .Y
       (mul_20_24_n_4));
  AND2X1 mul_20_24_g535__6260(.A (X2[0]), .B (X2[3]), .Y
       (mul_20_24_n_3));
  AND2X1 mul_20_24_g536__4319(.A (XPower2[2]), .B (X2[4]), .Y
       (mul_20_24_n_2));
  AND2X1 mul_20_24_g537__8428(.A (XPower2[2]), .B (X2[3]), .Y
       (mul_20_24_n_1));
  AND2X1 mul_20_24_g538__5526(.A (XPower2[3]), .B (X2[2]), .Y
       (mul_20_24_n_0));
endmodule

