
// Generated by Cadence Genus(TM) Synthesis Solution 25.12-s067_1
// Generated on: Jul 24 2026 20:40:19 -03 (Jul 24 2026 23:40:19 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  DFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_13), .Q
       (count[7]));
  DFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_12), .Q
       (count[6]));
  XNOR2X1 g416__2398(.A (count[7]), .B (n_11), .Y (n_13));
  OA21X1 g418__5107(.A0 (count[6]), .A1 (n_10), .B0 (n_11), .Y (n_12));
  DFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_9), .Q
       (count[5]));
  NAND2X1 g420__6260(.A (count[6]), .B (n_10), .Y (n_11));
  DFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_7), .Q
       (count[4]));
  XNOR2X1 g421__4319(.A (count[5]), .B (n_8), .Y (n_9));
  NOR2BX1 g423__8428(.AN (count[5]), .B (n_8), .Y (n_10));
  OA21X1 g424__5526(.A0 (count[4]), .A1 (n_6), .B0 (n_8), .Y (n_7));
  DFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_5), .Q
       (count[3]));
  NAND2X1 g426__6783(.A (count[4]), .B (n_6), .Y (n_8));
  DFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_3), .Q
       (count[2]));
  XNOR2X1 g427__3680(.A (count[3]), .B (n_4), .Y (n_5));
  NOR2BX1 g429__1617(.AN (count[3]), .B (n_4), .Y (n_6));
  OA21X1 g430__2802(.A0 (count[2]), .A1 (n_2), .B0 (n_4), .Y (n_3));
  NAND2X1 g432__1705(.A (count[2]), .B (n_2), .Y (n_4));
  DFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_1), .Q
       (count[1]));
  ADDHX1 g433__5122(.A (count[0]), .B (count[1]), .CO (n_2), .S (n_1));
  DFFRX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
endmodule

