
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point start start -type PI PI
add mapped point valid valid -type PI PI
add mapped point a[31] a[31] -type PI PI
add mapped point a[30] a[30] -type PI PI
add mapped point a[29] a[29] -type PI PI
add mapped point a[28] a[28] -type PI PI
add mapped point a[27] a[27] -type PI PI
add mapped point a[26] a[26] -type PI PI
add mapped point a[25] a[25] -type PI PI
add mapped point a[24] a[24] -type PI PI
add mapped point a[23] a[23] -type PI PI
add mapped point a[22] a[22] -type PI PI
add mapped point a[21] a[21] -type PI PI
add mapped point a[20] a[20] -type PI PI
add mapped point a[19] a[19] -type PI PI
add mapped point a[18] a[18] -type PI PI
add mapped point a[17] a[17] -type PI PI
add mapped point a[16] a[16] -type PI PI
add mapped point a[15] a[15] -type PI PI
add mapped point a[14] a[14] -type PI PI
add mapped point a[13] a[13] -type PI PI
add mapped point a[12] a[12] -type PI PI
add mapped point a[11] a[11] -type PI PI
add mapped point a[10] a[10] -type PI PI
add mapped point a[9] a[9] -type PI PI
add mapped point a[8] a[8] -type PI PI
add mapped point a[7] a[7] -type PI PI
add mapped point a[6] a[6] -type PI PI
add mapped point a[5] a[5] -type PI PI
add mapped point a[4] a[4] -type PI PI
add mapped point a[3] a[3] -type PI PI
add mapped point a[2] a[2] -type PI PI
add mapped point a[1] a[1] -type PI PI
add mapped point a[0] a[0] -type PI PI
add mapped point b[31] b[31] -type PI PI
add mapped point b[30] b[30] -type PI PI
add mapped point b[29] b[29] -type PI PI
add mapped point b[28] b[28] -type PI PI
add mapped point b[27] b[27] -type PI PI
add mapped point b[26] b[26] -type PI PI
add mapped point b[25] b[25] -type PI PI
add mapped point b[24] b[24] -type PI PI
add mapped point b[23] b[23] -type PI PI
add mapped point b[22] b[22] -type PI PI
add mapped point b[21] b[21] -type PI PI
add mapped point b[20] b[20] -type PI PI
add mapped point b[19] b[19] -type PI PI
add mapped point b[18] b[18] -type PI PI
add mapped point b[17] b[17] -type PI PI
add mapped point b[16] b[16] -type PI PI
add mapped point b[15] b[15] -type PI PI
add mapped point b[14] b[14] -type PI PI
add mapped point b[13] b[13] -type PI PI
add mapped point b[12] b[12] -type PI PI
add mapped point b[11] b[11] -type PI PI
add mapped point b[10] b[10] -type PI PI
add mapped point b[9] b[9] -type PI PI
add mapped point b[8] b[8] -type PI PI
add mapped point b[7] b[7] -type PI PI
add mapped point b[6] b[6] -type PI PI
add mapped point b[5] b[5] -type PI PI
add mapped point b[4] b[4] -type PI PI
add mapped point b[3] b[3] -type PI PI
add mapped point b[2] b[2] -type PI PI
add mapped point b[1] b[1] -type PI PI
add mapped point b[0] b[0] -type PI PI

//output ports
add mapped point busy busy -type PO PO
add mapped point done done -type PO PO
add mapped point result[73] result[73] -type PO PO
add mapped point result[72] result[72] -type PO PO
add mapped point result[71] result[71] -type PO PO
add mapped point result[70] result[70] -type PO PO
add mapped point result[69] result[69] -type PO PO
add mapped point result[68] result[68] -type PO PO
add mapped point result[67] result[67] -type PO PO
add mapped point result[66] result[66] -type PO PO
add mapped point result[65] result[65] -type PO PO
add mapped point result[64] result[64] -type PO PO
add mapped point result[63] result[63] -type PO PO
add mapped point result[62] result[62] -type PO PO
add mapped point result[61] result[61] -type PO PO
add mapped point result[60] result[60] -type PO PO
add mapped point result[59] result[59] -type PO PO
add mapped point result[58] result[58] -type PO PO
add mapped point result[57] result[57] -type PO PO
add mapped point result[56] result[56] -type PO PO
add mapped point result[55] result[55] -type PO PO
add mapped point result[54] result[54] -type PO PO
add mapped point result[53] result[53] -type PO PO
add mapped point result[52] result[52] -type PO PO
add mapped point result[51] result[51] -type PO PO
add mapped point result[50] result[50] -type PO PO
add mapped point result[49] result[49] -type PO PO
add mapped point result[48] result[48] -type PO PO
add mapped point result[47] result[47] -type PO PO
add mapped point result[46] result[46] -type PO PO
add mapped point result[45] result[45] -type PO PO
add mapped point result[44] result[44] -type PO PO
add mapped point result[43] result[43] -type PO PO
add mapped point result[42] result[42] -type PO PO
add mapped point result[41] result[41] -type PO PO
add mapped point result[40] result[40] -type PO PO
add mapped point result[39] result[39] -type PO PO
add mapped point result[38] result[38] -type PO PO
add mapped point result[37] result[37] -type PO PO
add mapped point result[36] result[36] -type PO PO
add mapped point result[35] result[35] -type PO PO
add mapped point result[34] result[34] -type PO PO
add mapped point result[33] result[33] -type PO PO
add mapped point result[32] result[32] -type PO PO
add mapped point result[31] result[31] -type PO PO
add mapped point result[30] result[30] -type PO PO
add mapped point result[29] result[29] -type PO PO
add mapped point result[28] result[28] -type PO PO
add mapped point result[27] result[27] -type PO PO
add mapped point result[26] result[26] -type PO PO
add mapped point result[25] result[25] -type PO PO
add mapped point result[24] result[24] -type PO PO
add mapped point result[23] result[23] -type PO PO
add mapped point result[22] result[22] -type PO PO
add mapped point result[21] result[21] -type PO PO
add mapped point result[20] result[20] -type PO PO
add mapped point result[19] result[19] -type PO PO
add mapped point result[18] result[18] -type PO PO
add mapped point result[17] result[17] -type PO PO
add mapped point result[16] result[16] -type PO PO
add mapped point result[15] result[15] -type PO PO
add mapped point result[14] result[14] -type PO PO
add mapped point result[13] result[13] -type PO PO
add mapped point result[12] result[12] -type PO PO
add mapped point result[11] result[11] -type PO PO
add mapped point result[10] result[10] -type PO PO
add mapped point result[9] result[9] -type PO PO
add mapped point result[8] result[8] -type PO PO
add mapped point result[7] result[7] -type PO PO
add mapped point result[6] result[6] -type PO PO
add mapped point result[5] result[5] -type PO PO
add mapped point result[4] result[4] -type PO PO
add mapped point result[3] result[3] -type PO PO
add mapped point result[2] result[2] -type PO PO
add mapped point result[1] result[1] -type PO PO
add mapped point result[0] result[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point done/q done_reg/Q -type DFF DFF
add mapped point busy/q busy_reg/Q -type DFF DFF
add mapped point count[1]/q count_reg[1]/Q -type DFF DFF
add mapped point count[2]/q count_reg[2]/Q -type DFF DFF
add mapped point count[3]/q count_reg[3]/Q -type DFF DFF
add mapped point count[4]/q count_reg[4]/Q -type DFF DFF
add mapped point count[5]/q count_reg[5]/Q -type DFF DFF
add mapped point count[6]/q count_reg[6]/Q -type DFF DFF
add mapped point count[7]/q count_reg[7]/Q -type DFF DFF
add mapped point count[8]/q count_reg[8]/Q -type DFF DFF
add mapped point count[9]/q count_reg[9]/Q -type DFF DFF
add mapped point result[0]/q result_reg[0]/Q -type DFF DFF
add mapped point result[1]/q result_reg[1]/Q -type DFF DFF
add mapped point result[2]/q result_reg[2]/Q -type DFF DFF
add mapped point result[3]/q result_reg[3]/Q -type DFF DFF
add mapped point result[4]/q result_reg[4]/Q -type DFF DFF
add mapped point result[6]/q result_reg[6]/Q -type DFF DFF
add mapped point result[7]/q result_reg[7]/Q -type DFF DFF
add mapped point result[8]/q result_reg[8]/Q -type DFF DFF
add mapped point result[9]/q result_reg[9]/Q -type DFF DFF
add mapped point result[10]/q result_reg[10]/Q -type DFF DFF
add mapped point result[11]/q result_reg[11]/Q -type DFF DFF
add mapped point result[12]/q result_reg[12]/Q -type DFF DFF
add mapped point result[13]/q result_reg[13]/Q -type DFF DFF
add mapped point result[14]/q result_reg[14]/Q -type DFF DFF
add mapped point result[15]/q result_reg[15]/Q -type DFF DFF
add mapped point result[16]/q result_reg[16]/Q -type DFF DFF
add mapped point result[17]/q result_reg[17]/Q -type DFF DFF
add mapped point result[18]/q result_reg[18]/Q -type DFF DFF
add mapped point result[19]/q result_reg[19]/Q -type DFF DFF
add mapped point result[20]/q result_reg[20]/Q -type DFF DFF
add mapped point result[21]/q result_reg[21]/Q -type DFF DFF
add mapped point result[22]/q result_reg[22]/Q -type DFF DFF
add mapped point result[23]/q result_reg[23]/Q -type DFF DFF
add mapped point result[24]/q result_reg[24]/Q -type DFF DFF
add mapped point result[25]/q result_reg[25]/Q -type DFF DFF
add mapped point result[26]/q result_reg[26]/Q -type DFF DFF
add mapped point result[27]/q result_reg[27]/Q -type DFF DFF
add mapped point result[28]/q result_reg[28]/Q -type DFF DFF
add mapped point result[29]/q result_reg[29]/Q -type DFF DFF
add mapped point result[30]/q result_reg[30]/Q -type DFF DFF
add mapped point result[31]/q result_reg[31]/Q -type DFF DFF
add mapped point result[32]/q result_reg[32]/Q -type DFF DFF
add mapped point result[33]/q result_reg[33]/Q -type DFF DFF
add mapped point result[34]/q result_reg[34]/Q -type DFF DFF
add mapped point result[35]/q result_reg[35]/Q -type DFF DFF
add mapped point result[36]/q result_reg[36]/Q -type DFF DFF
add mapped point result[37]/q result_reg[37]/Q -type DFF DFF
add mapped point result[38]/q result_reg[38]/Q -type DFF DFF
add mapped point result[39]/q result_reg[39]/Q -type DFF DFF
add mapped point result[40]/q result_reg[40]/Q -type DFF DFF
add mapped point result[41]/q result_reg[41]/Q -type DFF DFF
add mapped point result[42]/q result_reg[42]/Q -type DFF DFF
add mapped point result[43]/q result_reg[43]/Q -type DFF DFF
add mapped point result[44]/q result_reg[44]/Q -type DFF DFF
add mapped point result[45]/q result_reg[45]/Q -type DFF DFF
add mapped point result[46]/q result_reg[46]/Q -type DFF DFF
add mapped point result[47]/q result_reg[47]/Q -type DFF DFF
add mapped point result[48]/q result_reg[48]/Q -type DFF DFF
add mapped point result[49]/q result_reg[49]/Q -type DFF DFF
add mapped point result[50]/q result_reg[50]/Q -type DFF DFF
add mapped point result[51]/q result_reg[51]/Q -type DFF DFF
add mapped point result[52]/q result_reg[52]/Q -type DFF DFF
add mapped point result[53]/q result_reg[53]/Q -type DFF DFF
add mapped point result[54]/q result_reg[54]/Q -type DFF DFF
add mapped point result[55]/q result_reg[55]/Q -type DFF DFF
add mapped point result[56]/q result_reg[56]/Q -type DFF DFF
add mapped point result[57]/q result_reg[57]/Q -type DFF DFF
add mapped point result[58]/q result_reg[58]/Q -type DFF DFF
add mapped point result[59]/q result_reg[59]/Q -type DFF DFF
add mapped point result[60]/q result_reg[60]/Q -type DFF DFF
add mapped point result[61]/q result_reg[61]/Q -type DFF DFF
add mapped point result[62]/q result_reg[62]/Q -type DFF DFF
add mapped point result[63]/q result_reg[63]/Q -type DFF DFF
add mapped point result[64]/q result_reg[64]/Q -type DFF DFF
add mapped point result[65]/q result_reg[65]/Q -type DFF DFF
add mapped point result[66]/q result_reg[66]/Q -type DFF DFF
add mapped point result[67]/q result_reg[67]/Q -type DFF DFF
add mapped point result[68]/q result_reg[68]/Q -type DFF DFF
add mapped point result[69]/q result_reg[69]/Q -type DFF DFF
add mapped point result[70]/q result_reg[70]/Q -type DFF DFF
add mapped point result[71]/q result_reg[71]/Q -type DFF DFF
add mapped point result[72]/q result_reg[72]/Q -type DFF DFF
add mapped point result[73]/q result_reg[73]/Q -type DFF DFF
add mapped point count[0]/q count_reg[0]/Q -type DFF DFF
add mapped point result[5]/q result_reg[5]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
