
// Generated by Cadence Genus(TM) Synthesis Solution 25.12-s067_1
// Generated on: Jul 24 2026 20:25:49 -03 (Jul 24 2026 23:25:49 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  DFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_13), .Q
       (count[7]));
  CLKXOR2X1 g416__2398(.A (count[7]), .B (n_11), .Y (n_13));
  DFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_12), .Q
       (count[6]));
  ADDHX1 g418__5107(.A (count[6]), .B (n_9), .CO (n_11), .S (n_12));
  DFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_10), .Q
       (count[5]));
  ADDHX1 g420__6260(.A (count[5]), .B (n_7), .CO (n_9), .S (n_10));
  DFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_8), .Q
       (count[4]));
  ADDHX1 g422__4319(.A (count[4]), .B (n_5), .CO (n_7), .S (n_8));
  DFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_6), .Q
       (count[3]));
  ADDHX1 g424__8428(.A (count[3]), .B (n_3), .CO (n_5), .S (n_6));
  DFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_4), .Q
       (count[2]));
  ADDHX1 g426__5526(.A (count[2]), .B (n_1), .CO (n_3), .S (n_4));
  DFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_2), .Q
       (count[1]));
  ADDHX1 g428__6783(.A (count[1]), .B (count[0]), .CO (n_1), .S (n_2));
  DFFRX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
endmodule

