# ####################################################################

#  Created by Genus(TM) Synthesis Solution 25.12-s067_1 on Sat Aug 22 09:49:48 -03 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design pattern_detector

create_clock -name "clk" -period 10.0 -waveform {0.0 5.0} [get_ports clk]
set_clock_transition 0.1 [get_clocks clk]
set_load -pin_load -max 0.02 [get_ports in_ready]
set_load -pin_load -max 0.01 [get_ports {rom_addr[2]}]
set_load -pin_load -max 0.01 [get_ports {rom_addr[1]}]
set_load -pin_load -max 0.01 [get_ports {rom_addr[0]}]
set_load -pin_load -max 0.02 [get_ports {out_data[34]}]
set_load -pin_load -max 0.02 [get_ports {out_data[33]}]
set_load -pin_load -max 0.02 [get_ports {out_data[32]}]
set_load -pin_load -max 0.02 [get_ports {out_data[31]}]
set_load -pin_load -max 0.02 [get_ports {out_data[30]}]
set_load -pin_load -max 0.02 [get_ports {out_data[29]}]
set_load -pin_load -max 0.02 [get_ports {out_data[28]}]
set_load -pin_load -max 0.02 [get_ports {out_data[27]}]
set_load -pin_load -max 0.02 [get_ports {out_data[26]}]
set_load -pin_load -max 0.02 [get_ports {out_data[25]}]
set_load -pin_load -max 0.02 [get_ports {out_data[24]}]
set_load -pin_load -max 0.02 [get_ports {out_data[23]}]
set_load -pin_load -max 0.02 [get_ports {out_data[22]}]
set_load -pin_load -max 0.02 [get_ports {out_data[21]}]
set_load -pin_load -max 0.02 [get_ports {out_data[20]}]
set_load -pin_load -max 0.02 [get_ports {out_data[19]}]
set_load -pin_load -max 0.02 [get_ports {out_data[18]}]
set_load -pin_load -max 0.02 [get_ports {out_data[17]}]
set_load -pin_load -max 0.02 [get_ports {out_data[16]}]
set_load -pin_load -max 0.02 [get_ports {out_data[15]}]
set_load -pin_load -max 0.02 [get_ports {out_data[14]}]
set_load -pin_load -max 0.02 [get_ports {out_data[13]}]
set_load -pin_load -max 0.02 [get_ports {out_data[12]}]
set_load -pin_load -max 0.02 [get_ports {out_data[11]}]
set_load -pin_load -max 0.02 [get_ports {out_data[10]}]
set_load -pin_load -max 0.02 [get_ports {out_data[9]}]
set_load -pin_load -max 0.02 [get_ports {out_data[8]}]
set_load -pin_load -max 0.02 [get_ports {out_data[7]}]
set_load -pin_load -max 0.02 [get_ports {out_data[6]}]
set_load -pin_load -max 0.02 [get_ports {out_data[5]}]
set_load -pin_load -max 0.02 [get_ports {out_data[4]}]
set_load -pin_load -max 0.02 [get_ports {out_data[3]}]
set_load -pin_load -max 0.02 [get_ports {out_data[2]}]
set_load -pin_load -max 0.02 [get_ports {out_data[1]}]
set_load -pin_load -max 0.02 [get_ports {out_data[0]}]
set_load -pin_load -max 0.02 [get_ports out_valid]
set_false_path -from [get_ports rst_n]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[15]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[14]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports {in_data[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports in_valid]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.5 [get_ports out_ready]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[15]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[14]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 1.6 [get_ports {rom_data[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[34]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[33]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[32]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[31]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[30]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[29]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[28]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[27]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[26]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[25]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[24]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[23]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[22]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[21]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[20]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[19]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[18]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[17]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[16]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[15]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[14]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[13]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[12]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports {out_data[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports out_valid]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.3 [get_ports in_ready]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {rom_addr[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {rom_addr[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 1.0 [get_ports {rom_addr[0]}]
set_input_transition 0.2 [get_ports {in_data[15]}]
set_input_transition 0.2 [get_ports {in_data[14]}]
set_input_transition 0.2 [get_ports {in_data[13]}]
set_input_transition 0.2 [get_ports {in_data[12]}]
set_input_transition 0.2 [get_ports {in_data[11]}]
set_input_transition 0.2 [get_ports {in_data[10]}]
set_input_transition 0.2 [get_ports {in_data[9]}]
set_input_transition 0.2 [get_ports {in_data[8]}]
set_input_transition 0.2 [get_ports {in_data[7]}]
set_input_transition 0.2 [get_ports {in_data[6]}]
set_input_transition 0.2 [get_ports {in_data[5]}]
set_input_transition 0.2 [get_ports {in_data[4]}]
set_input_transition 0.2 [get_ports {in_data[3]}]
set_input_transition 0.2 [get_ports {in_data[2]}]
set_input_transition 0.2 [get_ports {in_data[1]}]
set_input_transition 0.2 [get_ports {in_data[0]}]
set_input_transition 0.2 [get_ports in_valid]
set_input_transition 0.15 [get_ports {rom_data[15]}]
set_input_transition 0.15 [get_ports {rom_data[14]}]
set_input_transition 0.15 [get_ports {rom_data[13]}]
set_input_transition 0.15 [get_ports {rom_data[12]}]
set_input_transition 0.15 [get_ports {rom_data[11]}]
set_input_transition 0.15 [get_ports {rom_data[10]}]
set_input_transition 0.15 [get_ports {rom_data[9]}]
set_input_transition 0.15 [get_ports {rom_data[8]}]
set_input_transition 0.15 [get_ports {rom_data[7]}]
set_input_transition 0.15 [get_ports {rom_data[6]}]
set_input_transition 0.15 [get_ports {rom_data[5]}]
set_input_transition 0.15 [get_ports {rom_data[4]}]
set_input_transition 0.15 [get_ports {rom_data[3]}]
set_input_transition 0.15 [get_ports {rom_data[2]}]
set_input_transition 0.15 [get_ports {rom_data[1]}]
set_input_transition 0.15 [get_ports {rom_data[0]}]
set_input_transition 0.2 [get_ports out_ready]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.2 [get_clocks clk]
