
// Generated by Cadence Genus(TM) Synthesis Solution 25.12-s067_1
// Generated on: Aug 15 2026 09:26:06 -03 (Aug 15 2026 12:26:06 UTC)

// Verification Directory fv/x3_curto 

module x3_curto(XPower, X, clk);
  input [7:0] X;
  input clk;
  output [7:0] XPower;
  wire [7:0] X;
  wire clk;
  wire [7:0] XPower;
  wire [7:0] XPower2;
  wire [7:0] X1;
  wire [7:0] X2;
  wire mul_20_24_n_0, mul_20_24_n_1, mul_20_24_n_2, mul_20_24_n_3,
       mul_20_24_n_4, mul_20_24_n_5, mul_20_24_n_6, mul_20_24_n_7;
  wire mul_20_24_n_8, mul_20_24_n_9, mul_20_24_n_10, mul_20_24_n_11,
       mul_20_24_n_12, mul_20_24_n_13, mul_20_24_n_14, mul_20_24_n_15;
  wire mul_20_24_n_16, mul_20_24_n_17, mul_20_24_n_18, mul_20_24_n_19,
       mul_20_24_n_20, mul_20_24_n_22, mul_20_24_n_23, mul_20_24_n_24;
  wire mul_20_24_n_25, mul_20_24_n_26, mul_20_24_n_27, mul_20_24_n_28,
       mul_20_24_n_29, mul_20_24_n_30, mul_20_24_n_31, mul_20_24_n_32;
  wire mul_20_24_n_33, mul_20_24_n_34, mul_20_24_n_35, mul_20_24_n_36,
       mul_20_24_n_37, mul_20_24_n_38, mul_20_24_n_39, mul_20_24_n_41;
  wire mul_20_24_n_42, mul_20_24_n_43, mul_20_24_n_44, mul_20_24_n_45,
       mul_20_24_n_46, mul_20_24_n_47, mul_20_24_n_48, mul_20_24_n_49;
  wire mul_20_24_n_50, mul_20_24_n_51, mul_20_24_n_52, mul_20_24_n_53,
       mul_20_24_n_55, mul_20_24_n_56, mul_20_24_n_57, mul_20_24_n_58;
  wire mul_20_24_n_59, mul_20_24_n_60, mul_20_24_n_61, mul_20_24_n_63,
       mul_20_24_n_64, mul_20_24_n_66, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52;
  DFFQXL \XPower2_reg[7] (.CK (clk), .D (n_36), .Q (XPower2[7]));
  XNOR2X1 g1043__2398(.A (n_4), .B (n_35), .Y (n_36));
  OAI22X1 g1044__5107(.A0 (n_2), .A1 (n_34), .B0 (n_24), .B1 (n_30), .Y
       (n_35));
  DFFHQX1 \XPower2_reg[6] (.CK (clk), .D (n_33), .Q (XPower2[6]));
  MXI2XL g1046__6260(.A (n_23), .B (n_32), .S0 (X1[5]), .Y (n_34));
  XNOR2X1 g1047__4319(.A (n_7), .B (n_29), .Y (n_33));
  DFFHQX1 \XPower2_reg[5] (.CK (clk), .D (n_31), .Q (XPower2[5]));
  OAI21X1 g1049__8428(.A0 (n_12), .A1 (n_28), .B0 (n_10), .Y (n_32));
  DFFHQX1 \XPower2_reg[4] (.CK (clk), .D (n_27), .Q (XPower2[4]));
  AOI221X1 g1051__5526(.A0 (n_8), .A1 (n_22), .B0 (n_0), .B1 (n_14),
       .C0 (n_26), .Y (n_31));
  AOI21X1 g1052__6783(.A0 (n_17), .A1 (n_25), .B0 (n_13), .Y (n_30));
  OAI22X1 g1053__3680(.A0 (n_25), .A1 (n_26), .B0 (n_1), .B1 (n_15), .Y
       (n_29));
  AOI21X1 g1054__1617(.A0 (n_0), .A1 (n_16), .B0 (X1[2]), .Y (n_28));
  OAI31X1 g1055__2802(.A0 (n_0), .A1 (n_14), .A2 (n_18), .B0 (n_19), .Y
       (n_27));
  DFFHQX1 \XPower2_reg[3] (.CK (clk), .D (n_20), .Q (XPower2[3]));
  NOR2X1 g1057__1705(.A (n_8), .B (n_22), .Y (n_26));
  NOR2X1 g1058__5122(.A (n_17), .B (n_16), .Y (n_24));
  NAND2BXL g1059__8246(.AN (n_14), .B (n_21), .Y (n_23));
  NAND2X1 g1060__7098(.A (X1[1]), .B (n_16), .Y (n_25));
  OAI21XL g1061__6131(.A0 (X1[3]), .A1 (n_12), .B0 (X1[4]), .Y (n_21));
  OR2XL g1062__1881(.A (n_6), .B (n_18), .Y (n_22));
  NOR3BX1 g1063__5115(.AN (n_11), .B (n_0), .C (n_6), .Y (n_20));
  OAI2BB1X1 g1064__7482(.A0N (X1[0]), .A1N (n_14), .B0 (n_13), .Y
       (n_19));
  DFFHQX1 \XPower2_reg[2] (.CK (clk), .D (n_5), .Q (XPower2[2]));
  AND2X1 g1066__4733(.A (n_11), .B (n_1), .Y (n_18));
  NOR2BX1 g1067__6161(.AN (n_8), .B (n_6), .Y (n_15));
  NOR2X1 g1068__9315(.A (n_1), .B (n_7), .Y (n_17));
  AOI21X1 g1069__9945(.A0 (X1[3]), .A1 (X1[4]), .B0 (n_9), .Y (n_16));
  DFFQXL \X2_reg[7] (.CK (clk), .D (X1[7]), .Q (X2[7]));
  DFFHQX1 \X2_reg[4] (.CK (clk), .D (X1[4]), .Q (X2[4]));
  DFFHQX1 \X2_reg[5] (.CK (clk), .D (X1[5]), .Q (X2[5]));
  DFFQXL \X2_reg[6] (.CK (clk), .D (X1[6]), .Q (X2[6]));
  DFFHQX1 \X2_reg[2] (.CK (clk), .D (X1[2]), .Q (X2[2]));
  DFFHQX1 \X2_reg[3] (.CK (clk), .D (X1[3]), .Q (X2[3]));
  DFFHQX1 \X2_reg[1] (.CK (clk), .D (X1[1]), .Q (X2[1]));
  DFFHQX1 \X2_reg[0] (.CK (clk), .D (X1[0]), .Q (X2[0]));
  NOR2X1 g1078__2883(.A (n_3), .B (n_1), .Y (n_14));
  INVX1 g1079(.A (n_9), .Y (n_10));
  NOR2XL g1080__2346(.A (n_2), .B (X1[0]), .Y (n_5));
  NOR2X1 g1081__1666(.A (X1[1]), .B (n_3), .Y (n_13));
  NAND2XL g1082__7410(.A (X1[6]), .B (X1[0]), .Y (n_4));
  NOR2X1 g1083__6417(.A (X1[0]), .B (n_3), .Y (n_12));
  NAND2X1 g1084__5477(.A (X1[1]), .B (X1[2]), .Y (n_11));
  NOR2X1 g1085__2398(.A (X1[3]), .B (X1[4]), .Y (n_9));
  NAND2X1 g1086__5107(.A (X1[4]), .B (X1[0]), .Y (n_8));
  NAND2X1 g1087__6260(.A (X1[5]), .B (X1[0]), .Y (n_7));
  NOR2X1 g1088__4319(.A (X1[1]), .B (X1[2]), .Y (n_6));
  INVX1 g1089(.A (X1[2]), .Y (n_3));
  INVX1 g1090(.A (X1[1]), .Y (n_2));
  INVX1 g1091(.A (X1[3]), .Y (n_1));
  DFFHQX1 \XPower_reg[3] (.CK (clk), .D (n_50), .Q (XPower[3]));
  DFFHQX1 \XPower_reg[2] (.CK (clk), .D (n_51), .Q (XPower[2]));
  DFFQXL \X1_reg[6] (.CK (clk), .D (X[6]), .Q (X1[6]));
  DFFHQX1 \X1_reg[5] (.CK (clk), .D (X[5]), .Q (X1[5]));
  DFFHQX1 \X1_reg[4] (.CK (clk), .D (X[4]), .Q (X1[4]));
  DFFHQX1 \X1_reg[2] (.CK (clk), .D (X[2]), .Q (X1[2]));
  DFFHQX1 \X1_reg[1] (.CK (clk), .D (X[1]), .Q (X1[1]));
  DFFHQX1 \X1_reg[3] (.CK (clk), .D (X[3]), .Q (X1[3]));
  INVX1 g1100(.A (X1[0]), .Y (n_0));
  DFFHQX1 \XPower_reg[5] (.CK (clk), .D (n_48), .Q (XPower[5]));
  DFFHQX1 \XPower_reg[1] (.CK (clk), .D (n_52), .Q (XPower[1]));
  DFFHQX1 \XPower_reg[6] (.CK (clk), .D (n_47), .Q (XPower[6]));
  DFFQXL \X1_reg[7] (.CK (clk), .D (X[7]), .Q (X1[7]));
  DFFHQX1 \XPower_reg[7] (.CK (clk), .D (n_46), .Q (XPower[7]));
  DFFHQX1 \XPower_reg[0] (.CK (clk), .D (X2[0]), .Q (XPower[0]));
  DFFHQX1 \XPower_reg[4] (.CK (clk), .D (n_49), .Q (XPower[4]));
  DFFHQX1 \X1_reg[0] (.CK (clk), .D (X[0]), .Q (X1[0]));
  XNOR2X1 mul_20_24_g480__8428(.A (mul_20_24_n_63), .B
       (mul_20_24_n_66), .Y (n_46));
  ADDFX1 mul_20_24_g481__5526(.A (mul_20_24_n_55), .B (mul_20_24_n_59),
       .CI (mul_20_24_n_64), .CO (mul_20_24_n_66), .S (n_47));
  ADDFX1 mul_20_24_g482__6783(.A (mul_20_24_n_47), .B (mul_20_24_n_56),
       .CI (mul_20_24_n_61), .CO (mul_20_24_n_64), .S (n_48));
  XNOR2X1 mul_20_24_g483__3680(.A (mul_20_24_n_58), .B
       (mul_20_24_n_60), .Y (mul_20_24_n_63));
  ADDFX1 mul_20_24_g484__1617(.A (mul_20_24_n_30), .B (mul_20_24_n_53),
       .CI (mul_20_24_n_48), .CO (mul_20_24_n_61), .S (n_49));
  XNOR2X1 mul_20_24_g485__2802(.A (mul_20_24_n_57), .B
       (mul_20_24_n_52), .Y (mul_20_24_n_60));
  ADDFX1 mul_20_24_g486__1705(.A (mul_20_24_n_45), .B (mul_20_24_n_44),
       .CI (mul_20_24_n_51), .CO (mul_20_24_n_58), .S (mul_20_24_n_59));
  XNOR2X1 mul_20_24_g487__5122(.A (mul_20_24_n_42), .B
       (mul_20_24_n_50), .Y (mul_20_24_n_57));
  ADDFX1 mul_20_24_g488__8246(.A (mul_20_24_n_29), .B (mul_20_24_n_33),
       .CI (mul_20_24_n_46), .CO (mul_20_24_n_55), .S (mul_20_24_n_56));
  ADDFX1 mul_20_24_g489__7098(.A (mul_20_24_n_3), .B (mul_20_24_n_28),
       .CI (mul_20_24_n_34), .CO (mul_20_24_n_53), .S (n_50));
  XNOR2X1 mul_20_24_g490__6131(.A (mul_20_24_n_41), .B
       (mul_20_24_n_49), .Y (mul_20_24_n_52));
  ADDFX1 mul_20_24_g491__1881(.A (mul_20_24_n_4), .B (mul_20_24_n_31),
       .CI (mul_20_24_n_35), .CO (mul_20_24_n_50), .S (mul_20_24_n_51));
  XNOR2X1 mul_20_24_g492__5115(.A (mul_20_24_n_37), .B
       (mul_20_24_n_43), .Y (mul_20_24_n_49));
  ADDFX1 mul_20_24_g493__7482(.A (mul_20_24_n_14), .B (mul_20_24_n_15),
       .CI (mul_20_24_n_36), .CO (mul_20_24_n_47), .S (mul_20_24_n_48));
  ADDFX1 mul_20_24_g494__4733(.A (mul_20_24_n_1), .B (mul_20_24_n_0),
       .CI (mul_20_24_n_17), .CO (mul_20_24_n_45), .S (mul_20_24_n_46));
  ADDFX1 mul_20_24_g495__6161(.A (mul_20_24_n_2), .B (mul_20_24_n_16),
       .CI (mul_20_24_n_18), .CO (mul_20_24_n_43), .S (mul_20_24_n_44));
  XNOR2X1 mul_20_24_g496__9315(.A (mul_20_24_n_32), .B
       (mul_20_24_n_39), .Y (mul_20_24_n_42));
  XNOR2X1 mul_20_24_g497__9945(.A (mul_20_24_n_7), .B (mul_20_24_n_38),
       .Y (mul_20_24_n_41));
  AOI21X1 mul_20_24_g498__2883(.A0 (mul_20_24_n_27), .A1
       (mul_20_24_n_26), .B0 (mul_20_24_n_28), .Y (n_51));
  XNOR2X1 mul_20_24_g499__2346(.A (mul_20_24_n_20), .B (mul_20_24_n_8),
       .Y (mul_20_24_n_39));
  XNOR2X1 mul_20_24_g500__1666(.A (mul_20_24_n_19), .B (mul_20_24_n_9),
       .Y (mul_20_24_n_38));
  XNOR2X1 mul_20_24_g501__7410(.A (mul_20_24_n_6), .B (mul_20_24_n_5),
       .Y (mul_20_24_n_37));
  XOR2XL mul_20_24_g502__6417(.A (mul_20_24_n_22), .B (mul_20_24_n_11),
       .Y (mul_20_24_n_36));
  XOR2XL mul_20_24_g503__5477(.A (mul_20_24_n_25), .B (mul_20_24_n_24),
       .Y (mul_20_24_n_35));
  XOR2XL mul_20_24_g504__2398(.A (mul_20_24_n_10), .B (mul_20_24_n_12),
       .Y (mul_20_24_n_34));
  XOR2XL mul_20_24_g505__5107(.A (mul_20_24_n_13), .B (mul_20_24_n_23),
       .Y (mul_20_24_n_33));
  NOR2XL mul_20_24_g506__6260(.A (mul_20_24_n_25), .B (mul_20_24_n_24),
       .Y (mul_20_24_n_32));
  NOR2X1 mul_20_24_g507__4319(.A (mul_20_24_n_13), .B (mul_20_24_n_23),
       .Y (mul_20_24_n_31));
  NOR2X1 mul_20_24_g508__8428(.A (mul_20_24_n_12), .B (mul_20_24_n_10),
       .Y (mul_20_24_n_30));
  NOR2X1 mul_20_24_g509__5526(.A (mul_20_24_n_11), .B (mul_20_24_n_22),
       .Y (mul_20_24_n_29));
  NOR2X1 mul_20_24_g510__6783(.A (mul_20_24_n_27), .B (mul_20_24_n_26),
       .Y (mul_20_24_n_28));
  AND2XL mul_20_24_g511__3680(.A (X2[1]), .B (X2[0]), .Y (n_52));
  NAND2XL mul_20_24_g512__1617(.A (X2[5]), .B (XPower2[2]), .Y
       (mul_20_24_n_20));
  NAND2XL mul_20_24_g513__2802(.A (X2[2]), .B (XPower2[5]), .Y
       (mul_20_24_n_19));
  NAND2X1 mul_20_24_g514__1705(.A (X2[2]), .B (X2[0]), .Y
       (mul_20_24_n_27));
  NAND2X1 mul_20_24_g515__5122(.A (XPower2[2]), .B (X2[0]), .Y
       (mul_20_24_n_26));
  NAND2X1 mul_20_24_g516__8246(.A (X2[1]), .B (XPower2[5]), .Y
       (mul_20_24_n_25));
  AND2XL mul_20_24_g517__7098(.A (X2[6]), .B (X2[0]), .Y
       (mul_20_24_n_18));
  NAND2X1 mul_20_24_g518__6131(.A (XPower2[6]), .B (X2[0]), .Y
       (mul_20_24_n_24));
  NAND2X1 mul_20_24_g519__1881(.A (XPower2[5]), .B (X2[0]), .Y
       (mul_20_24_n_23));
  AND2XL mul_20_24_g520__5115(.A (X2[5]), .B (X2[0]), .Y
       (mul_20_24_n_17));
  NAND2X1 mul_20_24_g521__7482(.A (X2[1]), .B (XPower2[3]), .Y
       (mul_20_24_n_22));
  AND2XL mul_20_24_g522__4733(.A (X2[3]), .B (XPower2[3]), .Y
       (mul_20_24_n_16));
  AND2XL mul_20_24_g523__6161(.A (X2[4]), .B (X2[0]), .Y
       (mul_20_24_n_15));
  AND2XL mul_20_24_g524__9315(.A (X2[2]), .B (XPower2[2]), .Y
       (mul_20_24_n_14));
  NAND2X1 mul_20_24_g525__9945(.A (X2[4]), .B (XPower2[3]), .Y
       (mul_20_24_n_9));
  NAND2X1 mul_20_24_g526__2883(.A (X2[7]), .B (X2[0]), .Y
       (mul_20_24_n_8));
  NAND2X1 mul_20_24_g527__2346(.A (X2[3]), .B (XPower2[4]), .Y
       (mul_20_24_n_7));
  NAND2XL mul_20_24_g528__1666(.A (XPower2[6]), .B (X2[1]), .Y
       (mul_20_24_n_6));
  NAND2X1 mul_20_24_g529__7410(.A (XPower2[7]), .B (X2[0]), .Y
       (mul_20_24_n_5));
  NAND2X1 mul_20_24_g530__6417(.A (X2[1]), .B (XPower2[4]), .Y
       (mul_20_24_n_13));
  NAND2X1 mul_20_24_g531__5477(.A (XPower2[3]), .B (X2[0]), .Y
       (mul_20_24_n_12));
  NAND2X1 mul_20_24_g532__2398(.A (XPower2[4]), .B (X2[0]), .Y
       (mul_20_24_n_11));
  NAND2X1 mul_20_24_g533__5107(.A (X2[1]), .B (XPower2[2]), .Y
       (mul_20_24_n_10));
  AND2XL mul_20_24_g534__6260(.A (X2[2]), .B (XPower2[4]), .Y
       (mul_20_24_n_4));
  AND2XL mul_20_24_g535__4319(.A (X2[3]), .B (X2[0]), .Y
       (mul_20_24_n_3));
  AND2XL mul_20_24_g536__8428(.A (X2[4]), .B (XPower2[2]), .Y
       (mul_20_24_n_2));
  AND2XL mul_20_24_g537__5526(.A (X2[3]), .B (XPower2[2]), .Y
       (mul_20_24_n_1));
  AND2XL mul_20_24_g538__6783(.A (X2[2]), .B (XPower2[3]), .Y
       (mul_20_24_n_0));
endmodule

