
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point in_data[15] in_data[15] -type PI PI
add mapped point in_data[14] in_data[14] -type PI PI
add mapped point in_data[13] in_data[13] -type PI PI
add mapped point in_data[12] in_data[12] -type PI PI
add mapped point in_data[11] in_data[11] -type PI PI
add mapped point in_data[10] in_data[10] -type PI PI
add mapped point in_data[9] in_data[9] -type PI PI
add mapped point in_data[8] in_data[8] -type PI PI
add mapped point in_data[7] in_data[7] -type PI PI
add mapped point in_data[6] in_data[6] -type PI PI
add mapped point in_data[5] in_data[5] -type PI PI
add mapped point in_data[4] in_data[4] -type PI PI
add mapped point in_data[3] in_data[3] -type PI PI
add mapped point in_data[2] in_data[2] -type PI PI
add mapped point in_data[1] in_data[1] -type PI PI
add mapped point in_data[0] in_data[0] -type PI PI
add mapped point in_valid in_valid -type PI PI
add mapped point rom_data[15] rom_data[15] -type PI PI
add mapped point rom_data[14] rom_data[14] -type PI PI
add mapped point rom_data[13] rom_data[13] -type PI PI
add mapped point rom_data[12] rom_data[12] -type PI PI
add mapped point rom_data[11] rom_data[11] -type PI PI
add mapped point rom_data[10] rom_data[10] -type PI PI
add mapped point rom_data[9] rom_data[9] -type PI PI
add mapped point rom_data[8] rom_data[8] -type PI PI
add mapped point rom_data[7] rom_data[7] -type PI PI
add mapped point rom_data[6] rom_data[6] -type PI PI
add mapped point rom_data[5] rom_data[5] -type PI PI
add mapped point rom_data[4] rom_data[4] -type PI PI
add mapped point rom_data[3] rom_data[3] -type PI PI
add mapped point rom_data[2] rom_data[2] -type PI PI
add mapped point rom_data[1] rom_data[1] -type PI PI
add mapped point rom_data[0] rom_data[0] -type PI PI
add mapped point out_ready out_ready -type PI PI

//output ports
add mapped point in_ready in_ready -type PO PO
add mapped point rom_addr[2] rom_addr[2] -type PO PO
add mapped point rom_addr[1] rom_addr[1] -type PO PO
add mapped point rom_addr[0] rom_addr[0] -type PO PO
add mapped point out_data[34] out_data[34] -type PO PO
add mapped point out_data[33] out_data[33] -type PO PO
add mapped point out_data[32] out_data[32] -type PO PO
add mapped point out_data[31] out_data[31] -type PO PO
add mapped point out_data[30] out_data[30] -type PO PO
add mapped point out_data[29] out_data[29] -type PO PO
add mapped point out_data[28] out_data[28] -type PO PO
add mapped point out_data[27] out_data[27] -type PO PO
add mapped point out_data[26] out_data[26] -type PO PO
add mapped point out_data[25] out_data[25] -type PO PO
add mapped point out_data[24] out_data[24] -type PO PO
add mapped point out_data[23] out_data[23] -type PO PO
add mapped point out_data[22] out_data[22] -type PO PO
add mapped point out_data[21] out_data[21] -type PO PO
add mapped point out_data[20] out_data[20] -type PO PO
add mapped point out_data[19] out_data[19] -type PO PO
add mapped point out_data[18] out_data[18] -type PO PO
add mapped point out_data[17] out_data[17] -type PO PO
add mapped point out_data[16] out_data[16] -type PO PO
add mapped point out_data[15] out_data[15] -type PO PO
add mapped point out_data[14] out_data[14] -type PO PO
add mapped point out_data[13] out_data[13] -type PO PO
add mapped point out_data[12] out_data[12] -type PO PO
add mapped point out_data[11] out_data[11] -type PO PO
add mapped point out_data[10] out_data[10] -type PO PO
add mapped point out_data[9] out_data[9] -type PO PO
add mapped point out_data[8] out_data[8] -type PO PO
add mapped point out_data[7] out_data[7] -type PO PO
add mapped point out_data[6] out_data[6] -type PO PO
add mapped point out_data[5] out_data[5] -type PO PO
add mapped point out_data[4] out_data[4] -type PO PO
add mapped point out_data[3] out_data[3] -type PO PO
add mapped point out_data[2] out_data[2] -type PO PO
add mapped point out_data[1] out_data[1] -type PO PO
add mapped point out_data[0] out_data[0] -type PO PO
add mapped point out_valid out_valid -type PO PO

//inout ports




//Sequential Pins
add mapped point fsm_i/fill_count[0]/q fsm_i/fill_count_reg[0]/Q -type DFF DFF
add mapped point fsm_i/fill_count[1]/q fsm_i/fill_count_reg[1]/Q -type DFF DFF
add mapped point fsm_i/state[0]/q fsm_i/state_reg[0]/Q -type DFF DFF
add mapped point fsm_i/fill_count[2]/q fsm_i/fill_count_reg[2]/Q -type DFF DFF
add mapped point fsm_i/term_count[0]/q fsm_i/term_count_reg[0]/Q -type DFF DFF
add mapped point fsm_i/term_count[1]/q fsm_i/term_count_reg[1]/Q -type DFF DFF
add mapped point fsm_i/term_count[2]/q fsm_i/term_count_reg[2]/Q -type DFF DFF
add mapped point fsm_i/state[2]/q fsm_i/state_reg[2]/Q -type DFF DFF
add mapped point fsm_i/state[1]/q fsm_i/state_reg[1]/Q -type DFF DFF
add mapped point mac_i/done/q mac_i_done_reg/Q -type DFF DFF
add mapped point buffer_i/mem[0][0]/q buffer_i_mem_reg[0][0]/Q -type DFF DFF
add mapped point buffer_i/mem[0][1]/q buffer_i_mem_reg[0][1]/Q -type DFF DFF
add mapped point buffer_i/mem[0][2]/q buffer_i_mem_reg[0][2]/Q -type DFF DFF
add mapped point buffer_i/mem[0][3]/q buffer_i_mem_reg[0][3]/Q -type DFF DFF
add mapped point buffer_i/mem[0][4]/q buffer_i_mem_reg[0][4]/Q -type DFF DFF
add mapped point buffer_i/mem[0][5]/q buffer_i_mem_reg[0][5]/Q -type DFF DFF
add mapped point buffer_i/mem[0][6]/q buffer_i_mem_reg[0][6]/Q -type DFF DFF
add mapped point buffer_i/mem[0][7]/q buffer_i_mem_reg[0][7]/Q -type DFF DFF
add mapped point buffer_i/mem[0][8]/q buffer_i_mem_reg[0][8]/Q -type DFF DFF
add mapped point buffer_i/mem[0][9]/q buffer_i_mem_reg[0][9]/Q -type DFF DFF
add mapped point buffer_i/mem[0][10]/q buffer_i_mem_reg[0][10]/Q -type DFF DFF
add mapped point buffer_i/mem[0][11]/q buffer_i_mem_reg[0][11]/Q -type DFF DFF
add mapped point buffer_i/mem[0][12]/q buffer_i_mem_reg[0][12]/Q -type DFF DFF
add mapped point buffer_i/mem[0][13]/q buffer_i_mem_reg[0][13]/Q -type DFF DFF
add mapped point buffer_i/mem[0][14]/q buffer_i_mem_reg[0][14]/Q -type DFF DFF
add mapped point buffer_i/mem[0][15]/q buffer_i_mem_reg[0][15]/Q -type DFF DFF
add mapped point buffer_i/mem[1][0]/q buffer_i_mem_reg[1][0]/Q -type DFF DFF
add mapped point buffer_i/mem[1][1]/q buffer_i_mem_reg[1][1]/Q -type DFF DFF
add mapped point buffer_i/mem[1][2]/q buffer_i_mem_reg[1][2]/Q -type DFF DFF
add mapped point buffer_i/mem[1][3]/q buffer_i_mem_reg[1][3]/Q -type DFF DFF
add mapped point buffer_i/mem[1][4]/q buffer_i_mem_reg[1][4]/Q -type DFF DFF
add mapped point buffer_i/mem[1][5]/q buffer_i_mem_reg[1][5]/Q -type DFF DFF
add mapped point buffer_i/mem[1][6]/q buffer_i_mem_reg[1][6]/Q -type DFF DFF
add mapped point buffer_i/mem[1][7]/q buffer_i_mem_reg[1][7]/Q -type DFF DFF
add mapped point buffer_i/mem[1][8]/q buffer_i_mem_reg[1][8]/Q -type DFF DFF
add mapped point buffer_i/mem[1][9]/q buffer_i_mem_reg[1][9]/Q -type DFF DFF
add mapped point buffer_i/mem[1][10]/q buffer_i_mem_reg[1][10]/Q -type DFF DFF
add mapped point buffer_i/mem[1][11]/q buffer_i_mem_reg[1][11]/Q -type DFF DFF
add mapped point buffer_i/mem[1][12]/q buffer_i_mem_reg[1][12]/Q -type DFF DFF
add mapped point buffer_i/mem[1][13]/q buffer_i_mem_reg[1][13]/Q -type DFF DFF
add mapped point buffer_i/mem[1][14]/q buffer_i_mem_reg[1][14]/Q -type DFF DFF
add mapped point buffer_i/mem[1][15]/q buffer_i_mem_reg[1][15]/Q -type DFF DFF
add mapped point buffer_i/mem[2][0]/q buffer_i_mem_reg[2][0]/Q -type DFF DFF
add mapped point buffer_i/mem[2][1]/q buffer_i_mem_reg[2][1]/Q -type DFF DFF
add mapped point buffer_i/mem[2][2]/q buffer_i_mem_reg[2][2]/Q -type DFF DFF
add mapped point buffer_i/mem[2][3]/q buffer_i_mem_reg[2][3]/Q -type DFF DFF
add mapped point buffer_i/mem[2][4]/q buffer_i_mem_reg[2][4]/Q -type DFF DFF
add mapped point buffer_i/mem[2][5]/q buffer_i_mem_reg[2][5]/Q -type DFF DFF
add mapped point buffer_i/mem[2][6]/q buffer_i_mem_reg[2][6]/Q -type DFF DFF
add mapped point buffer_i/mem[2][7]/q buffer_i_mem_reg[2][7]/Q -type DFF DFF
add mapped point buffer_i/mem[2][8]/q buffer_i_mem_reg[2][8]/Q -type DFF DFF
add mapped point buffer_i/mem[2][9]/q buffer_i_mem_reg[2][9]/Q -type DFF DFF
add mapped point buffer_i/mem[2][10]/q buffer_i_mem_reg[2][10]/Q -type DFF DFF
add mapped point buffer_i/mem[2][11]/q buffer_i_mem_reg[2][11]/Q -type DFF DFF
add mapped point buffer_i/mem[2][12]/q buffer_i_mem_reg[2][12]/Q -type DFF DFF
add mapped point buffer_i/mem[2][13]/q buffer_i_mem_reg[2][13]/Q -type DFF DFF
add mapped point buffer_i/mem[2][14]/q buffer_i_mem_reg[2][14]/Q -type DFF DFF
add mapped point buffer_i/mem[2][15]/q buffer_i_mem_reg[2][15]/Q -type DFF DFF
add mapped point buffer_i/mem[3][0]/q buffer_i_mem_reg[3][0]/Q -type DFF DFF
add mapped point buffer_i/mem[3][1]/q buffer_i_mem_reg[3][1]/Q -type DFF DFF
add mapped point buffer_i/mem[3][2]/q buffer_i_mem_reg[3][2]/Q -type DFF DFF
add mapped point buffer_i/mem[3][3]/q buffer_i_mem_reg[3][3]/Q -type DFF DFF
add mapped point buffer_i/mem[3][4]/q buffer_i_mem_reg[3][4]/Q -type DFF DFF
add mapped point buffer_i/mem[3][5]/q buffer_i_mem_reg[3][5]/Q -type DFF DFF
add mapped point buffer_i/mem[3][6]/q buffer_i_mem_reg[3][6]/Q -type DFF DFF
add mapped point buffer_i/mem[3][7]/q buffer_i_mem_reg[3][7]/Q -type DFF DFF
add mapped point buffer_i/mem[3][8]/q buffer_i_mem_reg[3][8]/Q -type DFF DFF
add mapped point buffer_i/mem[3][9]/q buffer_i_mem_reg[3][9]/Q -type DFF DFF
add mapped point buffer_i/mem[3][10]/q buffer_i_mem_reg[3][10]/Q -type DFF DFF
add mapped point buffer_i/mem[3][11]/q buffer_i_mem_reg[3][11]/Q -type DFF DFF
add mapped point buffer_i/mem[3][12]/q buffer_i_mem_reg[3][12]/Q -type DFF DFF
add mapped point buffer_i/mem[3][13]/q buffer_i_mem_reg[3][13]/Q -type DFF DFF
add mapped point buffer_i/mem[3][14]/q buffer_i_mem_reg[3][14]/Q -type DFF DFF
add mapped point buffer_i/mem[3][15]/q buffer_i_mem_reg[3][15]/Q -type DFF DFF
add mapped point buffer_i/mem[4][0]/q buffer_i_mem_reg[4][0]/Q -type DFF DFF
add mapped point buffer_i/mem[4][1]/q buffer_i_mem_reg[4][1]/Q -type DFF DFF
add mapped point buffer_i/mem[4][2]/q buffer_i_mem_reg[4][2]/Q -type DFF DFF
add mapped point buffer_i/mem[4][3]/q buffer_i_mem_reg[4][3]/Q -type DFF DFF
add mapped point buffer_i/mem[4][4]/q buffer_i_mem_reg[4][4]/Q -type DFF DFF
add mapped point buffer_i/mem[4][5]/q buffer_i_mem_reg[4][5]/Q -type DFF DFF
add mapped point buffer_i/mem[4][6]/q buffer_i_mem_reg[4][6]/Q -type DFF DFF
add mapped point buffer_i/mem[4][7]/q buffer_i_mem_reg[4][7]/Q -type DFF DFF
add mapped point buffer_i/mem[4][8]/q buffer_i_mem_reg[4][8]/Q -type DFF DFF
add mapped point buffer_i/mem[4][9]/q buffer_i_mem_reg[4][9]/Q -type DFF DFF
add mapped point buffer_i/mem[4][10]/q buffer_i_mem_reg[4][10]/Q -type DFF DFF
add mapped point buffer_i/mem[4][11]/q buffer_i_mem_reg[4][11]/Q -type DFF DFF
add mapped point buffer_i/mem[4][12]/q buffer_i_mem_reg[4][12]/Q -type DFF DFF
add mapped point buffer_i/mem[4][13]/q buffer_i_mem_reg[4][13]/Q -type DFF DFF
add mapped point buffer_i/mem[4][14]/q buffer_i_mem_reg[4][14]/Q -type DFF DFF
add mapped point buffer_i/mem[4][15]/q buffer_i_mem_reg[4][15]/Q -type DFF DFF
add mapped point buffer_i/mem[5][0]/q buffer_i_mem_reg[5][0]/Q -type DFF DFF
add mapped point buffer_i/mem[5][1]/q buffer_i_mem_reg[5][1]/Q -type DFF DFF
add mapped point buffer_i/mem[5][2]/q buffer_i_mem_reg[5][2]/Q -type DFF DFF
add mapped point buffer_i/mem[5][3]/q buffer_i_mem_reg[5][3]/Q -type DFF DFF
add mapped point buffer_i/mem[5][4]/q buffer_i_mem_reg[5][4]/Q -type DFF DFF
add mapped point buffer_i/mem[5][5]/q buffer_i_mem_reg[5][5]/Q -type DFF DFF
add mapped point buffer_i/mem[5][6]/q buffer_i_mem_reg[5][6]/Q -type DFF DFF
add mapped point buffer_i/mem[5][7]/q buffer_i_mem_reg[5][7]/Q -type DFF DFF
add mapped point buffer_i/mem[5][8]/q buffer_i_mem_reg[5][8]/Q -type DFF DFF
add mapped point buffer_i/mem[5][9]/q buffer_i_mem_reg[5][9]/Q -type DFF DFF
add mapped point buffer_i/mem[5][10]/q buffer_i_mem_reg[5][10]/Q -type DFF DFF
add mapped point buffer_i/mem[5][11]/q buffer_i_mem_reg[5][11]/Q -type DFF DFF
add mapped point buffer_i/mem[5][12]/q buffer_i_mem_reg[5][12]/Q -type DFF DFF
add mapped point buffer_i/mem[5][13]/q buffer_i_mem_reg[5][13]/Q -type DFF DFF
add mapped point buffer_i/mem[5][14]/q buffer_i_mem_reg[5][14]/Q -type DFF DFF
add mapped point buffer_i/mem[5][15]/q buffer_i_mem_reg[5][15]/Q -type DFF DFF
add mapped point buffer_i/mem[6][0]/q buffer_i_mem_reg[6][0]/Q -type DFF DFF
add mapped point buffer_i/mem[6][1]/q buffer_i_mem_reg[6][1]/Q -type DFF DFF
add mapped point buffer_i/mem[6][2]/q buffer_i_mem_reg[6][2]/Q -type DFF DFF
add mapped point buffer_i/mem[6][3]/q buffer_i_mem_reg[6][3]/Q -type DFF DFF
add mapped point buffer_i/mem[6][4]/q buffer_i_mem_reg[6][4]/Q -type DFF DFF
add mapped point buffer_i/mem[6][5]/q buffer_i_mem_reg[6][5]/Q -type DFF DFF
add mapped point buffer_i/mem[6][6]/q buffer_i_mem_reg[6][6]/Q -type DFF DFF
add mapped point buffer_i/mem[6][7]/q buffer_i_mem_reg[6][7]/Q -type DFF DFF
add mapped point buffer_i/mem[6][8]/q buffer_i_mem_reg[6][8]/Q -type DFF DFF
add mapped point buffer_i/mem[6][9]/q buffer_i_mem_reg[6][9]/Q -type DFF DFF
add mapped point buffer_i/mem[6][10]/q buffer_i_mem_reg[6][10]/Q -type DFF DFF
add mapped point buffer_i/mem[6][11]/q buffer_i_mem_reg[6][11]/Q -type DFF DFF
add mapped point buffer_i/mem[6][12]/q buffer_i_mem_reg[6][12]/Q -type DFF DFF
add mapped point buffer_i/mem[6][13]/q buffer_i_mem_reg[6][13]/Q -type DFF DFF
add mapped point buffer_i/mem[6][14]/q buffer_i_mem_reg[6][14]/Q -type DFF DFF
add mapped point buffer_i/mem[6][15]/q buffer_i_mem_reg[6][15]/Q -type DFF DFF
add mapped point buffer_i/mem[7][0]/q buffer_i_mem_reg[7][0]/Q -type DFF DFF
add mapped point buffer_i/mem[7][1]/q buffer_i_mem_reg[7][1]/Q -type DFF DFF
add mapped point buffer_i/mem[7][2]/q buffer_i_mem_reg[7][2]/Q -type DFF DFF
add mapped point buffer_i/mem[7][3]/q buffer_i_mem_reg[7][3]/Q -type DFF DFF
add mapped point buffer_i/mem[7][4]/q buffer_i_mem_reg[7][4]/Q -type DFF DFF
add mapped point buffer_i/mem[7][5]/q buffer_i_mem_reg[7][5]/Q -type DFF DFF
add mapped point buffer_i/mem[7][6]/q buffer_i_mem_reg[7][6]/Q -type DFF DFF
add mapped point buffer_i/mem[7][7]/q buffer_i_mem_reg[7][7]/Q -type DFF DFF
add mapped point buffer_i/mem[7][8]/q buffer_i_mem_reg[7][8]/Q -type DFF DFF
add mapped point buffer_i/mem[7][9]/q buffer_i_mem_reg[7][9]/Q -type DFF DFF
add mapped point buffer_i/mem[7][10]/q buffer_i_mem_reg[7][10]/Q -type DFF DFF
add mapped point buffer_i/mem[7][11]/q buffer_i_mem_reg[7][11]/Q -type DFF DFF
add mapped point buffer_i/mem[7][12]/q buffer_i_mem_reg[7][12]/Q -type DFF DFF
add mapped point buffer_i/mem[7][13]/q buffer_i_mem_reg[7][13]/Q -type DFF DFF
add mapped point buffer_i/mem[7][14]/q buffer_i_mem_reg[7][14]/Q -type DFF DFF
add mapped point buffer_i/mem[7][15]/q buffer_i_mem_reg[7][15]/Q -type DFF DFF
add mapped point buffer_i/wr_ptr[0]/q buffer_i_wr_ptr_reg[0]/Q -type DFF DFF
add mapped point mac_i/busy/q mac_i_busy_reg/Q -type DFF DFF
add mapped point mac_i/count[0]/q mac_i_count_reg[0]/Q -type DFF DFF
add mapped point mac_i/count[1]/q mac_i_count_reg[1]/Q -type DFF DFF
add mapped point mac_i/count[2]/q mac_i_count_reg[2]/Q -type DFF DFF
add mapped point mac_i/result[0]/q mac_i_result_reg[0]/Q -type DFF DFF
add mapped point mac_i/result[1]/q mac_i_result_reg[1]/Q -type DFF DFF
add mapped point mac_i/result[2]/q mac_i_result_reg[2]/Q -type DFF DFF
add mapped point mac_i/result[3]/q mac_i_result_reg[3]/Q -type DFF DFF
add mapped point mac_i/result[4]/q mac_i_result_reg[4]/Q -type DFF DFF
add mapped point mac_i/result[5]/q mac_i_result_reg[5]/Q -type DFF DFF
add mapped point mac_i/result[6]/q mac_i_result_reg[6]/Q -type DFF DFF
add mapped point mac_i/result[7]/q mac_i_result_reg[7]/Q -type DFF DFF
add mapped point mac_i/result[8]/q mac_i_result_reg[8]/Q -type DFF DFF
add mapped point mac_i/result[9]/q mac_i_result_reg[9]/Q -type DFF DFF
add mapped point mac_i/result[10]/q mac_i_result_reg[10]/Q -type DFF DFF
add mapped point mac_i/result[11]/q mac_i_result_reg[11]/Q -type DFF DFF
add mapped point mac_i/result[12]/q mac_i_result_reg[12]/Q -type DFF DFF
add mapped point mac_i/result[13]/q mac_i_result_reg[13]/Q -type DFF DFF
add mapped point mac_i/result[14]/q mac_i_result_reg[14]/Q -type DFF DFF
add mapped point mac_i/result[15]/q mac_i_result_reg[15]/Q -type DFF DFF
add mapped point mac_i/result[16]/q mac_i_result_reg[16]/Q -type DFF DFF
add mapped point mac_i/result[17]/q mac_i_result_reg[17]/Q -type DFF DFF
add mapped point mac_i/result[18]/q mac_i_result_reg[18]/Q -type DFF DFF
add mapped point mac_i/result[19]/q mac_i_result_reg[19]/Q -type DFF DFF
add mapped point mac_i/result[20]/q mac_i_result_reg[20]/Q -type DFF DFF
add mapped point mac_i/result[21]/q mac_i_result_reg[21]/Q -type DFF DFF
add mapped point mac_i/result[22]/q mac_i_result_reg[22]/Q -type DFF DFF
add mapped point mac_i/result[23]/q mac_i_result_reg[23]/Q -type DFF DFF
add mapped point mac_i/result[24]/q mac_i_result_reg[24]/Q -type DFF DFF
add mapped point mac_i/result[25]/q mac_i_result_reg[25]/Q -type DFF DFF
add mapped point mac_i/result[26]/q mac_i_result_reg[26]/Q -type DFF DFF
add mapped point mac_i/result[27]/q mac_i_result_reg[27]/Q -type DFF DFF
add mapped point mac_i/result[28]/q mac_i_result_reg[28]/Q -type DFF DFF
add mapped point mac_i/result[29]/q mac_i_result_reg[29]/Q -type DFF DFF
add mapped point mac_i/result[30]/q mac_i_result_reg[30]/Q -type DFF DFF
add mapped point mac_i/result[31]/q mac_i_result_reg[31]/Q -type DFF DFF
add mapped point mac_i/result[32]/q mac_i_result_reg[32]/Q -type DFF DFF
add mapped point mac_i/result[33]/q mac_i_result_reg[33]/Q -type DFF DFF
add mapped point mac_i/result[34]/q mac_i_result_reg[34]/Q -type DFF DFF
add mapped point out_data[0]/q out_data_reg[0]/Q -type DFF DFF
add mapped point out_data[1]/q out_data_reg[1]/Q -type DFF DFF
add mapped point out_data[2]/q out_data_reg[2]/Q -type DFF DFF
add mapped point out_data[3]/q out_data_reg[3]/Q -type DFF DFF
add mapped point out_data[4]/q out_data_reg[4]/Q -type DFF DFF
add mapped point out_data[5]/q out_data_reg[5]/Q -type DFF DFF
add mapped point out_data[6]/q out_data_reg[6]/Q -type DFF DFF
add mapped point out_data[7]/q out_data_reg[7]/Q -type DFF DFF
add mapped point out_data[8]/q out_data_reg[8]/Q -type DFF DFF
add mapped point out_data[9]/q out_data_reg[9]/Q -type DFF DFF
add mapped point out_data[10]/q out_data_reg[10]/Q -type DFF DFF
add mapped point out_data[11]/q out_data_reg[11]/Q -type DFF DFF
add mapped point out_data[12]/q out_data_reg[12]/Q -type DFF DFF
add mapped point out_data[13]/q out_data_reg[13]/Q -type DFF DFF
add mapped point out_data[14]/q out_data_reg[14]/Q -type DFF DFF
add mapped point out_data[15]/q out_data_reg[15]/Q -type DFF DFF
add mapped point out_data[16]/q out_data_reg[16]/Q -type DFF DFF
add mapped point out_data[17]/q out_data_reg[17]/Q -type DFF DFF
add mapped point out_data[18]/q out_data_reg[18]/Q -type DFF DFF
add mapped point out_data[19]/q out_data_reg[19]/Q -type DFF DFF
add mapped point out_data[20]/q out_data_reg[20]/Q -type DFF DFF
add mapped point out_data[21]/q out_data_reg[21]/Q -type DFF DFF
add mapped point out_data[22]/q out_data_reg[22]/Q -type DFF DFF
add mapped point out_data[23]/q out_data_reg[23]/Q -type DFF DFF
add mapped point out_data[24]/q out_data_reg[24]/Q -type DFF DFF
add mapped point out_data[25]/q out_data_reg[25]/Q -type DFF DFF
add mapped point out_data[26]/q out_data_reg[26]/Q -type DFF DFF
add mapped point out_data[27]/q out_data_reg[27]/Q -type DFF DFF
add mapped point out_data[28]/q out_data_reg[28]/Q -type DFF DFF
add mapped point out_data[29]/q out_data_reg[29]/Q -type DFF DFF
add mapped point out_data[30]/q out_data_reg[30]/Q -type DFF DFF
add mapped point out_data[31]/q out_data_reg[31]/Q -type DFF DFF
add mapped point out_data[32]/q out_data_reg[32]/Q -type DFF DFF
add mapped point out_data[33]/q out_data_reg[33]/Q -type DFF DFF
add mapped point out_data[34]/q out_data_reg[34]/Q -type DFF DFF
add mapped point buffer_i/wr_ptr[1]/q buffer_i_wr_ptr_reg[1]/Q -type DFF DFF
add mapped point buffer_i/wr_ptr[2]/q buffer_i_wr_ptr_reg[2]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
