
//input ports
add mapped point ReadEn_in ReadEn_in -type PI PI
add mapped point RClk RClk -type PI PI
add mapped point Data_in[7] Data_in[7] -type PI PI
add mapped point Data_in[6] Data_in[6] -type PI PI
add mapped point Data_in[5] Data_in[5] -type PI PI
add mapped point Data_in[4] Data_in[4] -type PI PI
add mapped point Data_in[3] Data_in[3] -type PI PI
add mapped point Data_in[2] Data_in[2] -type PI PI
add mapped point Data_in[1] Data_in[1] -type PI PI
add mapped point Data_in[0] Data_in[0] -type PI PI
add mapped point WriteEn_in WriteEn_in -type PI PI
add mapped point WClk WClk -type PI PI
add mapped point Clear_in Clear_in -type PI PI

//output ports
add mapped point Data_out[7] Data_out[7] -type PO PO
add mapped point Data_out[6] Data_out[6] -type PO PO
add mapped point Data_out[5] Data_out[5] -type PO PO
add mapped point Data_out[4] Data_out[4] -type PO PO
add mapped point Data_out[3] Data_out[3] -type PO PO
add mapped point Data_out[2] Data_out[2] -type PO PO
add mapped point Data_out[1] Data_out[1] -type PO PO
add mapped point Data_out[0] Data_out[0] -type PO PO
add mapped point Empty_out Empty_out -type PO PO
add mapped point Full_out Full_out -type PO PO

//inout ports




//Sequential Pins
add mapped point GrayCounter_pRd/BinaryCount[3]/q GrayCounter_pRd/BinaryCount_reg[3]/Q -type DFF DFF
add mapped point GrayCounter_pRd/BinaryCount[4]/q GrayCounter_pRd/BinaryCount_reg[4]/Q -type DFF DFF
add mapped point GrayCounter_pRd/BinaryCount[2]/q GrayCounter_pRd/BinaryCount_reg[2]/Q -type DFF DFF
add mapped point GrayCounter_pRd/BinaryCount[1]/q GrayCounter_pRd/BinaryCount_reg[1]/Q -type DFF DFF
add mapped point GrayCounter_pRd/GrayCount_out[1]/q GrayCounter_pRd/GrayCount_out_reg[1]/Q -type DFF DFF
add mapped point GrayCounter_pRd/GrayCount_out[2]/q GrayCounter_pRd/GrayCount_out_reg[2]/Q -type DFF DFF
add mapped point GrayCounter_pRd/GrayCount_out[3]/q GrayCounter_pRd/GrayCount_out_reg[3]/Q -type DFF DFF
add mapped point GrayCounter_pRd/GrayCount_out[4]/q GrayCounter_pRd/GrayCount_out_reg[4]/Q -type DFF DFF
add mapped point GrayCounter_pRd/BinaryCount[0]/q GrayCounter_pRd/BinaryCount_reg[0]/Q -type DFF DFF
add mapped point GrayCounter_pWr/BinaryCount[3]/q GrayCounter_pWr/BinaryCount_reg[3]/Q -type DFF DFF
add mapped point GrayCounter_pWr/BinaryCount[4]/q GrayCounter_pWr/BinaryCount_reg[4]/Q -type DFF DFF
add mapped point GrayCounter_pWr/BinaryCount[2]/q GrayCounter_pWr/BinaryCount_reg[2]/Q -type DFF DFF
add mapped point GrayCounter_pWr/BinaryCount[1]/q GrayCounter_pWr/BinaryCount_reg[1]/Q -type DFF DFF
add mapped point GrayCounter_pWr/GrayCount_out[1]/q GrayCounter_pWr/GrayCount_out_reg[1]/Q -type DFF DFF
add mapped point GrayCounter_pWr/GrayCount_out[2]/q GrayCounter_pWr/GrayCount_out_reg[2]/Q -type DFF DFF
add mapped point GrayCounter_pWr/GrayCount_out[3]/q GrayCounter_pWr/GrayCount_out_reg[3]/Q -type DFF DFF
add mapped point GrayCounter_pWr/GrayCount_out[4]/q GrayCounter_pWr/GrayCount_out_reg[4]/Q -type DFF DFF
add mapped point GrayCounter_pWr/BinaryCount[0]/q GrayCounter_pWr/BinaryCount_reg[0]/Q -type DFF DFF
add mapped point Next_Write_addr_2[1]/q Next_Write_addr_2_reg[1]/Q -type DFF DFF
add mapped point Next_Write_addr_2[2]/q Next_Write_addr_2_reg[2]/Q -type DFF DFF
add mapped point Next_Write_addr_2[4]/q Next_Write_addr_2_reg[4]/Q -type DFF DFF
add mapped point Next_Read_addr_2[4]/q Next_Read_addr_2_reg[4]/Q -type DFF DFF
add mapped point Next_Read_addr_2[3]/q Next_Read_addr_2_reg[3]/Q -type DFF DFF
add mapped point Next_Read_addr_2[2]/q Next_Read_addr_2_reg[2]/Q -type DFF DFF
add mapped point Next_Write_addr_2[0]/q Next_Write_addr_2_reg[0]/Q -type DFF DFF
add mapped point Next_Write_addr_2[3]/q Next_Write_addr_2_reg[3]/Q -type DFF DFF
add mapped point Next_Read_addr_2[1]/q Next_Read_addr_2_reg[1]/Q -type DFF DFF
add mapped point Next_Read_addr_2[0]/q Next_Read_addr_2_reg[0]/Q -type DFF DFF
add mapped point Next_Read_addr_1[2]/q Next_Read_addr_1_reg[2]/Q -type DFF DFF
add mapped point Next_Read_addr_1[1]/q Next_Read_addr_1_reg[1]/Q -type DFF DFF
add mapped point Next_Read_addr_1[0]/q Next_Read_addr_1_reg[0]/Q -type DFF DFF
add mapped point Next_Read_addr_1[3]/q Next_Read_addr_1_reg[3]/Q -type DFF DFF
add mapped point Next_Read_addr_1[4]/q Next_Read_addr_1_reg[4]/Q -type DFF DFF
add mapped point Next_Write_addr_1[2]/q Next_Write_addr_1_reg[2]/Q -type DFF DFF
add mapped point Next_Write_addr_1[1]/q Next_Write_addr_1_reg[1]/Q -type DFF DFF
add mapped point Next_Write_addr_1[0]/q Next_Write_addr_1_reg[0]/Q -type DFF DFF
add mapped point Next_Write_addr_1[3]/q Next_Write_addr_1_reg[3]/Q -type DFF DFF
add mapped point Next_Write_addr_1[4]/q Next_Write_addr_1_reg[4]/Q -type DFF DFF
add mapped point Data_out[0]/q Data_out_reg[0]/Q -type DFF DFF
add mapped point Data_out[1]/q Data_out_reg[1]/Q -type DFF DFF
add mapped point Data_out[2]/q Data_out_reg[2]/Q -type DFF DFF
add mapped point Data_out[3]/q Data_out_reg[3]/Q -type DFF DFF
add mapped point Data_out[4]/q Data_out_reg[4]/Q -type DFF DFF
add mapped point Data_out[5]/q Data_out_reg[5]/Q -type DFF DFF
add mapped point Data_out[6]/q Data_out_reg[6]/Q -type DFF DFF
add mapped point Data_out[7]/q Data_out_reg[7]/Q -type DFF DFF
add mapped point Empty_out/q Empty_out_reg/Q -type DFF DFF
add mapped point Full_out/q Full_out_reg/Q -type DFF DFF
add mapped point Mem[0][0]/q Mem_reg[0][0]/Q -type DFF DFF
add mapped point Mem[0][1]/q Mem_reg[0][1]/Q -type DFF DFF
add mapped point Mem[0][2]/q Mem_reg[0][2]/Q -type DFF DFF
add mapped point Mem[0][3]/q Mem_reg[0][3]/Q -type DFF DFF
add mapped point Mem[0][4]/q Mem_reg[0][4]/Q -type DFF DFF
add mapped point Mem[0][5]/q Mem_reg[0][5]/Q -type DFF DFF
add mapped point Mem[0][6]/q Mem_reg[0][6]/Q -type DFF DFF
add mapped point Mem[0][7]/q Mem_reg[0][7]/Q -type DFF DFF
add mapped point Mem[1][0]/q Mem_reg[1][0]/Q -type DFF DFF
add mapped point Mem[1][1]/q Mem_reg[1][1]/Q -type DFF DFF
add mapped point Mem[1][2]/q Mem_reg[1][2]/Q -type DFF DFF
add mapped point Mem[1][3]/q Mem_reg[1][3]/Q -type DFF DFF
add mapped point Mem[1][4]/q Mem_reg[1][4]/Q -type DFF DFF
add mapped point Mem[1][5]/q Mem_reg[1][5]/Q -type DFF DFF
add mapped point Mem[1][6]/q Mem_reg[1][6]/Q -type DFF DFF
add mapped point Mem[1][7]/q Mem_reg[1][7]/Q -type DFF DFF
add mapped point Mem[2][0]/q Mem_reg[2][0]/Q -type DFF DFF
add mapped point Mem[2][1]/q Mem_reg[2][1]/Q -type DFF DFF
add mapped point Mem[2][2]/q Mem_reg[2][2]/Q -type DFF DFF
add mapped point Mem[2][3]/q Mem_reg[2][3]/Q -type DFF DFF
add mapped point Mem[2][4]/q Mem_reg[2][4]/Q -type DFF DFF
add mapped point Mem[2][5]/q Mem_reg[2][5]/Q -type DFF DFF
add mapped point Mem[2][6]/q Mem_reg[2][6]/Q -type DFF DFF
add mapped point Mem[2][7]/q Mem_reg[2][7]/Q -type DFF DFF
add mapped point Mem[3][0]/q Mem_reg[3][0]/Q -type DFF DFF
add mapped point Mem[3][1]/q Mem_reg[3][1]/Q -type DFF DFF
add mapped point Mem[3][2]/q Mem_reg[3][2]/Q -type DFF DFF
add mapped point Mem[3][3]/q Mem_reg[3][3]/Q -type DFF DFF
add mapped point Mem[3][4]/q Mem_reg[3][4]/Q -type DFF DFF
add mapped point Mem[3][5]/q Mem_reg[3][5]/Q -type DFF DFF
add mapped point Mem[3][6]/q Mem_reg[3][6]/Q -type DFF DFF
add mapped point Mem[3][7]/q Mem_reg[3][7]/Q -type DFF DFF
add mapped point Mem[4][0]/q Mem_reg[4][0]/Q -type DFF DFF
add mapped point Mem[4][1]/q Mem_reg[4][1]/Q -type DFF DFF
add mapped point Mem[4][2]/q Mem_reg[4][2]/Q -type DFF DFF
add mapped point Mem[4][3]/q Mem_reg[4][3]/Q -type DFF DFF
add mapped point Mem[4][4]/q Mem_reg[4][4]/Q -type DFF DFF
add mapped point Mem[4][5]/q Mem_reg[4][5]/Q -type DFF DFF
add mapped point Mem[4][6]/q Mem_reg[4][6]/Q -type DFF DFF
add mapped point Mem[4][7]/q Mem_reg[4][7]/Q -type DFF DFF
add mapped point Mem[5][0]/q Mem_reg[5][0]/Q -type DFF DFF
add mapped point Mem[5][1]/q Mem_reg[5][1]/Q -type DFF DFF
add mapped point Mem[5][2]/q Mem_reg[5][2]/Q -type DFF DFF
add mapped point Mem[5][3]/q Mem_reg[5][3]/Q -type DFF DFF
add mapped point Mem[5][4]/q Mem_reg[5][4]/Q -type DFF DFF
add mapped point Mem[5][5]/q Mem_reg[5][5]/Q -type DFF DFF
add mapped point Mem[5][6]/q Mem_reg[5][6]/Q -type DFF DFF
add mapped point Mem[5][7]/q Mem_reg[5][7]/Q -type DFF DFF
add mapped point Mem[6][0]/q Mem_reg[6][0]/Q -type DFF DFF
add mapped point Mem[6][1]/q Mem_reg[6][1]/Q -type DFF DFF
add mapped point Mem[6][2]/q Mem_reg[6][2]/Q -type DFF DFF
add mapped point Mem[6][3]/q Mem_reg[6][3]/Q -type DFF DFF
add mapped point Mem[6][4]/q Mem_reg[6][4]/Q -type DFF DFF
add mapped point Mem[6][5]/q Mem_reg[6][5]/Q -type DFF DFF
add mapped point Mem[6][6]/q Mem_reg[6][6]/Q -type DFF DFF
add mapped point Mem[6][7]/q Mem_reg[6][7]/Q -type DFF DFF
add mapped point Mem[7][0]/q Mem_reg[7][0]/Q -type DFF DFF
add mapped point Mem[7][1]/q Mem_reg[7][1]/Q -type DFF DFF
add mapped point Mem[7][2]/q Mem_reg[7][2]/Q -type DFF DFF
add mapped point Mem[7][3]/q Mem_reg[7][3]/Q -type DFF DFF
add mapped point Mem[7][4]/q Mem_reg[7][4]/Q -type DFF DFF
add mapped point Mem[7][5]/q Mem_reg[7][5]/Q -type DFF DFF
add mapped point Mem[7][6]/q Mem_reg[7][6]/Q -type DFF DFF
add mapped point Mem[7][7]/q Mem_reg[7][7]/Q -type DFF DFF
add mapped point Mem[8][0]/q Mem_reg[8][0]/Q -type DFF DFF
add mapped point Mem[8][1]/q Mem_reg[8][1]/Q -type DFF DFF
add mapped point Mem[8][2]/q Mem_reg[8][2]/Q -type DFF DFF
add mapped point Mem[8][3]/q Mem_reg[8][3]/Q -type DFF DFF
add mapped point Mem[8][4]/q Mem_reg[8][4]/Q -type DFF DFF
add mapped point Mem[8][5]/q Mem_reg[8][5]/Q -type DFF DFF
add mapped point Mem[8][6]/q Mem_reg[8][6]/Q -type DFF DFF
add mapped point Mem[8][7]/q Mem_reg[8][7]/Q -type DFF DFF
add mapped point Mem[9][0]/q Mem_reg[9][0]/Q -type DFF DFF
add mapped point Mem[9][1]/q Mem_reg[9][1]/Q -type DFF DFF
add mapped point Mem[9][2]/q Mem_reg[9][2]/Q -type DFF DFF
add mapped point Mem[9][3]/q Mem_reg[9][3]/Q -type DFF DFF
add mapped point Mem[9][4]/q Mem_reg[9][4]/Q -type DFF DFF
add mapped point Mem[9][5]/q Mem_reg[9][5]/Q -type DFF DFF
add mapped point Mem[9][6]/q Mem_reg[9][6]/Q -type DFF DFF
add mapped point Mem[9][7]/q Mem_reg[9][7]/Q -type DFF DFF
add mapped point Mem[10][0]/q Mem_reg[10][0]/Q -type DFF DFF
add mapped point Mem[10][1]/q Mem_reg[10][1]/Q -type DFF DFF
add mapped point Mem[10][2]/q Mem_reg[10][2]/Q -type DFF DFF
add mapped point Mem[10][3]/q Mem_reg[10][3]/Q -type DFF DFF
add mapped point Mem[10][4]/q Mem_reg[10][4]/Q -type DFF DFF
add mapped point Mem[10][5]/q Mem_reg[10][5]/Q -type DFF DFF
add mapped point Mem[10][6]/q Mem_reg[10][6]/Q -type DFF DFF
add mapped point Mem[10][7]/q Mem_reg[10][7]/Q -type DFF DFF
add mapped point Mem[11][0]/q Mem_reg[11][0]/Q -type DFF DFF
add mapped point Mem[11][1]/q Mem_reg[11][1]/Q -type DFF DFF
add mapped point Mem[11][2]/q Mem_reg[11][2]/Q -type DFF DFF
add mapped point Mem[11][3]/q Mem_reg[11][3]/Q -type DFF DFF
add mapped point Mem[11][4]/q Mem_reg[11][4]/Q -type DFF DFF
add mapped point Mem[11][5]/q Mem_reg[11][5]/Q -type DFF DFF
add mapped point Mem[11][6]/q Mem_reg[11][6]/Q -type DFF DFF
add mapped point Mem[11][7]/q Mem_reg[11][7]/Q -type DFF DFF
add mapped point Mem[12][0]/q Mem_reg[12][0]/Q -type DFF DFF
add mapped point Mem[12][1]/q Mem_reg[12][1]/Q -type DFF DFF
add mapped point Mem[12][2]/q Mem_reg[12][2]/Q -type DFF DFF
add mapped point Mem[12][3]/q Mem_reg[12][3]/Q -type DFF DFF
add mapped point Mem[12][4]/q Mem_reg[12][4]/Q -type DFF DFF
add mapped point Mem[12][5]/q Mem_reg[12][5]/Q -type DFF DFF
add mapped point Mem[12][6]/q Mem_reg[12][6]/Q -type DFF DFF
add mapped point Mem[12][7]/q Mem_reg[12][7]/Q -type DFF DFF
add mapped point Mem[13][0]/q Mem_reg[13][0]/Q -type DFF DFF
add mapped point Mem[13][1]/q Mem_reg[13][1]/Q -type DFF DFF
add mapped point Mem[13][2]/q Mem_reg[13][2]/Q -type DFF DFF
add mapped point Mem[13][3]/q Mem_reg[13][3]/Q -type DFF DFF
add mapped point Mem[13][4]/q Mem_reg[13][4]/Q -type DFF DFF
add mapped point Mem[13][5]/q Mem_reg[13][5]/Q -type DFF DFF
add mapped point Mem[13][6]/q Mem_reg[13][6]/Q -type DFF DFF
add mapped point Mem[13][7]/q Mem_reg[13][7]/Q -type DFF DFF
add mapped point Mem[14][0]/q Mem_reg[14][0]/Q -type DFF DFF
add mapped point Mem[14][1]/q Mem_reg[14][1]/Q -type DFF DFF
add mapped point Mem[14][2]/q Mem_reg[14][2]/Q -type DFF DFF
add mapped point Mem[14][3]/q Mem_reg[14][3]/Q -type DFF DFF
add mapped point Mem[14][4]/q Mem_reg[14][4]/Q -type DFF DFF
add mapped point Mem[14][5]/q Mem_reg[14][5]/Q -type DFF DFF
add mapped point Mem[14][6]/q Mem_reg[14][6]/Q -type DFF DFF
add mapped point Mem[14][7]/q Mem_reg[14][7]/Q -type DFF DFF
add mapped point Mem[15][0]/q Mem_reg[15][0]/Q -type DFF DFF
add mapped point Mem[15][1]/q Mem_reg[15][1]/Q -type DFF DFF
add mapped point Mem[15][2]/q Mem_reg[15][2]/Q -type DFF DFF
add mapped point Mem[15][3]/q Mem_reg[15][3]/Q -type DFF DFF
add mapped point Mem[15][4]/q Mem_reg[15][4]/Q -type DFF DFF
add mapped point Mem[15][5]/q Mem_reg[15][5]/Q -type DFF DFF
add mapped point Mem[15][6]/q Mem_reg[15][6]/Q -type DFF DFF
add mapped point Mem[15][7]/q Mem_reg[15][7]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
